const verses = [
  {
    chapter : 1,
    number  : 1,
    sloka   : [
      "मुदाकरात्तमोदकं सदा विमुक्तिसाधकं",
      "कलाधरावतंसकं विलासिलोकरक्षकम् ।",
      "अनायकैकनायकं विनाशितेभदैत्यकं",
      "नताशुभाशुनाशकं नमामि तं विनायकम् ॥१॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 2,
    sloka   : [
      "अनुष्टुप् छन्दः ।",
      "श्रीमहाविष्णुः परमात्मा श्रीमन्नारायणो देवता ।",
      "अमृतांशूद्भवो भानुरिति बीजम् ।",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 3,
    sloka   : [
      "देवकीनन्दनः स्रष्टेति शक्तिः ।",
      "उद्भवः क्षोभणो देव इति परमो मन्त्रः ।",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 4,
    sloka   : [
      "शङ्खभृन्नन्दकी चक्रीति कीलकम् ।",
      "शार्ङ्गधन्वा गदाधर इत्यस्त्रम् ।",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 5,
    sloka   : [
      "रथाङ्गपाणिरक्षोभ्य इति नेत्रम् ।",
      "त्रिसामा सामगः सामेति कवचम् ।",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 6,
    sloka   : [
      "नमः समस्तभूतानामादिभूताय भूभृते ।",
      "अनेकरूपरूपाय विष्णवे प्रभविष्णवे ॥ ५॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
];

export default verses;