const verses = [
  {
    chapter : 2,
    number  : 1,
    sloka   : [
      "( श्रीवेदव्यास उवाच )",
      "अस्य श्रीविष्णोर्दिव्यसहस्रनामस्तोत्रमहामन्त्रस्य ।",
      "श्रीवेदव्यासो भगवान् ऋषिः ।",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    prose  : [],
    transl : [],
    transl_tel: [],
    essence: [],
    meanings: [],
    grammar: [],
    notes   : [],
  },
  {
    chapter : 2,
    number  : 2,
    sloka   : [
      "अनुष्टुप् छन्दः ।",
      "श्रीमहाविष्णुः परमात्मा श्रीमन्नारायणो देवता ।",
      "अमृतांशूद्भवो भानुरिति बीजम् ।",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    prose  : [],
    transl : [],
    transl_tel: [],
    essence: [],
    meanings: [],
    grammar: [],
    notes   : [],
  },
  {
    chapter : 2,
    number  : 3,
    sloka   : [
      "देवकीनन्दनः स्रष्टेति शक्तिः ।",
      "उद्भवः क्षोभणो देव इति परमो मन्त्रः ।",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    prose  : [],
    transl : [],
    transl_tel: [],
    essence: [],
    meanings: [],
    grammar: [],
    notes   : [],
  },
  {
    chapter : 2,
    number  : 4,
    sloka   : [
      "शङ्खभृन्नन्दकी चक्रीति कीलकम् ।",
      "शार्ङ्गधन्वा गदाधर इत्यस्त्रम् ।",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    prose  : [],
    transl : [],
    transl_tel: [],
    essence: [],
    meanings: [],
    grammar: [],
    notes   : [],
  },
  {
    chapter : 2,
    number  : 5,
    sloka   : [
      "रथाङ्गपाणिरक्षोभ्य इति नेत्रम् ।",
      "त्रिसामा सामगः सामेति कवचम् ।",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    prose  : [],
    transl : [],
    transl_tel: [],
    essence: [],
    meanings: [],
    grammar: [],
    notes   : [],
  },
  {
    chapter : 2,
    number  : 6,
    sloka   : [
      "नमः समस्तभूतानामादिभूताय भूभृते ।",
      "अनेकरूपरूपाय विष्णवे प्रभविष्णवे ॥ ५॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    prose  : [],
    transl : [],
    transl_tel: [],
    essence: [],
    meanings: [],
    grammar: [],
    notes   : [],
  },
  {
    chapter : 2,
    number  : 7,
    sloka   : [
      "आनन्दं परब्रह्मेति योनिः ।",
      "ऋतुः सुदर्शनः काल इति दिग्बन्धः ।",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    prose  : [],
    transl : [],
    transl_tel: [],
    essence: [],
    meanings: [],
    grammar: [],
    notes   : [],
  },
  {
    chapter : 2,
    number  : 8,
    sloka   : [
      "श्रीविश्वरूप इति ध्यानम् ।",
      "श्रीमहाविष्णुप्रीत्यर्थे सहस्रनामस्तोत्रपाठे विनियोगः ॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    prose  : [],
    transl : [],
    transl_tel: [],
    essence: [],
    meanings: [],
    grammar: [],
    notes   : [],
  },
];

export default verses;