const verses = [
  {
    chapter : 4,
    number  : 1,
    sloka   : [
      "हरिः ॐ ।",
      "ॐ विश्वं विष्णुर्वषट्कारो भूतभव्यभवत्प्रभुः ।",
      "भूतकृद्भूतभृद्भावो भूतात्मा भूतभावनः ॥ १॥",
    ],
    sloka_tel : [
      "హరిః ఓమ్ |",
      "ఓం విశ్వం విష్ణుర్వషట్కారో భూతభవ్యభవత్ప్రభుః |",
      "భూతకృద్భూతభృద్భావో భూతాత్మా భూతభావనః ॥ ౧॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 2,
    sloka   : [
      "पूतात्मा परमात्मा च मुक्तानां परमा गतिः ।",
      "अव्ययः पुरुषः साक्षी क्षेत्रज्ञोऽक्षर एव च ॥ २॥",
    ],
    sloka_tel : [
      "పూతాత్మా పరమాత్మా చ ముక్తానాం పరమా గతిః |",
      "అవ్యయః పురుషః సాక్షీ క్షేత్రజ్ఞోऽక్షర ఏవ చ ॥ ౨॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 3,
    sloka   : [
      "योगो योगविदां नेता प्रधानपुरुषेश्वरः ।",
      "नारसिंहवपुः श्रीमान् केशवः पुरुषोत्तमः ॥ ३॥",
    ],
    sloka_tel : [
      "యోగో యోగవిదాం నేతా ప్రధానపురుషేశ్వరః |",
      "నారసింహవపుః శ్రీమాన్ కేశవః పురుషోత్తమః ॥ ౩॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 4,
    sloka   : [
      "सर्वः शर्वः शिवः स्थाणुर्भूतादिर्निधिरव्ययः ।",
      "सम्भवो भावनो भर्ता प्रभवः प्रभुरीश्वरः ॥ ४॥",
    ],
    sloka_tel : [
      "సర్వః శర్వః శివః స్థాణుర్భూతాదిర్నిధిరవ్యయః |",
      "సమ్భవో భావనో భర్తా ప్రభవః ప్రభురీశ్వరః ॥ ౪॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 5,
    sloka   : [
      "स्वयम्भूः शम्भुरादित्यः पुष्कराक्षो महास्वनः ।",
      "अनादिनिधनो धाता विधाता धातुरुत्तमः ॥ ५॥",
    ],
    sloka_tel : [
      "స్వయమ్భూః శమ్భురాదిత్యః పుష్కరాక్షో మహాస్వనః |",
      "అనాదినిధనో ధాతా విధాతా ధాతురుత్తమః ॥ ౫॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 6,
    sloka   : [
      "अप्रमेयो हृषीकेशः पद्मनाभोऽमरप्रभुः ।",
      "विश्वकर्मा मनुस्त्वष्टा स्थविष्ठः स्थविरो ध्रुवः ॥ ६॥",
    ],
    sloka_tel : [
      "అప్రమేయో హృషీకేశః పద్మనాభోऽమరప్రభుః |",
      "విశ్వకర్మా మనుస్త్వష్టా స్థవిష్ఠః స్థవిరో ధ్రువః ॥ ౬॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 7,
    sloka   : [
      "अग्राह्यः शाश्वतः कृष्णो लोहिताक्षः प्रतर्दनः ।",
      "प्रभूतस्त्रिककुब्धाम पवित्रं मङ्गलं परम् ॥ ७॥",
    ],
    sloka_tel : [
      "అగ్రాహ్యః శాశ్వతః కృష్ణో లోహితాక్షః ప్రతర్దనః |",
      "ప్రభూతస్త్రికకుబ్ధామ పవిత్రం మఙ్గలం పరమ్ ॥ ౭॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 8,
    sloka   : [
      "ईशानः प्राणदः प्राणो ज्येष्ठः श्रेष्ठः प्रजापतिः ।",
      "हिरण्यगर्भो भूगर्भो माधवो मधुसूदनः ॥ ८॥",
    ],
    sloka_tel : [
      "ఈశానః ప్రాణదః ప్రాణో జ్యేష్ఠః శ్రేష్ఠః ప్రజాపతిః |",
      "హిరణ్యగర్భో భూగర్భో మాధవో మధుసూదనః ॥ ౮॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 9,
    sloka   : [
      "ईश्वरो विक्रमी धन्वी मेधावी विक्रमः क्रमः ।",
      "अनुत्तमो दुराधर्षः कृतज्ञः कृतिरात्मवान् ॥ ९॥",
    ],
    sloka_tel : [
      "ఈశ్వరో విక్రమీ ధన్వీ మేధావీ విక్రమః క్రమః |",
      "అనుత్తమో దురాధర్షః కృతజ్ఞః కృతిరాత్మవాన్ ॥ ౯॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 10,
    sloka   : [
      "सुरेशः शरणं शर्म विश्वरेताः प्रजाभवः ।",
      "अहः संवत्सरो व्यालः प्रत्ययः सर्वदर्शनः ॥ १०॥",
    ],
    sloka_tel : [
      "సురేశః శరణం శర్మ విశ్వరేతాః ప్రజాభవః |",
      "అహః సంవత్సరో వ్యాలః ప్రత్యయః సర్వదర్శనః ॥ ౧౦॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 11,
    sloka   : [
      "अजः सर्वेश्वरः सिद्धः सिद्धिः सर्वादिरच्युतः ।",
      "वृषाकपिरमेयात्मा सर्वयोगविनिःसृतः ॥ ११॥",
    ],
    sloka_tel : [
      "అజః సర్వేశ్వరః సిద్ధః సిద్ధిః సర్వాదిరచ్యుతః |",
      "వృషాకపిరమేయాత్మా సర్వయోగవినిఃసృతః ॥ ౧౧॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 12,
    sloka   : [
      "वसुर्वसुमनाः सत्यः समात्माऽसम्मितः समः ।",
      "अमोघः पुण्डरीकाक्षो वृषकर्मा वृषाकृतिः ॥ १२॥",
    ],
    sloka_tel : [
      "వసుర్వసుమనాః సత్యః సమాత్మాऽసమ్మితః సమః |",
      "అమోఘః పుండరీకాక్షో వృషకర్మా వృషాకృతిః ॥ ౧౨॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 13,
    sloka   : [
      "रुद्रो बहुशिरा बभ्रुर्विश्वयोनिः शुचिश्रवाः ।",
      "अमृतः शाश्वतस्थाणुर्वरारोहो महातपाः ॥ १३॥",
    ],
    sloka_tel : [
      "రుద్రో బహుశిరా బభ్రుర్విశ్వయోనిః శుచిశ్రవాః |",
      "అమృతః శాశ్వతస్థాణుర్వరారోహో మహాతపాః ॥ ౧౩॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 14,
    sloka   : [
      "सर्वगः सर्वविद्भानुर्विष्वक्सेनो जनार्दनः ।",
      "वेदो वेदविदव्यङ्गो वेदाङ्गो वेदवित् कविः ॥ १४॥",
    ],
    sloka_tel : [
      "సర్వగః సర్వవిద్భానుర్విష్వక్సేనో జనార్దనః |",
      "వేదో వేదవిదవ్యఙ్గో వేదాఙ్గో వేదవిత్ కవిః ॥ ౧౪॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 15,
    sloka   : [
      "लोकाध्यक्षः सुराध्यक्षो धर्माध्यक्षः कृताकृतः ।",
      "चतुरात्मा चतुर्व्यूहश्चतुर्दंष्ट्रश्चतुर्भुजः ॥ १५॥",
    ],
    sloka_tel : [
      "లోకాధ్యక్షః సురాధ్యక్షో ధర్మాధ్యక్షః కృతాకృతః |",
      "చతురాత్మా చతుర్వ్యూహశ్చతుర్దంష్ట్రశ్చతుర్భుజః ॥ ౧౫॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 16,
    sloka   : [
      "भ्राजिष्णुर्भोजनं भोक्ता सहिष्णुर्जगदादिजः ।",
      "अनघो विजयो जेता विश्वयोनिः पुनर्वसुः ॥ १६॥",
    ],
    sloka_tel : [
      "భ్రాజిష్ణుర్భోజనం భోక్తా సహిష్ణుర్జగదాదిజః |",
      "అనఘో విజయో జేతా విశ్వయోనిః పునర్వసుః ॥ ౧౬॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 17,
    sloka   : [
      "उपेन्द्रो वामनः प्रांशुरमोघः शुचिरूर्जितः ।",
      "अतीन्द्रः सङ्ग्रहः सर्गो धृतात्मा नियमो यमः ॥ १७॥",
    ],
    sloka_tel : [
      "ఉపేన్ద్రో వామనః ప్రాంశురమోఘః శుచిరూర్జితః |",
      "అతీన్ద్రః సఙ్గ్రహః సర్గో ధృతాత్మా నియమో యమః ॥ ౧౭॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 18,
    sloka   : [
      "वेद्यो वैद्यः सदायोगी वीरहा माधवो मधुः ।",
      "अतीन्द्रियो महामायो महोत्साहो महाबलः ॥ १८॥",
    ],
    sloka_tel : [
      "వేద్యో వైద్యః సదాయోగీ వీరహా మాధవో మధుః |",
      "అతీన్ద్రియో మహామాయో మహోత్సాహో మహాబలః ॥ ౧౮॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 19,
    sloka   : [
      "महाबुद्धिर्महावीर्यो महाशक्तिर्महाद्युतिः ।",
      "अनिर्देश्यवपुः श्रीमानमेयात्मा महाद्रिधृक् ॥ १९॥",
    ],
    sloka_tel : [
      "మహాబుద్ధిర్మహావీర్యో మహాశక్తిర్మహాద్యుతిః |",
      "అనిర్దేశ్యవపుః శ్రీమానమేయాత్మా మహాద్రిధృక్ ॥ ౧౯॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 20,
    sloka   : [
      "महेष्वासो महीभर्ता श्रीनिवासः सतां गतिः ।",
      "अनिरुद्धः सुरानन्दो गोविन्दो गोविदां पतिः ॥ २०॥",
    ],
    sloka_tel : [
      "మహేష్వాసో మహీభర్తా శ్రీనివాసః సతాం గతిః |",
      "అనిరుద్ధః సురానన్దో గోవిన్దో గోవిదాం పతిః ॥ ౨౦॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 21,
    sloka   : [
      "मरीचिर्दमनो हंसः सुपर्णो भुजगोत्तमः ।",
      "हिरण्यनाभः सुतपाः पद्मनाभः प्रजापतिः ॥ २१॥",
    ],
    sloka_tel : [
      "మరీచిర్దమనో హంసః సుపర్ణో భుజగోత్తమః |",
      "హిరణ్యనాభః సుతపాః పద్మనాభః ప్రజాపతిః ॥ ౨౧॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 22,
    sloka   : [
      "अमृत्युः सर्वदृक् सिंहः सन्धाता सन्धिमान् स्थिरः ।",
      "अजो दुर्मर्षणः शास्ता विश्रुतात्मा सुरारिहा ॥ २२॥",
    ],
    sloka_tel : [
      "అమృత్యుః సర్వదృక్ సింహః సన్ధాతా సన్ధిమాన్ స్థిరః |",
      "అజో దుర్మర్షణః శాస్తా విశ్రుతాత్మా సురారిహా ॥ ౨౨॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 23,
    sloka   : [
      "गुरुर्गुरुतमो धाम सत्यः सत्यपराक्रमः ।",
      "निमिषोऽनिमिषः स्रग्वी वाचस्पतिरुदारधीः ॥ २३॥",
    ],
    sloka_tel : [
      "గురుర్గురుతమో ధామ సత్యః సత్యపరాక్రమః |",
      "నిమిషోऽనిమిషః స్రగ్వీ వాచస్పతిరుదారధీః ॥ ౨౩॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 24,
    sloka   : [
      "अग्रणीर्ग्रामणीः श्रीमान् न्यायो नेता समीरणः ।",
      "सहस्रमूर्धा विश्वात्मा सहस्राक्षः सहस्रपात् ॥ २४॥",
    ],
    sloka_tel : [
      "అగ్రణీర్గ్రామణీః శ్రీమాన్ న్యాయో నేతా సమీరణః |",
      "సహస్రమూర్ధా విశ్వాత్మా సహస్రాక్షః సహస్రపాత్ ॥ ౨౪॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 25,
    sloka   : [
      "आवर्तनो निवृत्तात्मा संवृतः सम्प्रमर्दनः ।",
      "अहः संवर्तको वह्निरनिलो धरणीधरः ॥ २५॥",
    ],
    sloka_tel : [
      "ఆవర్తనో నివృత్తాత్మా సంవృతః సమ్ప్రమర్దనః |",
      "అహః సంవర్తకో వహ్నిరనిలో ధరణీధరః ॥ ౨౫॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
{
    chapter : 4,
    number  : 26,
    sloka   : [
      "सुप्रसादः प्रसन्नात्मा विश्वधृग्विश्वभुग्विभुः ।",
      "सत्कर्ता सत्कृतः साधुर्जह्नुर्नारायणो नरः ॥ २६॥",
    ],
    sloka_tel : [
      "సుప్రసాదః ప్రసన్నాత్మా విశ్వధృగ్విశ్వభుగ్విభుః |",
      "సత్కర్తా సత్కృతః సాధుర్జహ్నుర్నారాయణో నరః ॥ ౨౬॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 27,
    sloka   : [
      "असङ्ख्येयोऽप्रमेयात्मा विशिष्टः शिष्टकृच्छुचिः ।",
      "सिद्धार्थः सिद्धसङ्कल्पः सिद्धिदः सिद्धिसाधनः ॥ २७॥",
    ],
    sloka_tel : [
      "అసఙ్ఖ్యేయోऽప్రమేయాత్మా విశిష్టః శిష్టకృచ్ఛుచిః |",
      "సిద్ధార్థః సిద్ధసఙ్కల్పః సిద్ధిదః సిద్ధిసాధనః ॥ ౨౭॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 28,
    sloka   : [
      "वृषाही वृषभो विष्णुर्वृषपर्वा वृषोदरः ।",
      "वर्धनो वर्धमानश्च विविक्तः श्रुतिसागरः ॥ २८॥",
    ],
    sloka_tel : [
      "వృషాహీ వృషభో విష్ణుర్వృషపర్వా వృషోదరః |",
      "వర్ధనో వర్ధమానశ్చ వివిక్తః శ్రుతిసాగరః ॥ ౨౮॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 29,
    sloka   : [
      "सुभुजो दुर्धरो वाग्मी महेन्द्रो वसुदो वसुः ।",
      "नैकरूपो बृहद्रूपः शिपिविष्टः प्रकाशनः ॥ २९॥",
    ],
    sloka_tel : [
      "సుభుజో దుర్ధరో వాగ్మీ మహేన్ద్రో వసుదో వసుః |",
      "నైకరూపో బృహద్రూపః శిపివిష్టః ప్రకాశనః ॥ ౨౯॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 30,
    sloka   : [
      "ओजस्तेजोद्युतिधरः प्रकाशात्मा प्रतापनः ।",
      "ऋद्धः स्पष्टाक्षरो मन्त्रश्चन्द्रांशुर्भास्करद्युतिः ॥ ३०॥",
    ],
    sloka_tel : [
      "ఓజస్తేజోద్యుతిధరః ప్రకాశాత్మా ప్రతాపనః |",
      "ఋద్ధః స్పష్టాక్షరో మన్త్రశ్చన్ద్రాంశుర్భాస్కరద్యుతిః ॥ ౩౦॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 31,
    sloka   : [
      "अमृतांशूद्भवो भानुः शशबिन्दुः सुरेश्वरः ।",
      "औषधं जगतः सेतुः सत्यधर्मपराक्रमः ॥ ३१॥",
    ],
    sloka_tel : [
      "అమృతాంశూద్భవో భానుః శశబిన్దుః సురేశ్వరః |",
      "ఔషధం జగతః సేతుః సత్యధర్మపరాక్రమః ॥ ౩౧॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 32,
    sloka   : [
      "भूतभव्यभवन्नाथः पवनः पावनोऽनलः ।",
      "कामहा कामकृत्कान्तः कामः कामप्रदः प्रभुः ॥ ३२॥",
    ],
    sloka_tel : [
      "భూతభవ్యభవన్నాతః పవనః పావనోऽనలః |",
      "కామహా కామకృత్కాన్తః కామః కామప్రదః ప్రభుః ॥ ౩౨॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 33,
    sloka   : [
      "युगादिकृद्युगावर्तो नैकमायो महाशनः ।",
      "अदृश्यो व्यक्तरूपश्च सहस्रजिदनन्तजित् ॥ ३३॥",
    ],
    sloka_tel : [
      "యుగాదికృద్యుగావర్తో నైకమాయో మహాశనః |",
      "అదృశ్యో వ్యక్తరూపశ్చ సహస్రజిదనన్తజిత్ ॥ ౩౩॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 34,
    sloka   : [
      "इष्टोऽविशिष्टः शिष्टेष्टः शिखण्डी नहुषो वृषः ।",
      "क्रोधहा क्रोधकृत्कर्ता विश्वबाहुर्महीधरः ॥ ३४॥",
    ],
    sloka_tel : [
      "ఇష్టోऽవిశిష్టః శిష్టేష్టః శిఖణ్డీ నహుషో వృషః |",
      "క్రోధహా క్రోధకృత్కర్తా విశ్వబాహుర్మహీధరః ॥ ౩౪॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 35,
    sloka   : [
      "अच्युतः प्रथितः प्राणः प्राणदो वासवानुजः ।",
      "अपांनिधिरधिष्ठानमप्रमत्तः प्रतिष्ठितः ॥ ३५॥",
    ],
    sloka_tel : [
      "అచ్యుతః ప్రథితః ప్రాణః ప్రాణదో వాసవానుజః |",
      "అపాంనిధిరధిష్ఠానమప్రమత్తః ప్రతిష్ఠితః ॥ ౩౫॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 36,
    sloka   : [
      "स्कन्दः स्कन्दधरो धुर्यो वरदो वायुवाहनः ।",
      "वासुदेवो बृहद्भानुरादिदेवः पुरन्दरः ॥ ३६॥",
    ],
    sloka_tel : [
      "స్కన్దః స్కన్దధరో ధుర్యో వరదో వాయువాహనః |",
      "వాసుదేవో బృహద్భానురాదిదేవః పురన్దరః ॥ ౩౬॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 37,
    sloka   : [
      "अशोकस्तारणस्तारः शूरः शौरिर्जनेश्वरः ।",
      "अनुकूलः शतावर्तः पद्मी पद्मनिभेक्षणः ॥ ३७॥",
    ],
    sloka_tel : [
      "అశోకస్తారణస్తారః శూరః శౌరిర్జనేశ్వరః |",
      "అనుకూలః శతావర్తః పద్మీ పద్మనిభేక్షణః ॥ ౩౭॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 38,
    sloka   : [
      "पद्मनाभोऽरविन्दाक्षः पद्मगर्भः शरीरभृत् ।",
      "महर्द्धिरृद्धो वृद्धात्मा महाक्षो गरुडध्वजः ॥ ३८॥",
    ],
    sloka_tel : [
      "పద్మనాభోऽరవిన్దాక్షః పద్మగర్భః శరీరభృత్ |",
      "మహర్ద్ధిరృద్ధో వృద్ధాత్మా మహాక్షో గరుడధ్వజః ॥ ౩౮॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 39,
    sloka   : [
      "अतुलः शरभो भीमः समयज्ञो हविर्हरिः ।",
      "सर्वलक्षणलक्षण्यो लक्ष्मीवान् समितिञ्जयः ॥ ३९॥",
    ],
    sloka_tel : [
      "అతులః శరభో భీమః సమయజ్ఞో హవిర్హరిః |",
      "సర్వలక్షణలక్షణ్యో లక్ష్మీవాన్ సమితిఞ్జయః ॥ ౩౯॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 40,
    sloka   : [
      "विक्षरो रोहितो मार्गो हेतुर्दामोदरः सहः ।",
      "महीधरो महाभागो वेगवानमिताशनः ॥ ४०॥",
    ],
    sloka_tel : [
      "విక్షరో రోహితో మార్గో హేతుర్దామోదరః సహః |",
      "మహీధరో మహాభాగో వేగవానమితాశనః ॥ ౪౦॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 41,
    sloka   : [
      "उद्भवः क्षोभणो देवः श्रीगर्भः परमेश्वरः ।",
      "करणं कारणं कर्ता विकर्ता गहनो गुहः ॥ ४१॥",
    ],
    sloka_tel : [
      "ఉద్భవః క్షోభణో దేవః శ్రీగర్భః పరమేశ్వరః |",
      "కరణం కారణం కర్తా వికర్తా గహనో గుహః ॥ ౪౧॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 42,
    sloka   : [
      "व्यवसायो व्यवस्थानः संस्थानः स्थानदो ध्रुवः ।",
      "परर्द्धिः परमस्पष्टस्तुष्टः पुष्टः शुभेक्षणः ॥ ४२॥",
    ],
    sloka_tel : [
      "వ్యవసాయో వ్యవస్థానః సంస్థానః స్థానదో ధ్రువః |",
      "పరర్ద్ధిః పరమస్పష్టస్తుష్టః పుష్టః శుభేక్షణః ॥ ౪౨॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 43,
    sloka   : [
      "रामो विरामो विरजो मार्गो नेयो नयोऽनयः । (विरामो विरतो)",
      "वीरः शक्तिमतां श्रेष्ठो धर्मो धर्मविदुत्तमः ॥ ४३॥",
    ],
    sloka_tel : [
      "రామో విరామో విరజో మార్గో నేయో నయోऽనయః | (విరామో విరతో)",
      "వీరః శక్తిమతాం శ్రేష్ఠో ధర్మో ధర్మవిదుత్తమః ॥ ౪౩॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 44,
    sloka   : [
      "वैकुण्ठः पुरुषः प्राणः प्राणदः प्रणवः पृथुः ।",
      "हिरण्यगर्भः शत्रुघ्नो व्याप्तो वायुरधोक्षजः ॥ ४४॥",
    ],
    sloka_tel : [
      "వైకుణ్ఠః పురుషః ప్రాణః ప్రాణదః ప్రణవః పృథుః |",
      "హిరణ్యగర్భః శత్రుఘ్నో వ్యాప్తో వాయురధోక్షజః ॥ ౪౪॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 45,
    sloka   : [
      "ऋतुः सुदर्शनः कालः परमेष्ठी परिग्रहः ।",
      "उग्रः संवत्सरो दक्षो विश्रामो विश्वदक्षिणः ॥ ४५॥",
    ],
    sloka_tel : [
      "ఋతుః సుదర్శనః కాలః పరమేష్ఠీ పరిగ్రహః |",
      "ఉగ్రః సంవత్సరో దక్షో విశ్రామో విశ్వదక్షిణః ॥ ౪౫॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 46,
    sloka   : [
      "विस्तारः ५स्थावरस्थाणुः प्रमाणं बीजमव्ययम् ।",
      "अर्थोऽनर्थो महाकोशो महाभोगो महाधनः ॥ ४६॥",
    ],
    sloka_tel : [
      "విస్తారః స్థావరస్థాణుః ప్రమాణం బీజమవ్యయమ్ |",
      "ార్థోऽనర్థో మహాకోశో మహాభోగో మహాధనః ॥ ౪౬॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 47,
    sloka   : [
      "अनिर्विण्णः स्थविष्ठोऽभूर्धर्मयूपो महामखः ।",
      "नक्षत्रनेमिर्नक्षत्री क्षमः क्षामः समीहनः ॥ ४७॥",
    ],
    sloka_tel : [
      "అనిర్విణ్ణః స్థవిష్ఠోऽభూర్ధర్మయూపో మహామఖః |",
      "నక్షత్రనేమిర్నక్షత్రీ క్షమః క్షామః సమీహనః ॥ ౪౭॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 48,
    sloka   : [
      "यज्ञ इज्यो महेज्यश्च क्रतुः सत्रं सतां गतिः ।",
      "सर्वदर्शी विमुक्तात्मा सर्वज्ञो ज्ञानमुत्तमम् ॥ ४८॥",
    ],
    sloka_tel : [
      "యజ్ఞ ఇజ్యో మహేజ్యశ్చ క్రతుః సత్రం సతాం గతిః |",
      "సర్వదర్శీ విముక్తాత్మా సర్వజ్ఞో జ్ఞానముత్తమమ్ ॥ ౪౮॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 49,
    sloka   : [
      "सुव्रतः सुमुखः सूक्ष्मः सुघोषः सुखदः सुहृत् ।",
      "मनोहरो जितक्रोधो वीरबाहुर्विदारणः ॥ ४९॥",
    ],
    sloka_tel : [
      "సువ్రతః సుముఖః సూక్ష్మః సుఘోషః సుఖదః సుహృత్ |",
      "మనోహరో జితక్రోధో వీరబాహుర్విదారణః ॥ ౪౯॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 50,
    sloka   : [
      "स्वापनः स्ववशो व्यापी नैकात्मा नैककर्मकृत् ।",
      "वत्सरो वत्सलो वत्सी रत्नगर्भो धनेश्वरः ॥ ५०॥",
    ],
    sloka_tel : [
      "స్వాపనః స్వవశో వ్యాపీ నైకాత్మా నైకకర్మకృత్ |",
      "వత్సరో వత్సలో వత్సీ రత్నగర్భో ధనేశ్వరః ॥ ౫౦॥"
    ],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 51,
    sloka   : [
      "धर्मगुब्धर्मकृद्धर्मी सदसत्क्षरमक्षरम् ।",
      "अविज्ञाता सहस्रांशुर्विधाता कृतलक्षणः ॥ ५१॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 52,
    sloka   : [
      "गभस्तिनेमिः सत्त्वस्थः सिंहो भूतमहेश्वरः ।",
      "आदिदेवो महादेवो देवेशो देवभृद्गुरुः ॥ ५२॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 53,
    sloka   : [
      "उत्तरो गोपतिर्गोप्ता ज्ञानगम्यः पुरातनः ।",
      "शरीरभूतभृद्भोक्ता कपीन्द्रो भूरिदक्षिणः ॥ ५३॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 54,
    sloka   : [
      "सोमपोऽमृतपः सोमः पुरुजित्पुरुसत्तमः ।",
      "विनयो जयः सत्यसन्धो दाशार्हः सात्वताम्पतिः ॥ ५४॥ विनियोज्यः",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 55,
    sloka   : [
      "जीवो विनयिता साक्षी मुकुन्दोऽमितविक्रमः ।",
      "अम्भोनिधिरनन्तात्मा महोदधिशयोऽन्तकः ॥ ५५॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 56,
    sloka   : [
      "अजो महार्हः स्वाभाव्यो जितामित्रः प्रमोदनः ।",
      "आनन्दो नन्दनो नन्दः सत्यधर्मा त्रिविक्रमः ॥ ५६॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 57,
    sloka   : [
      "महर्षिः कपिलाचार्यः कृतज्ञो मेदिनीपतिः ।",
      "त्रिपदस्त्रिदशाध्यक्षो महाश‍ृङ्गः कृतान्तकृत् ॥ ५७॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 58,
    sloka   : [
      "महावराहो गोविन्दः सुषेणः कनकाङ्गदी ।",
      "गुह्यो गभीरो गहनो गुप्तश्चक्रगदाधरः ॥ ५८॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 59,
    sloka   : [
      "वेधाः स्वाङ्गोऽजितः कृष्णो दृढः सङ्कर्षणोऽच्युतः ।",
      "वरुणो वारुणो वृक्षः पुष्कराक्षो महामनाः ॥ ५९॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 60,
    sloka   : [
      "भगवान् भगहाऽऽनन्दी वनमाली हलायुधः ।",
      "आदित्यो ज्योतिरादित्यः सहिष्णुर्गतिसत्तमः ॥ ६०॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 61,
    sloka   : [
      "सुधन्वा खण्डपरशुर्दारुणो द्रविणप्रदः ।",
      "दिवस्पृक् सर्वदृग्व्यासो वाचस्पतिरयोनिजः ॥ ६१॥ (दिविस्पृक्)"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 62,
    sloka   : [
      "त्रिसामा सामगः साम निर्वाणं भेषजं भिषक् ।",
      "संन्यासकृच्छमः शान्तो निष्ठा शान्तिः परायणम् ॥ ६२॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 63,
    sloka   : [
      "शुभाङ्गः शान्तिदः स्रष्टा कुमुदः कुवलेशयः ।",
      "गोहितो गोपतिर्गोप्ता वृषभाक्षो वृषप्रियः ॥ ६३॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 64,
    sloka   : [
      "अनिवर्ती निवृत्तात्मा सङ्क्षेप्ता क्षेमकृच्छिवः ।",
      "श्रीवत्सवक्षाः श्रीवासः श्रीपतिः श्रीमतांवरः ॥ ६४॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 65,
    sloka   : [
      "श्रीदः श्रीशः श्रीनिवासः श्रीनिधिः श्रीविभावनः ।",
      "श्रीधरः श्रीकरः श्रेयः श्रीमाँल्लोकत्रयाश्रयः ॥ ६५॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 66,
    sloka   : [
      "स्वक्षः स्वङ्गः शतानन्दो नन्दिर्ज्योतिर्गणेश्वरः ।",
      "विजितात्माऽविधेयात्मा सत्कीर्तिश्छिन्नसंशयः ॥ ६६॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 67,
    sloka   : [
      "उदीर्णः सर्वतश्चक्षुरनीशः शाश्वतस्थिरः ।",
      "भूशयो भूषणो भूतिर्विशोकः शोकनाशनः ॥ ६७॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 68,
    sloka   : [
      "अर्चिष्मानर्चितः कुम्भो विशुद्धात्मा विशोधनः ।",
      "अनिरुद्धोऽप्रतिरथः प्रद्युम्नोऽमितविक्रमः ॥ ६८॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 69,
    sloka   : [
      "कालनेमिनिहा वीरः शौरिः शूरजनेश्वरः ।",
      "त्रिलोकात्मा त्रिलोकेशः केशवः केशिहा हरिः ॥ ६९॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 70,
    sloka   : [
      "कामदेवः कामपालः कामी कान्तः कृतागमः ।",
      "अनिर्देश्यवपुर्विष्णुर्वीरोऽनन्तो धनञ्जयः ॥ ७०॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 71,
    sloka   : [
      "ब्रह्मण्यो ब्रह्मकृद् ब्रह्मा ब्रह्म ब्रह्मविवर्धनः ।",
      "ब्रह्मविद् ब्राह्मणो ब्रह्मी ब्रह्मज्ञो ब्राह्मणप्रियः ॥ ७१॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 72,
    sloka   : [
      "महाक्रमो महाकर्मा महातेजा महोरगः ।",
      "महाक्रतुर्महायज्वा महायज्ञो महाहविः ॥ ७२॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 73,
    sloka   : [
      "स्तव्यः स्तवप्रियः स्तोत्रं स्तुतिः स्तोता रणप्रियः ।",
      "पूर्णः पूरयिता पुण्यः पुण्यकीर्तिरनामयः ॥ ७३॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 74,
    sloka   : [
      "मनोजवस्तीर्थकरो वसुरेता वसुप्रदः ।",
      "वसुप्रदो वासुदेवो वसुर्वसुमना हविः ॥ ७४॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 75,
    sloka   : [
      "सद्गतिः सत्कृतिः सत्ता सद्भूतिः सत्परायणः ।",
      "शूरसेनो यदुश्रेष्ठः सन्निवासः सुयामुनः ॥ ७५॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 76,
    sloka   : [
      "भूतावासो वासुदेवः सर्वासुनिलयोऽनलः ।",
      "दर्पहा दर्पदो दृप्तो दुर्धरोऽथापराजितः ॥ ७६॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 77,
    sloka   : [
      "विश्वमूर्तिर्महामूर्तिर्दीप्तमूर्तिरमूर्तिमान् ।",
      "अनेकमूर्तिरव्यक्तः शतमूर्तिः शताननः ॥ ७७॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 78,
    sloka   : [
      "एको नैकः सवः कः किं यत् तत्पदमनुत्तमम् ।",
      "लोकबन्धुर्लोकनाथो माधवो भक्तवत्सलः ॥ ७८॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 79,
    sloka   : [
      "सुवर्णवर्णो हेमाङ्गो वराङ्गश्चन्दनाङ्गदी ।",
      "वीरहा विषमः शून्यो घृताशीरचलश्चलः ॥ ७९॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 80,
    sloka   : [
      "अमानी मानदो मान्यो लोकस्वामी त्रिलोकधृक् ।",
      "सुमेधा मेधजो धन्यः सत्यमेधा धराधरः ॥ ८०॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 81,
    sloka   : [
      "तेजोवृषो द्युतिधरः सर्वशस्त्रभृतां वरः ।",
      "प्रग्रहो निग्रहो व्यग्रो नैकश‍ृङ्गो गदाग्रजः ॥ ८१॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 82,
    sloka   : [
      "चतुर्मूर्तिश्चतुर्बाहुश्चतुर्व्यूहश्चतुर्गतिः ।",
      "चतुरात्मा चतुर्भावश्चतुर्वेदविदेकपात् ॥ ८२॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 83,
    sloka   : [
      "समावर्तोऽनिवृत्तात्मा दुर्जयो दुरतिक्रमः ।",
      "दुर्लभो दुर्गमो दुर्गो दुरावासो दुरारिहा ॥ ८३॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 84,
    sloka   : [
      "शुभाङ्गो लोकसारङ्गः सुतन्तुस्तन्तुवर्धनः ।",
      "इन्द्रकर्मा महाकर्मा कृतकर्मा कृतागमः ॥ ८४॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 85,
    sloka   : [
      "उद्भवः सुन्दरः सुन्दो रत्ननाभः सुलोचनः ।",
      "अर्को वाजसनः श‍ृङ्गी जयन्तः सर्वविज्जयी ॥ ८५॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 86,
    sloka   : [
      "सुवर्णबिन्दुरक्षोभ्यः सर्ववागीश्वरेश्वरः ।",
      "महाह्रदो महागर्तो महाभूतो महानिधिः ॥ ८६॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 87,
    sloka   : [
      "कुमुदः कुन्दरः कुन्दः पर्जन्यः पावनोऽनिलः ।",
      "अमृताशोऽमृतवपुः सर्वज्ञः सर्वतोमुखः ॥ ८७॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 88,
    sloka   : [
      "सुलभः सुव्रतः सिद्धः शत्रुजिच्छत्रुतापनः ।",
      "न्यग्रोधोऽदुम्बरोऽश्वत्थश्चाणूरान्ध्रनिषूदनः ॥ ८८॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 89,
    sloka   : [
      "सहस्रार्चिः सप्तजिह्वः सप्तैधाः सप्तवाहनः ।",
      "अमूर्तिरनघोऽचिन्त्यो भयकृद्भयनाशनः ॥ ८९॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 90,
    sloka   : [
      "अणुर्बृहत्कृशः स्थूलो गुणभृन्निर्गुणो महान् ।",
      "अधृतः स्वधृतः स्वास्यः प्राग्वंशो वंशवर्धनः ॥ ९०॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 91,
    sloka   : [
      "भारभृत् कथितो योगी योगीशः सर्वकामदः ।",
      "आश्रमः श्रमणः क्षामः सुपर्णो वायुवाहनः ॥ ९१॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 92,
    sloka   : [
      "धनुर्धरो धनुर्वेदो दण्डो दमयिता दमः ।",
      "अपराजितः सर्वसहो नियन्ताऽनियमोऽयमः ॥ ९२॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 93,
    sloka   : [
      "सत्त्ववान् सात्त्विकः सत्यः सत्यधर्मपरायणः ।",
      "अभिप्रायः प्रियार्होऽर्हः प्रियकृत् प्रीतिवर्धनः ॥ ९३॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 94,
    sloka   : [
      "विहायसगतिर्ज्योतिः सुरुचिर्हुतभुग्विभुः ।",
      "रविर्विरोचनः सूर्यः सविता रविलोचनः ॥ ९४॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 95,
    sloka   : [
      "अनन्तो हुतभुग्भोक्ता सुखदो नैकजोऽग्रजः ।",
      "अनिर्विण्णः सदामर्षी लोकाधिष्ठानमद्भुतः ॥ ९५॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 96,
    sloka   : [
      "सनात्सनातनतमः कपिलः कपिरव्ययः ।",
      "स्वस्तिदः स्वस्तिकृत्स्वस्ति स्वस्तिभुक्स्वस्तिदक्षिणः ॥ ९६॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 97,
    sloka   : [
      "अरौद्रः कुण्डली चक्री विक्रम्यूर्जितशासनः ।",
      "शब्दातिगः शब्दसहः शिशिरः शर्वरीकरः ॥ ९७॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 98,
    sloka   : [
      "अक्रूरः पेशलो दक्षो दक्षिणः क्षमिणांवरः ।",
      "विद्वत्तमो वीतभयः पुण्यश्रवणकीर्तनः ॥ ९८॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 99,
    sloka   : [
      "उत्तारणो दुष्कृतिहा पुण्यो दुःस्वप्ननाशनः ।",
      "वीरहा रक्षणः सन्तो जीवनः पर्यवस्थितः ॥ ९९॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 100,
    sloka   : [
      "अनन्तरूपोऽनन्तश्रीर्जितमन्युर्भयापहः ।",
      "चतुरश्रो गभीरात्मा विदिशो व्यादिशो दिशः ॥ १००॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 101,
    sloka   : [
      "अनादिर्भूर्भुवो लक्ष्मीः सुवीरो रुचिराङ्गदः ।",
      "जननो जनजन्मादिर्भीमो भीमपराक्रमः ॥ १०१॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 102,
    sloka   : [
      "आधारनिलयोऽधाता पुष्पहासः प्रजागरः ।",
      "ऊर्ध्वगः सत्पथाचारः प्राणदः प्रणवः पणः ॥ १०२॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 103,
    sloka   : [
      "प्रमाणं प्राणनिलयः प्राणभृत्प्राणजीवनः ।",
      "तत्त्वं तत्त्वविदेकात्मा जन्ममृत्युजरातिगः ॥ १०३॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 104,
    sloka   : [
      "भूर्भुवःस्वस्तरुस्तारः सविता प्रपितामहः ।",
      "यज्ञो यज्ञपतिर्यज्वा यज्ञाङ्गो यज्ञवाहनः ॥ १०४॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 105,
    sloka   : [
      "यज्ञभृद् यज्ञकृद् यज्ञी यज्ञभुग् यज्ञसाधनः ।",
      "यज्ञान्तकृद् यज्ञगुह्यमन्नमन्नाद एव च ॥ १०५॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 106,
    sloka   : [
      "आत्मयोनिः स्वयञ्जातो वैखानः सामगायनः ।",
      "देवकीनन्दनः स्रष्टा क्षितीशः पापनाशनः ॥ १०६॥"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 107,
    sloka   : [
      "शङ्खभृन्नन्दकी चक्री शार्ङ्गधन्वा गदाधरः ।",
      "रथाङ्गपाणिरक्षोभ्यः सर्वप्रहरणायुधः ॥ १०७॥",
      "सर्वप्रहरणायुध ॐ नम इति ।"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 4,
    number  : 108,
    sloka   : [
      "वनमाली गदी शार्ङ्गी शङ्खी चक्री च नन्दकी ।",
      "श्रीमान् नारायणो विष्णुर्वासुदेवोऽभिरक्षतु ॥ १०८॥",
      "श्रीवासुदेवोऽभिरक्षतु ॐ नम इति ।"
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
];

export default verses;