const verses = [
  {
    chapter : 1,
    number  : 1,
    sloka   : [
      "शुक्लाम्बरधरं विष्णुं शशिवर्णं चतुर्भुजम् ।",
      "प्रसन्नवदनं ध्यायेत् सर्वविघ्नोपशान्तये ॥ १॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 2,
    sloka   : [
      "यस्य द्विरदवक्त्राद्याः पारिषद्याः परः शतम् ।",
      "विघ्नं निघ्नन्ति सततं विष्वक्सेनं तमाश्रये ॥ २॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 3,
    sloka   : [
      "व्यासं वसिष्ठनप्तारं शक्तेः पौत्रमकल्मषम् ।",
      "पराशरात्मजं वन्दे शुकतातं तपोनिधिम् ॥ ३॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 4,
    sloka   : [
      "व्यासाय विष्णुरूपाय व्यासरूपाय विष्णवे ।",
      "नमो वै ब्रह्मनिधये वासिष्ठाय नमो नमः ॥ ४॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 5,
    sloka   : [
      "अविकाराय शुद्धाय नित्याय परमात्मने ।",
      "सदैकरूपरूपाय विष्णवे सर्वजिष्णवे ॥ ५॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 6,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 7,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 8,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 9,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 10,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 11,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 12,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 13,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 14,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 15,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 16,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 17,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 18,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 19,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 20,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 21,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 22,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 23,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
];

export default verses;