const verses = [
  {
    chapter : 1,
    number  : 1,
    sloka   : [
      "शुक्लाम्बरधरं विष्णुं शशिवर्णं चतुर्भुजम् ।",
      "प्रसन्नवदनं ध्यायेत् सर्वविघ्नोपशान्तये ॥ १॥",
    ],
    sloka_tel : [
      "శుక్లాంబరధరం విష్ణుం శశివర్ణం చతుర్భుజమ్ ।", 
      "ప్రసన్నవదనం ధ్యాయేత్ సర్వవిఘ్నోపశాంతయే ॥",
    ],
    vicheda : [
      "शुक्ल-अम्बर-धरं विष्णुं शशि-वर्णं चतुर्-भुजम् ।",
      "प्रसन्न-वदनं ध्यायेत् सर्व-विघ्न-उपशान्तये ॥ १॥",
    ],
    anvaya  : [
      "- शुक्ल-अम्बर-धरं",
      "- विष्णुं",
      "- शशि-वर्णं",
      "- चतुर्-भुजम्",
      "- प्रसन्न-वदनं",
      "- (सर्व-विघ्न-उपशान्तये)",
      "ध्यायेत्",
    ],
    transl  : [
      "- the one who wears white garments",
      "- the one who is all pervading (Vishnu)",
      "- the one who has a moon-like complexion",
      "- the one who has four arms",
      "- the one with a smiling face",
      "- (for the removal of all obstacles)",
      "One should meditate upon",      
    ],
    essence : [
      "One should meditate upon Lord Ganesha (who wears white garments, has a moon-like complexion, and four arms, with a smiling face) for the removal of all obstacles.",
    ],
    essence_tel: [
      "తెల్లని వస్త్రములు ధరించి, చంద్రకాంతితో ప్రకాశిస్తూ, నాలుగు భుజములు కలిగి, ప్రసన్నవదనముతో ఉన్న ఆ విఘ్నేశ్వరుని అన్ని ఆటంకములు తొలగిపోవుటకై ధ్యానించవలెను.",
    ],
    meanings: [
      "ध्यायेत् = one should meditate",
      "सर्व-विघ्न-उपशान्तये = for the pacification (उपशमनम्) of all obstacles",
    ],
    notes   : [
      "ध्यायेत् = ध्यै — to meditate - विधिलिङ् (Potential Mood) - कर्तरि - प्र.पु. - एक.व. - परस्मै",
      "विधिलिङ् is used with 'should' in slokas to indicate a recommendation or advice.",
      "विधिलिङ् is used with 'may' in general conversation to indicate possibility or permission.",
      "सर्व-विघ्न-उपशान्तये = शान्तिः - चतुर्थी - एक.व.",
    ],
  },
  {
    chapter : 1,
    number  : 2,
    sloka   : [
      "यस्य द्विरदवक्त्राद्याः पारिषद्याः परः शतम् ।",
      "विघ्नं निघ्नन्ति सततं विष्वक्सेनं तमाश्रये ॥ २॥",
    ],
    sloka_tel : [
      "యస్య ద్విరదవక్త్రాద్యాః పారిషద్యాః పరః శతమ్ ।",
      "విఘ్నం నిఘ్నంతి సతతం విష్వక్సేనం తమాశ్రయే ॥ ౨॥"
    ],
    vicheda : [
      "यस्य द्विरद-वक्त्र-आद्याः पारिषद्याः परः-शतम् ।",
      "विघ्नम् निघ्नन्ति सततम् विष्वक्सेनम् तम् आश्रये ॥"
    ],
    anvaya  : [
      "अहम्",
      "- यस्य (द्विरदवक्त्राद्याः परः-शतम्) पारिषद्याः सततं विघ्नं निघ्नन्ति,",
      "- (विष्वक्सेनं) तम्",
      "आश्रये",
    ],
    transl  : [
      "I",
      "- whose attendants (elephant-faced and more than 100 in number) always destroys obstacles",
      "- him (Lord Vishwaksena)",
      "take refuge in",
    ],
    essence : [
      "I take refuge in Lord Vishvaksena, whose attendants (led by those with elephant faces) numbering more than a hundred, constantly destroy all obstacles.",
    ],
    essence_tel: [
      "ఎవరి యొక్క గజముఖము వంటి ముఖము గల సేవకులు వందల సంఖ్యలో ఉండి నిరంతరము విఘ్నములను నశింపజేస్తారో, అట్టి విష్వక్సేనుడిని నేను శరణు వేడుతున్నాను."
    ],
    meanings: [
      "Yasya = Whose / Of whom",
      "Dvirada-vaktra-ādyāḥ = Led by those with the face of an elephant (Gajavaktra)",
      "Pāriṣadyāḥ = Attendants / Members of the assembly / Retainers",
      "Paraḥ-śatam = More than a hundred",
      "Vighnam = Obstacles / Hindrances",
      "Nighnanti = They strike down / They destroy",
      "Satatam = Always / Constantly",
      "Viṣvaksenam = Lord Vishvaksena",
      "Tam = Him (In that person)",
      "Āśraye = I take refuge / I seek shelter"
    ],
    notes   : [
      "In the Vaishnava tradition, Vishvaksena is the commander-in-chief. This verse seeks his protection by acknowledging that even his subordinates are powerful enough to remove hundreds of obstacles.",
      "Grammar: 'Āśraye' is Lat-lakara (Present Tense), Uttama Purusha (1st Person Singular), Atmanepada. It corresponds to 'ఆశ్రయిస్తున్నాను' in Telugu.",
      "The word 'Nighnanti' is Prathama Purusha Bahuvachana (3rd Person Plural), referring to the many attendants acting.",
      "Vicheda Note: Sandhi like 'tam + āśraye' is split into 'tam āśraye' for better clarity in chanting."
    ],
  },
  {
    chapter : 1,
    number  : 3,
    sloka   : [
      "व्यासं वसिष्ठनप्तारं शक्तेः पौत्रमकल्मषम् ।",
      "पराशरात्मजं वन्दे शुकतातं तपोनिधिम् ॥ ३॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 4,
    sloka   : [
      "व्यासाय विष्णुरूपाय व्यासरूपाय विष्णवे ।",
      "नमो वै ब्रह्मनिधये वासिष्ठाय नमो नमः ॥ ४॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 5,
    sloka   : [
      "अविकाराय शुद्धाय नित्याय परमात्मने ।",
      "सदैकरूपरूपाय विष्णवे सर्वजिष्णवे ॥ ५॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 6,
    sloka   : [
      "यस्य स्मरणमात्रेण जन्मसंसारबन्धनात् ।",
      "विमुच्यते नमस्तस्मै विष्णवे प्रभविष्णवे ॥ ६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 6.1,
    sloka   : [
      "(नमः समस्तभूतानामादिभूताय भूभृते ।",
      "अनेकरूपरूपाय विष्णवे प्रभविष्णवे ॥)",
      "ॐ नमो विष्णवे प्रभविष्णवे ॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 7,
    sloka   : [
      "श्रीवैशम्पायन उवाच ---",
      "श्रुत्वा धर्मानशेषेण पावनानि च सर्वशः ।",
      "युधिष्ठिरः शान्तनवं पुनरेवाभ्यभाषत ॥ ७॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 8,
    sloka   : [
      "युधिष्ठिर उवाच ---",
      "किमेकं दैवतं लोके किं वाप्येकं परायणम् ।",
      "स्तुवन्तः कं कमर्चन्तः प्राप्नुयुर्मानवाः शुभम् ॥ ८॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 9,
    sloka   : [
      "को धर्मः सर्वधर्माणां भवतः परमो मतः ।",
      "किं जपन्मुच्यते जन्तुर्जन्मसंसारबन्धनात् ॥ ९॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 10,
    sloka   : [
      "भीष्म उवाच ---",
      "जगत्प्रभुं देवदेवमनन्तं पुरुषोत्तमम् ।",
      "स्तुवन् नामसहस्रेण पुरुषः सततोत्थितः ॥ १०॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 11,
    sloka   : [
      "तमेव चार्चयन्नित्यं  भक्त्या पुरुषमव्ययम् ।",
      "ध्यायन् स्तुवन् नमस्यंश्च यजमानस्तमेव च ॥ ११॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 12,
    sloka   : [
      "अनादिनिधनं विष्णुं सर्वलोकमहेश्वरम् ।",
      "लोकाध्यक्षं स्तुवन्नित्यं सर्वदुःखातिगो भवेत् ॥ १२॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 13,
    sloka   : [
      "ब्रह्मण्यं सर्वधर्मज्ञं लोकानां कीर्तिवर्धनम् ।",
      "लोकनाथं महद्भूतं सर्वभूतभवोद्भवम् ॥ १३॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 14,
    sloka   : [
      "एष मे सर्वधर्माणां धर्मोऽधिकतमो मतः ।",
      "यद्भक्त्या पुण्डरीकाक्षं स्तवैरर्चेन्नरः सदा ॥ १४॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 15,
    sloka   : [
      "परमं यो महत्तेजः परमं यो महत्तपः ।",
      "परमं यो महद्ब्रह्म परमं यः परायणम् ॥ १५॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 16,
    sloka   : [
      "पवित्राणां पवित्रं यो मङ्गलानां च मङ्गलम् ।",
      "दैवतं दैवतानां च भूतानां योऽव्ययः पिता ॥ १६॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 17,
    sloka   : [
      "यतः सर्वाणि भूतानि भवन्त्यादियुगागमे ।",
      "यस्मिंश्च प्रलयं यान्ति पुनरेव युगक्षये ॥ १७॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 18,
    sloka   : [
      "तस्य लोकप्रधानस्य जगन्नाथस्य भूपते ।",
      "विष्णोर्नामसहस्रं मे श‍ृणु पापभयापहम् ॥ १८॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 19,
    sloka   : [
      "यानि नामानि गौणानि विख्यातानि महात्मनः ।",
      "ऋषिभिः परिगीतानि तानि वक्ष्यामि भूतये ॥ १९॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 20,
    sloka   : [
      "ऋषिर्नाम्नां सहस्रस्य वेदव्यासो महामुनिः ।",
      "छन्दोऽनुष्टुप् तथा देवो भगवान् देवकीसुतः ॥ २०॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 21,
    sloka   : [
      "अमृतांशूद्भवो बीजं शक्तिर्देवकीनन्दनः ।",
      "त्रिसामा हृदयं तस्य शान्त्यर्थे विनियोज्यते ॥ २१॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 22,
    sloka   : [
      "विष्णुं जिष्णुं महाविष्णुं प्रभविष्णुं महेश्वरम् ।",
      "अनेकरूपदैत्यान्तं नमामि पुरुषोत्तमम् ॥ २२॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
];

export default verses;