// "॥ अथ वेङ्कटेशप्रपत्ति ॥",
const verses = [
  {
    chapter: 3,
    number: 1,
    sloka: [
      "ईशानां जगतोऽस्य वेङ्कटपतेर्विष्णोः परां प्रेयसीं",
      "तद्वक्षस्स्थलनित्यवासरसिकां तत्क्षान्तिसंवर्धिनीम् ।",
      "पद्मालङ्कृतपाणिपल्लवयुगां पद्मासनस्थां श्रियं",
      "वात्सल्यादिगुणोज्ज्वलां भगवतीं वन्दे जगन्मातरम् ॥ १॥",
    ],
    vicheda: [
      "ईशानां जगतः अस्य वेङ्कटपतेः विष्णोः परां प्रेयसीं",
      "तत्-वक्षःस्थल-नित्य-वास-रसिकाम् तत्-क्षान्ति-संवर्धिनीम् ।",
      "पद्म-अलङ्कृत-पाणि-पल्लव-युगाम् पद्म-आसन-स्थाम् श्रियं",
      "वात्सल्य-आदि-गुण-उज्ज्वलाम् भगवतीं वन्दे जगत्-मातरम् ॥ १॥",
    ],
    anvaya: [
      "अहं",
      "- (अस्य जगतः ईशानां)", 
      "- (वेङ्कटपतेः) विष्णोः परां प्रेयसीं ।",
      "- (तत्-वक्षःस्थल-नित्यवास-रसिकां) ।",
      "- तत्-क्षान्ति-संवर्धिनीम् ।",
      "- पद्म-आलङ्कृत-पाणि-पल्लव-युगां ।",
      "- पद्मासन-स्थाम् ।",
      "- वात्सल्य-आदि-गुण-उज्ज्वलाम् ।",
      "- जगन्मातरम् ।",
      "भगवतीं श्रियं वन्दे ।",
    ],
    transl: [
      "I",
      "- to the master of this universe",
      "- to the supreme beloved of Vishnu (Venkatapathi),",
      "- to the one who takes delight in residing in the heart of Sri Venkateswara,",
      "- to the one who increases his patience,",
      "- to the one whose hands are adorned with lotuses,",
      "- to the one who is seated on lotus throne",
      "- to the one who shines with qualities like motherly affection,",
      "- to the mother of the universe,",
      "- to the Bhagavati Sri Lakshmi,",
      "(I am) offering my obeisances",

      // "I pay my obeisance to Lakshmi the ruler of the universe, who is the most beloved of Lord Vishnu the Lord of Mount Venkata, who rests with supreme delight upon His chest, and increases His forbearance, whose hands tender as sprouts, are decorated with lotus blossoms, whose seat is the lotus (of the mind) who is radiant with perfection of qualities such as tender solicitude etc. and who is the Mother of the Universe.",
      // "I bow down to the divine Goddess Lakshmi, the supreme beloved of Lord Vishnu, the Lord of Venkata hills and ruler of the universe. She eternally resides on His chest and nurtures His patience and forbearance. Her tender hands are adorned with lotuses, and she is seated on a lotus throne. She shines with qualities such as motherly affection and is the universal mother. O Bhagavati, I offer my reverence to you!",
    ],
    essence: [
      "I offer my obiesances to Bhagavati Sri Lakshmi, who is the Lord of this universe, who is the supreme beloved of Lord Venkateswara, who takes delight in residing in his heart, who increases his patience, whose hands are decorated with lotuses, who is seated on lotus throne, who shines with qualities like motherly affection, and the mother of the universe.",
    ],
    meanings: [],
    notes: [
      "अस्य जगतः = of this world",
      "ईशानां = To the Lord/master/ruler(feminine) - द्वितीया.वि. - एक.व.",
      "(वेङ्कटपतेः) विष्णोः = Of Lord Vishnu/Lord Venkateswara",
      "परां प्रेयसीं = To the Supreme Beloved (consort)",
      "तत्-वक्षःस्थल-नित्यवास-रसिकां = to The one who eternally delights in residing on His chest",
      "तत्-क्षान्ति-संवर्धिनीम् = to The one who nurtures His (Vishnu’s) patience and forbearance",
      "पद्म-आलङ्कृत-पाणि-पल्लव-युगाम् = to The one whose tender hands are adorned with lotuses",
      "पद्मासन-स्थाम् = to The one seated on a lotus (Goddess Lakshmi)",
      "श्रियम् = Goddess Lakshmi",
      "वात्सल्य-आदि-गुण-उज्ज्वलाम् = to The one resplendent with qualities like motherly affection",
      "भगवतीम् = to The divine goddess",
      "जगन्मातरम् = to The mother of the universe",
      "(अहं) वन्दे = I bow down to, I worship",
    ],
  },
  {
    chapter: 3,
    number: 2,
    sloka: [
      "श्रीमन् कृपाजलनिधे कृतसर्वलोक",
      "सर्वज्ञ शक्त नतवत्सल सर्वशेषिन् ।",
      "स्वामिन् सुशील सुलभाश्रितपारिजात",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ २॥",
    ],
    vicheda: [
      "श्रीमन् कृपा-जल-निधे कृत-सर्व-लोक",
      "सर्वज्ञ शक्त नत-वत्सल सर्व-शेषिन् ।",
      "स्वामिन् सुशील सुलभ-आश्रित-पारिजात",
      "श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ २॥",
    ],
    anvaya: [
      "हे",
      "- श्रीमन्", 
      "- कृपा-जल-निधे",
      "- कृत-सर्व-लोक",
      "- सर्वज्ञ", 
      "- शक्त", 
      "- नत-वत्सल", 
      "- सर्व-शेषिन्",
      "- स्वामिन्", 
      "- सुशील", 
      "- सुलभ",
      "- आश्रित-पारिजात",
      "(अहं) श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ।",
    ],
    transl: [
      "O Lord! one who is -",
      "- opulent (Lord of prosperity),",
      "- ocean of compassion,",
      "- creator of all worlds,",
      "- omniscient (knower of everything),",
      "- omnipotent (capable of everything),",
      "- compassionate towards the humble,",
      "- the essence of the universe,",
      "- the master,",
      "- good natured,",
      "- easily attainable,",
      "- wish fulfilling tree of the one who take refugee.",
      "I take refuge (surrender) at the feet of Lord Venkateswara.",

      // "I take refuge in the lotus feet of Lord Venkateswara, who is opulent, and ocean of compassion, the Creator of the entire universe, omniscient, omnipotent, affectionate to the humble, the essence of the universe, the Master, amiable and receptive, fulfilling the desires of those who take refuge in him.",
      // "O Lord of prosperity! O ocean of mercy! O creator of all worlds! You are omniscient, omnipotent, and the protector of those who bow before You. You are the ultimate refuge of all. O Master! You are virtuous, easily accessible, and like a wish-fulfilling tree for those who seek shelter in You. O Lord Venkatesha! I completely surrender at Your divine feet.",
    ],
    essence: [
      "O Lord Venkateswara! the one who is opulent, ocean of compassion, creator of all worlds, omniscient, omnipotent, compassionate towards the humble, the essence of the universe, the master, good natured, easily attainable, wish fulfilling tree of the one who take refuge. I take refuge (completely surrender) at your lotus feet.",
    ],
    meanings: [],
    notes: [
      "श्रीमन् = O Lord of great fortune (possessor of Lakshmi)",
      "कृपा-जल-निधे = O the Lord, who is Ocean of compassion",
      "कृतसर्वलोक = Creator of all the worlds",
      "सर्वज्ञ = Omniscient (all-knowing)",
      "शक्त = Omnipotent (all-powerful)",
      "नत-वत्सल = Compassionate to those who bow before You - (नम् - to bow down - 1P - भ्वादिः - क्त)",
      "सर्वशेषिन् = The ultimate refuge and master of all (everything is dependent on You)",
      "स्वामिन् = O Lord!",
      "सुशील = Possessor of great virtues and noble character",
      "सुलभ = Easily accessible (merciful to devotees)",
      "आश्रितपारिजात = The wish-fulfilling tree for those who take refuge in You",
      "श्रीवेङ्कटेश-चरणौ = To the two feet of Lord Venkateswara - द्वितीया.वि. - एक.व.",
      "शरणं = Refuge/Surrender",
      "(अहं) प्रपद्ये = I surrender, I (offer) myself = (पद् - to go/attain - 4A - दिवादिः - कर्तरि लट् - उ.पु. - एक.व.)",
    ],
  },
  {
    chapter: 3,
    number: 3,
    sloka: [
      "आनूपुरार्पितसुजातसुगन्धिपुष्प-",
      "सौरभ्यसौरभकरौ समसन्निवेशौ ।",
      "सौम्यौ सदाऽनुभवनेऽपि नवानुभाव्यौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ३॥",
    ],
    vicheda: [
      "आनूपुर-अर्पित-सुजात-सुगन्धि-पुष्प-",
      "सौरभ्य-सौरभकरौ सम-सन्निवेशौ ।",
      "सौम्यौ सदा अनुभवने अपि नवानुभाव्यौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ३॥",
    ],
    anvaya: [
      "(अहं)",
      "- आनूपुर-अर्पित-सुजात-सुगन्धि-पुष्प-सौरभ्य-सौरभकरौ",
      "- सम-सन्निवेशौ",
      "- सौम्यौ",
      "- सदा अनुभवने अपि नवानुभाव्यौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- at (those feet) that give fragrance to the fragrant flowers offered near the anklets,",
      "- at (those feet) that appear symmetrical,",
      "- at (those feet) that are gentle,",
      "- at (those feet) that give fresh experience even though are experienced constantly,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",

      // "I take refuge in the lotus feet of Lord Venkatesvara, which impart their fragrance to the lovely garlands of scented flowers which hang below his anklets, resting gently, although experienced constantly, the enjoyment is ever fresh.",
      // "I surrender to the divine feet of Lord Venkatesha, which are adorned with beautifully fragrant flowers placed near His anklets. These feet emanate a divine fragrance, are symmetrically positioned, and possess a gentle charm. Even when experienced continuously, they always appear fresh and ever new.",
    ],
    essence: [
      "I take refuge at the lotus feet of Lord Venkateswara, which give fragrance to the fragrant flowers offered near the anklets, that appear symmetrical, that are gentle, that give fresh experience even though are experienced constantly.",
    ],
    meanings: [],
    notes: [
      "आनूपुर = Near the anklets",
      "अर्पित = Offered, placed",
      "सुजात = Beautifully born, well-formed",
      "सुगन्धिपुष्प = Fragrant flowers",
      "सौरभ्य = Fragrance",
      "सौरभकरौ = Those that spread fragrance",
      "समसन्निवेशौ = Symmetrically placed (well-proportioned)",
      "सौम्यौ = Gentle, pleasant",
      "सदा = Always",
      "अनुभवने अपि = Even in experience",
      "नवानुभाव्यौ = Always fresh and ever new in experience",
    ],
  },
  {
    chapter: 3,
    number: 4,
    sloka: [
      "सद्योविकासिसमुदित्वरसान्द्रराग-",
      "सौरभ्यनिर्भरसरोरुहसाम्यवार्ताम् ।",
      "सम्यक्षु साहसपदेषु विलेखयन्तौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ४॥",
    ],
    vicheda: [
      "सद्यः-विकासि-समुदित-वर-सान्द्र-राग-",
      "सौरभ्य-निर्भर-सरोरुह-साम्य-वार्ताम् ।",
      "सम्यक्षु साहस-पदेषु विलेखयन्तौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ४॥",
    ],
    anvaya: [
      "(अहं)",
      "- (सद्यः-विकासि-समुदित-वर-सान्द्र-राग-सौरभ्य-निर्भर-सरोरुह-साम्य-वार्ताम्)",
      "- (सम्यक्षु साहस-पदेषु)", 
      "- विलेखयन्तौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- (of freshly bloomed fragrant deep red lotuses),",
      "- (in the perfect and courageous steps),",
      "- at (those feet) that exceed the beauty,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",
      // "I take refuge in the lotus feet of Lord Venkatesvara, which resemble by their beauty newly blossomed exceedingly fragrant red lotuses. The testimony is self evident.",
      // "I surrender to the divine feet of Lord Venkatesha, which bloom instantly like a freshly opened lotus, enriched with deep red color and overflowing with fragrance. Their beauty reminds one of a lotus. As He moves with bold and confident steps, His divine feet leave marks on the ground, radiating their celestial presence.",
    ],
    essence: [
      "I take refuge at the lotus feet of Lord Venkateswara, which are supremely beautiful beyond comparison to the freshly bloomed fragrant deep red lotuses, in the perfect and courageous steps.",
    ],
    meanings: [
      "सद्यः-विकासि = Instantly blooming",
      "समुदित = Fully manifesting",
      "वर = Supreme, excellent",
      "सान्द्र-राग = Deeply enriched with color (symbolizing divine grace and love)",
      "सौरभ्य-निर्भर = Overflowing with fragrance",
      "सरोरुह-साम्य-वार्ताम् = Reminding one of a lotus (in beauty and fragrance)",
      "सम्यक्-अषु = Very quickly, properly",
      "साहस-पदेषु = In bold or courageous steps",
      "विलेखयन्तौ = Marking or engraving (the ground as they move)",
    ],
    notes: [      
    ],
  },
  {
    chapter: 3,
    number: 5,
    sloka: [
      "रेखामयध्वजसुधाकलशातपत्र",
      "वज्राङ्कुशाम्बुरुहकल्पकशङ्खचक्रैः ।",
      "भव्यैरलङ्कृततलौ परतत्त्वचिन्हैः",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ५॥",
    ],
    vicheda: [
      "रेखामय-ध्वज-सुधा-कलश-आतपत्र-",
      "वज्र-अङ्कुश-अम्बुरुह-कल्पक-शङ्ख-चक्रैः ।",
      "भव्यैः अलङ्कृत-तलौ परतत्त्व-चिन्हैः",
      "श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ ५॥",
    ],
    anvaya: [
      "(अहं)",
      "- - (भव्यैः) (परतत्त्व-चिन्हैः)",
      "- - रेखामय-ध्वज-सुधा-कलश-आतपत्र-वज्र-अङ्कुश-अम्बुरुह-कल्पक-शङ्ख-चक्रैः",
      "- अलङ्कृत-तलौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- - (with the auspicious and divine symbols),",
      "- - (like lines, flag, nectar pot, umbrella, thunderbolt, goad, lotus, celestial wish-fulfilling tree, conch and discus),",
      "- at (those feet) that are decorated,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",
      // "I take refuge in the lotus feet of Lord Venkatesvara, which are most worthy, marked with the divine and auspicious symbols of a flag, pot of ambrosia, umbrella, thunderbolt, elephant goad, conch-shell, and discus.",
      // "I surrender to the divine feet of Lord Venkatesha, whose soles are adorned with auspicious marks representing the Supreme Truth, such as lines, flag, nectar pot, umbrella, thunderbolt, goad, lotus, celestial wish-fulfilling tree, conch, and discus.",
      // "This verse glorifies the sacred feet of Lord Venkatesha, highlighting the divine symbols that adorn them, which signify protection, prosperity, and supreme divinity.",
    ],
    essence: [
      "I take refuge at the lotus feet of Lord Venkateswara, which are decorated with divine and auspicious symbols like: lines, flag, amritha kalasham, umbrella, thunderbolt (vajra), goad (ankusham), lotus, kalpa vriksha, shankam and chakram.",
    ],
    meanings: [
      "भव्यैः = auspicious",
      "परतत्त्व-चिन्हैः = with symbols representing the supreme truth",      
      "रेखामय-ध्वज-सुधा-कलश-आतपत्र-वज्र-अङ्कुश-अम्बुरुह-कल्पक-शङ्ख-चक्रैः = marked with divine symbols such as lines, flag, nectar pot, umbrella, thunderbolt, goad, lotus, celestial wish-fulfilling tree, conch, and discus",
      "अलङ्कृत-तलौ = decorated soles",
      "शरणं प्रपद्ये = I surrender",
      "अङ्कुश = The Sanskrit word अङ्कुश (aṅkuśa) means elephant goad or hook. It is a traditional tool used to control and guide elephants, typically made of metal with a pointed curved end. In a spiritual or symbolic context, अङ्कुश represents control, discipline, and guidance, often signifying the ability to steer one's mind and senses in the right direction. It is commonly associated with Lord Ganesha and other deities, symbolizing mastery over desires and obstacles.",
      "तलौ = The word तलौ (talau) is the dual form of तल (tala), which means sole (bottom part of feet.)"
    ],
    notes: [
      
    ],
  },
  {
    chapter: 3,
    number: 6,
    sloka: [
      "ताम्रोदरद्युतिपराजितपद्मरागौ",
      "बाह्यैर्महोभिरभिभूतमहेन्द्रनीलौ ।",
      "उद्यन्नखांशुभिरुदस्तशशाङ्कभासौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ६॥",
    ],
    vicheda: [
      "ताम्र-उदर-द्युति-पराजित-पद्मरागौ",
      "बाह्यैः महोभिः अभिभूत-महेन्द्रनीलौ ।",
      "उद्यत्-नख-अंशुभिः उदस्त-शशाङ्क-भासौ",
      "श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ ६॥",
    ],
    anvaya: [
      "(अहं)",
      "- ताम्र-उदर-द्युति-पराजित-पद्मरागौ",
      "- बाह्यैः महोभिः अभिभूत-महेन्द्रनीलौ",
      "- उद्यत्-नख-अंशुभिः उदस्त-शशाङ्क-भासौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- at (those feet) that have the luster of a red lotus gem (Padmarāga), surpassing the radiance of copper interiors,",
      "- at (those feet) that by their external brilliance, surpassing the radiance of the great Indra Nīla (blue sapphire),",
      "- at (those feet) that with rising brilliance from the toenails, shining like the raised radiance of the full moon,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",

      // "I take refuge in the lotus feet of Lord Venkatesvara, whose redness surpasses that of a ruby, and whose eternal resplendence exceeds that of the sapphire, the radiance of the nails excels that of the moon.",
      // "I surrender to the divine feet of Lord Venkatesha, which shine with the brilliance of red lotus gems, surpassing even the radiance of glowing copper; whose outer luster eclipses the grandeur of the great blue sapphire (Indranīla); and whose toenails emit a rising brilliance, resembling the radiant glow of the full moon.",
      // "This verse poetically describes the dazzling radiance of Lord Venkatesha's feet, comparing their colors and brilliance to precious gems, celestial lights, and natural elements, emphasizing their divine beauty and auspiciousness.",
    ],
    essence: [
      "I take refuge at the lotus feet of Lord Venkateswara, that have the luster of a red lotus gem (Padmarāga), surpassing the radiance of copper interiors; that by their external brilliance, surpassing the radiance of the great Indra Nīla (blue sapphire); that with rising brilliance from the toenails, shining like the raised radiance of the full moon.",
    ],
    meanings: [
      "ताम्र (tāmra) = Copper",
      "उदर (udara) = Belly, interior, or core",
      "द्युति (dyuti) = Radiance, brilliance, or luster",
      "ताम्र-उदर-द्युति-पराजित-पद्मरागौ = having the luster of a red lotus gem (Padmarāga), surpassing the radiance of copper interiors",
      "बाह्यैः महोभिः = by great external brilliance",
      "अभिभूत = eclipse",
      "अभिभूत-महेन्द्रनीलौ = surpassing the radiance of the great Indra Nīla (blue sapphire)",
      "उद्यत्-नख-अंशुभिः = with rising brilliance from the toenails",
      "उदस्त-शशाङ्क-भासौ = shining like the raised radiance of the full moon",
    ],
    notes: [
      
    ],
  },
  {
    chapter: 3,
    number: 7,
    sloka: [
      "सप्रेमभीति कमलाकरपल्लवाभ्यां",
      "संवाहनेऽपि सपदि क्लममादधानौ ।",
      "कान्ताववाङ्ग्मनसगोचरसौकुमार्यौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ७॥",
    ],
    vicheda: [
      "स-प्रेम-भीति कमलाकर-पल्लवाभ्याम्",
      "संवाहने-अपि सपदि क्लमम् आदधानौ ।",
      "कान्ता-अव-वाङ्मनस-गोचर-सौकुमार्यौ",
      "श्री-वॆङ्कटेश-चरणौ शरणं प्रपद्ये ॥ ७॥",
    ],
    anvaya: [
      "(अहं)",
      "- कमलाकर-पल्लवाभ्याम् स-प्रेम-भीति संवाहने-अपि सपदि क्लमम् आदधानौ",
      "- कान्ता-अव-वाङ्मनस-गोचर-सौकुमार्यौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- at (those feet) that experience fatigue even with the gentle massage by hands of Mother Lakshmi done with love and fear,",
      "- at (those feet) who delicacy is beyond comprehension for even Mother Lakshmi's mind and speech,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",

      // "I take refuge in the lotus feet of Lord Venkatesvara, so tender that they cannot bear even the gentle and careful massaging by the lotus-like hands of Lakshmi. whose charm and delicacy are beyond comprehension and expression.",
      // "I take refuge in the divine feet of Lord Venkatesha, Which, even when gently massaged with lotus-bud-like hands with love and reverence, instantly feel fatigue. These feet possess such extreme delicateness that they are beyond the grasp of speech and mind, even for Goddess Lakshmi herself.",
      // "This verse beautifully describes the supreme delicacy and divine nature of Lord Venkatesha's feet, which are so tender that even the lightest touch from Goddess Lakshmi causes them to feel fatigue. This emphasizes their transcendental nature, which is beyond human perception.",
    ],
    essence: [
      "I take refuge at the lotus feet of Lord Venkateswara, that experience fatigue even with the gentle massage by hands of Mother Lakshmi done with love and fear; whose delicacy is beyond comprehension for even Mother Lakshmi's mind and speech.",
    ],
    meanings: [
      "स-प्रेम-भीति = With both love and reverence (mixed with slight fear)",
      "कमलाकर = A pond of lotuses",
      "पल्लव = Tender sprout, bud, or young leaf.",
      "पल्लवाभ्याम् = With both tender buds (here referring to the lotus buds)",
      "संवाहने-अपि = Even while gently massaging - सम् + वह् + ल्युट् - सप्तमी विभक्ति",
      "सपदि = Instantly - (अव्ययम्) = तत्क्षणम्",
      "क्लमम् = Fatigue, tiredness",
      "आदधानौ = Experiencing, acquiring",
      "कान्तया = By the beloved (Goddess Lakshmi)",
      "अव = NOT ?? (negating)",
      "वाक्-मनस-गोचर = Beyond the reach of words and mind",
      "सौकुमार्यौ = Extreme tenderness and delicateness",
      "श्री-वेङ्कटेश-चरणौ = The sacred feet of Lord Venkatesha",
      "शरणं प्रपद्ये = I take refuge in",
      "In sloka वाङ्ग्मनस, half ga ग् is there, is it correct?",
    ],
    notes: [
    ],
  },
  {
    chapter: 3,
    number: 8,
    sloka: [
      "लक्ष्मीमहीतदनुरूपनिजानुभाव-",
      "नीलादिदिव्यमहिषीकरपल्लवानाम् ।",
      "आरुण्यसङ्क्रमणतः किल सान्द्ररागौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ८॥",
    ],
    vicheda: [
      "लक्ष्मी-महीतद-अनुरूप-निज-अनुभाव-",
      "नीला-आदि-दिव्य-महिषी-कर-पल्लवानाम् ।",
      "आरुण्य-सङ्क्रमणतः किल सान्द्र-रागौ",
      "श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ ८॥",
    ],
    anvaya: [
      "(अहं)",
      "- (लक्ष्मी-महीतद-अनुरूप-निज-अनुभाव-नीला-आदि-दिव्य-महिषी-कर-पल्लवानाम्) (आरुण्य-सङ्क्रमणतः) किल सान्द्र-रागौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- at (those feet) that turned red due to the transfer of redness of the finger tips of his divine consorts like Mother Lakshmi, Mother Bhudevi, Mother Nila Devi and others,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",

      // "I take refuge in the lotus feet of Lord Venkatesvara, whose red hue has been contracted from the reddish hands of Lakshmi, Bhudevi and Niladevi and the other consorts, all of equal dignity and radiance.",
      // "I take refuge in the divine feet of Lord Venkatesha, which have turned deeply red due to the transfer of the reddish hue from the tender fingertips of His divine consorts—Lakshmi, Bhūdevi, Nīlādevi, and others— whose hands are befitting His divine majesty.",
      // "This verse poetically describes how Lord Venkatesha's feet appear reddish due to the gentle touch of His divine consorts, who lovingly serve Him.",
    ],
    essence: [
      "I take refuge at the lotus feet of Lord Venkateswara, that turned red due to the transfer of redness of the finger tips of his divine consorts like Mother Lakshmi, Mother Bhudevi, Mother Nila Devi and others.",
    ],
    meanings: [
      "लक्ष्मी = Goddess Lakshmi",
      "महीतद = (of) Bhūdevi (Earth goddess)",
      "अनुरूप = Suitable, corresponding",
      "निज = Own, inherent",
      "अनुभाव = Majesty, divine power",
      "नीला = Goddess Nīlā (one of the divine consorts of Vishnu)",
      "आदि = And others, etc.",
      "'लक्ष्मी-मही-नीला आदि' refers to His celestial consorts, showing that He is the Supreme Lord, attended by divine queens.",
      "दिव्य = Divine, celestial",
      "महिषी = Queen, consort",
      "कर = Hand",
      "पल्लवानाम् = Of the tender buds (here, referring to the fingertips)",
      "आरुण्य = Reddish hue",
      "सङ्क्रमणतः = Due to the transfer of",
      "किल = Indeed, certainly",
      "सान्द्र = Deep, intense",
      "रागौ = Redness, passion",
      "The word 'सान्द्ररागौ' (intensely red) suggests the supreme beauty and tenderness of the Lord's feet.",
      "श्रीवेङ्कटेश = Lord Venkatesha",
      "चरणौ = The two feet",
      "शरणं प्रपद्ये = I take refuge in"
    ],
    notes: [      
    ],
  },
  {
    chapter: 3,
    number: 9,
    sloka: [
      "नित्यानमद्विधिशिवादिकिरीटकोटि-",
      "प्रत्युप्तदीप्तनवरत्नमहःप्ररोहैः ।",
      "नीराजनाविधिमुदारमुपादधानौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ९॥",
    ],
    vicheda: [
      "नित्य-आनमत्-विधि-शिव-आदि-किरीट-कोटि-",
      "प्रत्युप्त-दीप्त-नवरत्न-महः-प्ररोहैः ।",
      "नीराजन-विधिम्-उदारम्-उपादधानौ",
      "श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ ९॥",
    ],
    anvaya: [
      "(अहं)",
      "- ((यौ) नित्यानमत्-विधि-शिव-आदि-किरीट-कोटि-प्रत्युप्त-दीप्त-नवरत्न-महः-प्ररोहैः)",
      "- नीराजन-विधिम्-उदारम्-उपादधानौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- at (those feet) that appear magnificient in the process of Arati, by the light emanating from countless embedded shining navaratna crowns of Brahma, Lord Shiva, and other gods, as they eternally bow before him,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",

      // "I take refuge in the lotus feet of Lord Venkatesvara, who are constantly receiving the adoration of lights from the crowns of the deities like Brahma, Siva etc as they repeatedly bow down and pay their daily obeisance.",
      // "I take refuge in the divine feet of Lord Venkatesha, which assume the magnificent form of an Aarti (waving of lights) by the radiance emanating from the countless embedded shining Navaratna (nine-gem) crowns of Brahma, Shiva, and other gods, as they bow eternally before Him.",
      // "This verse describes how Brahma, Shiva, and other celestial beings continuously bow before Lord Venkatesha. Their crowns, studded with radiant Navaratna (nine gems), shine brilliantly as they touch the Lord's feet. The collective glow of these crowns appears like a grand Nīrājana (Aarti ceremony), naturally illuminating His divine feet. This showcases Lord Venkatesha's supreme divinity, as even the greatest deities pay homage to Him.",
    ],
    essence: [
      "I take refuge at the lotus feet of Lord Venkateswara, that appear magnificient in the process of Arati, by the light emanating from countless embedded shining navaratna crowns of Brahma, Lord Shiva, and other gods, as they eternally bow before him.",
    ],
    meanings: [
      "नित्य = Always, eternally",
      "आनमत् = Bowing down, reverentially bent",
      "विधि = Brahma (the creator god)",
      "शिव = Shiva (the destroyer god)",
      "आदि = And others",
      "किरीट = Crown",
      "कोटि = Crores, millions",
      "प्रत्युप्त = Embedded, studded",
      "दीप्त = Shining, radiant",
      "नवरत्न = Nine precious gems",
      "महः = Light, radiance",
      "प्ररोहैः = With sprouting beams (of light)",
      "नीराजन = Aarti, waving of lights in worship",
      "विधिम् = Method, process",
      "उदारम् = Magnificent, generous",
      "उपादधानौ = Assuming, displaying",
      "श्रीवेङ्कटेश = Lord Venkatesha",
      "चरणौ = The two feet",
      "शरणं प्रपद्ये = I take refuge in"
    ],
    notes: [
      
    ],
  },
  {
    chapter: 3,
    number: 10,
    sloka: [
      "विष्णोः पदे परम इत्युदितप्रशंसौ",
      "यौ मध्व उत्स इति भोग्यतयाऽप्युपात्तौ ।",
      "भूयस्तथेति तव पाणितलप्रदिष्टौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १०॥",
    ],
    vicheda: [
      "विष्णोः पदे परम इति उदित-प्रशंसौ",
      "यौ मधु-उत्स इति भोग्यतया अपि उपात्तौ ।",
      "भूयः (तथा) इति तव पाणि-तल-प्रदिष्टौ",
      "श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ १०॥",
    ],
    anvaya: [
      "(अहं)",
      "- (यौ) विष्णोः पदे परम इति उदित-प्रशंसौ",
      "- (यौ) मधु-उत्स इति भोग्यतया (अपि) उपात्तौ",
      "- (यौ) भूयः तथा इति तव पाणि-तल-प्रदिष्टौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- at (those feet) (Lord Vishnu's feet) that are glorified as Supreme,",
      "- at (those feet) that are considered spring of nectar, as they are an object of enjoyment to devotees,",
      "- at (those feet) that are indicated by your palm,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",

      // "I take refuge in the lotus feet of Lord Venkatesvara, whose feet are described in the Vedas as a fountain of ambrosia, an object of profound mystical experience expressed in manifold ways, and whose efficacy is demonstrated by the gesture of his hand pointing downwards.",
      // "I take refuge in the divine feet of Lord Venkatesha, which are praised as 'the supreme abode of Vishnu', which are also accepted as 'the source of nectar' due to their blissful nature, and which You Yourself have further indicated by showing them with Your own hands.",
      // "The feet of Vishnu are glorified in the scriptures as the supreme abode (param padam), signifying mokṣa (liberation). They are also called 'madhv-utsa' (a spring of nectar) because they provide divine bliss to devotees. Finally, the verse states that Lord Venkatesha Himself points to His feet with His hands, emphasizing them as the ultimate refuge for all beings. This verse reinforces the path of surrender (śaraṇāgati), which is central to Vaishnavism.",
    ],
    essence: [
      "I take refuge at the lotus feet of Lord Venkateswara, that (Lord Vishnu's feet) are glorified as Supreme, that are considered a spring of nectar as they are an enjoyment to devotees, and also, that are indicated by your own palm.",
    ],
    meanings: [
      "विष्णोः = Of Lord Vishnu",
      "पदे = Feet, position",
      "परम् = Supreme, highest",
      "इति = Thus",
      "उदित = Declared, described",
      "प्रशंसौ = Praised, glorified",
      "यौ = Those two (feet)",
      "मधु = Honey, nectar",
      "उत्स = Source, spring",
      "इति = Thus",
      "भोग्यतया = As an object of enjoyment",
      "अपि = Even",
      "उपात्तौ = Taken, accepted",
      "भूयः = Again, further",
      "तथा = Similarly, in the same way",
      "इति = Thus",
      "तव = Your",
      "पाणि = Hand",
      "तल = Palm",
      "प्रदिष्टौ = Indicated, shown",
      "श्रीवेङ्कटेश = Lord Venkatesha",
      "चरणौ = The two feet",
      "शरणं प्रपद्ये = I take refuge in"
    ],
    notes: [      
    ],
  },
  {
    chapter: 3,
    number: 11,
    sloka: [
      "पार्थाय तत्सदृशसारथिना त्वयैव",
      "यौ दर्शितौ स्वचरणौ शरणं व्रजेति ।",
      "भूयोऽपि मह्यमिह तौ करदर्शितौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ११॥",
    ],
    vicheda: [
      "पार्थाय तत्-सदृश सारथिना त्वया एव",
      "यौ दर्शितौ स्व-चरणौ शरणं व्रज इति ।",
      "भूयः-अपि मह्यम् इह तौ कर-दर्शितौ ते",
      "श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ ११॥",
    ],
    anvaya: [
      "(अहं)",
      "- यौ पार्थाय तत्-सदृश सारथिना त्वया एव 'शरणं व्रज' इति स्व-चरणौ दर्शितौ",
      "- (यौ) इह भूयः अपि मह्यम् ते कर-दर्शितौ, तौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- at (those feet) that (just like) you have shown to Arjuna (Partha) saying 'Surrender unto me',",
      "- at (those feet) that you are now showing to me by indicating with your hand,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",

      // "I take refuge in the lotus feet of Lord Venkatesvara — those feet which were resorted to by Arjuna, when you acted as his charioteer. You pointed to them with your hand as you gave the injunction — 'take refuge in me alone'.",
      // "I take refuge in the divine feet of Lord Venkatesha, which You alone showed to Arjuna, similar to how You revealed Your own feet and instructed him to take refuge, and which You have now shown to me with Your own hands here.",
      // "The verse draws a parallel between the revelation of Lord Krishna's feet to Arjuna on the battlefield of Kurukshetra, as described in the Bhagavad Gita, where Krishna reveals His divine form (Vishwarupa) and instructs Arjuna to take refuge in His feet.",
      // "Lord Venkatesha's feet are now described as being shown by the Lord Himself to the devotee, just as Krishna revealed His feet to Arjuna.",
      // "The verse emphasizes the path of surrender (śaraṇāgati), as the devotee seeks refuge at the feet of the Lord, who personally guides and protects them.",
      // "It highlights the direct and personal relationship between the devotee and the Lord, with the Lord personally showing His feet to grant protection and bliss.",
    ],
    essence: [
      "I take refuge at the lotus feet of Lord Venkateswara, that you have revealed to Arjuna instructing him to take refugee, similarly, now you are showing them to me.",
    ],
    meanings: [
      "पार्थाय = To Arjuna",
      "तत्सदृश = तत्-सदृश = Similar to that (to what was shown in the previous example)",
      "सारथिना = By the charioteer",
      "त्वयैव = त्वया एव = By You alone",
      "यौ = Those two (feet)",
      "दर्शितौ = Shown, revealed",
      "स्व = Own",
      "चरणौ = Feet",
      "शरणं = Refuge",
      "व्रजेति = He takes refuge",
      "भूयः = Again",
      "अपि = Even",
      "मह्यम् = To me",
      "इह = Here",
      "तौ = Those two",
      "करदर्शितौ = Shown by the hand",
      "ते = Your",
    ],
    notes: [      
    ],
  },
  {
    chapter: 3,
    number: 12,
    sloka: [
      "मन्मूर्ध्नि कालियफणे विकटाटवीषु",
      "श्रीवेङ्कटाद्रिशिखरे शिरसि श्रुतीनाम् ।",
      "चित्तेऽप्यनन्यमनसां सममाहितौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १२॥",
    ],
    vicheda: [
      "मन्मूर्ध्नि कालियफणे विकटाटवीषु",
      "श्री-वेङ्कटाद्रि-शिखरे शिरसि श्रुतीनाम् ।",
      "चित्तेऽप्यनन्यमनसां सममाहितौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १२॥",
    ],
    anvaya: [
      "(अहं)",
      "- (मन्मूर्ध्नि, कालियफणे, विकटाटवीषु,श्रीवेङ्कटाद्रिशिखरे, श्रुतीनाम् शिरसि, अनन्यमनसां चित्ते अपि) ",
      "- समम् आहितौ ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- (on my head, on serpent kaliya, in the dense forests, on crest of Venkatachala, on head of Vedas, and also, in the minds of unwavering devotees),",
      "- at (those feet) that are uniformly established,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",

      // "I take refuge in the lotus feet of Lord Venkatesvara, which are equally placed on my head as on the head of the dragon Kaliya, on the crest of Mount Venkata, on the head of the Secret Doctrine of the Upanishads and in the unwavering mind of the yogis.",
      // "I take refuge in the divine feet of Lord Venkatesha, which were placed on my head, which crushed the hood of the serpent Kaliya in the dense forest, which rest on the peak of the Venkata hill and on the heads of the Vedas, and which reside in the hearts of those whose minds are single-minded and completely devoted.",
      // "'मन्मूर्ध्नि कालियफणे विकटाटवीषु' refers to the incident in the Bhagavata Purana, where Lord Krishna placed His feet on the head of the serpent Kaliya, thereby defeating him. This is being used as a metaphor for the divine power of Lord Venkatesha's feet.",
      // "'श्रीवेङ्कटाद्रिशिखरे' refers to the Venkata hill, which is considered the abode of Lord Venkatesha. His feet rest on the peak of this hill, symbolizing His supreme position.",
      // "'शिरसि श्रुतीनाम्' highlights that the feet of Lord Venkatesha are revered by the Vedas themselves. The feet are considered so divine that they are placed above even the sacred texts.",
      // "The verse concludes by emphasizing that those who have single-minded devotion and unwavering focus on Lord Venkatesha's feet, find them as the ultimate refuge."
    ],
    essence: [
      "I take refuge at the lotus feet of Lord Venkateswara, that are uniformly established on my head, on serpent Kaliya, in the dense forests, on the crest of Venkatachala, on the head of Vedas, and also in the minds of unwavering devotees.",
    ],
    meanings: [
      "मन्मूर्ध्नि = On my head",
      "कालियफणे = Of Kaliya's hood (the serpent Kaliya)",
      "विकटाटवीषु = In the terrible, dense forest",
      "श्रीवेङ्कटाद्रिशिखरे = On the peak of the Venkata hill",
      "शिरसि = On the head",
      "श्रुतीनाम् = Of the Vedas (the sacred scriptures)",
      "चित्ते = In the heart/mind",
      "अपि = Even",
      "अनन्य = Without any other (unwavering)",
      "मनसाम् = Of the minds",
      "समम् = equally",
      "आहितौ = firmly established",
      "सममाहितौ = Completely devoted, fully focused",
      "ते = Your",
      "श्रीवेङ्कटेश = Lord Venkatesha",
      "चरणौ = The feet",
      "शरणं प्रपद्ये = I take refuge in"
    ],
    notes: [     
      "समम् = indeclinable adjective here meaning 'equally' or 'uniformly'", 
    ],
  },
  {
    chapter: 3,
    number: 13,
    sloka: [
      "अम्लानहृष्यदवनीतलकीर्णपुष्पौ",
      "श्रीवेङ्कटाद्रिशिखराभरणायमानौ ।",
      "आनन्दिताखिलमनोनयनौ तवैतौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १३॥",
    ],
    vicheda: [
      "अम्लान-हृष्यत् अवनी-तल-कीर्ण-पुष्पौ",
      "श्रीवेङ्कटाद्रि-शिखर-आभरणाय-मानौ ।",
      "आनन्दित-अखिल-मनो-नयनौ तव एतौ",
      "श्रीवेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ १३॥",
    ],
    anvaya: [
      "(अहं)",
      "- (यौ) अम्लान-हृष्यत् अवनी-तल-कीर्ण-पुष्पौ ",
      "- (यौ) श्रीवेङ्कटाद्रि-शिखर-आभरणाय-मानौ ",
      "- (यौ) आनन्दित-अखिल-मनो-नयनौ",
      "- तव एतौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- at (those feet) that appear like unfading flowers spread on the surface of the earth giving joy,",
      "- at (those feet) that are considered an ornament to the peak of Venkatadri mountain,",
      "- at (those feet) that delight minds and eyes of all devotees,",
      "- at your feet",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",

      // "I take refuge in the lotus feet of Lord Venkatesvara, which appear as unfading flowers, spread over the earth and the crest of Mount Venkata, an ornament of great beauty in the mind and vision of everyone.",
      // "I take refuge in the divine feet of Lord Venkatesha, which are like ever-fresh flowers, thrilling the earth as they are worshipped with scattered blossoms, which serve as an ornament to the peak of the Venkata mountain, and which delight the minds and eyes of all beings.",
      // "'अम्लान-हृष्यद-अवनी-तल-कीर्ण-पुष्पौ' compares the Lord's feet to flowers that remain ever fresh, as they are constantly worshipped by devotees, covering the earth with joy and divine beauty. 'श्रीवेङ्कटाद्रि-शिखर-आभरणाय-मानौ' highlights that Lord Venkatesha's feet are the greatest ornament of the Venkata mountain, making it a sacred pilgrimage site. 'आनन्दित-अखिल-मनो-नयनौ' means that His feet bring immense joy to the minds and eyes of all devotees, who experience bliss upon seeing them.",
    ],
    essence: [
       "I take refuge at your lotus feet, O Lord Venkateswara!, that appear like unfading flowers spread on the surface of the earth giving joy, that are considered an ornament to the peak of Venkatadri mountain, that delight minds and eyes of all devotees.",
    ],
    meanings: [
      "अम्लान = Unfading, ever-fresh",
      "हृष्यत् = Thrilling with joy, delighted",
      "अवनी = Earth",
      "तल = Surface, ground",
      "कीर्ण = Scattered, spread",
      "पुष्पौ = Flowers (two feet described as flowers)",
      "श्रीवेङ्कटाद्रि = Venkata mountain",
      "शिखर = Peak",
      "आभरणाय = As an ornament, decoration",
      "मानौ = Being considered, appearing",
      "आनन्दित = Delighting",
      "अखिल = All, entire",
      "मनो = Mind",
      "नयनौ = Eyes",
      "तव = Your",
      "एतौ = These two",
      "श्रीवेङ्कटेश = Lord Venkatesha",
      "चरणौ = The two feet",
      "शरणं प्रपद्ये = I take refuge in"
    ],
    notes: [    
      "हृष्यत् becomes हृष्यद् due to sandhi",  
    ],
  },
  {
    chapter: 3,
    number: 14,
    sloka: [
      "प्रायः प्रपन्नजनताप्रथमावगाह्यौ",
      "मातुस्स्तनाविव शिशोरमृतायमानौ ।",
      "प्राप्तौ परस्परतुलामतुलान्तरौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १४॥",
    ],
    vicheda: [
      "प्रायः प्रपन्न-जनता-प्रथम-आवगाह्यौ",
      "मातुः-स्तनौ इव शिशोः अमृताय-मानौ ।",
      "प्राप्तौ परस्पर-तुलाम अतुल-अन्तरौ ते",
      "श्रीवेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ १४॥",
    ],
    anvaya: [
      "(अहं)",
      "- (यौ) प्रायः प्रपन्न-जनता-प्रथम-आवगाह्यौ ",
      "- (यौ) मातुः-स्तनौ इव शिशोः अमृताय-मानौ ",
      "- (यौ) ते परस्पर-तुलाम प्राप्तौ, अतुल-अन्तरौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- at (those feet) that are primary refuge for those surrendered devotees,",
      "- at (those feet) that appear like nectar to devotees for spiritual nourishment, as if mother's breast to an infant for nourishment,",
      "- at (those feet) that appear equal to eyes, yet incomparable in their spiritual significance,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",

      // "I take refuge in the lotus feet of Lord Venkatesvara, whose attraction to those who surrender (prapannas) is like the breast of a mother for a suckling infant, spouting the incomparable spiritual ambrosia whereby they are nourished.",
      // "I take refuge in the divine feet of Lord Venkatesha, which are the foremost refuge for those who surrender, which are like a mother's breasts to an infant, nourishing them with nectar-like immortality, which, though appearing equal to each other, are incomparable in their greatness.",
      // "'प्रपन्नजनता प्रथमावगाह्यौ' → The Lord's feet are the first and foremost refuge for surrendered devotees, meaning they are the ultimate source of protection and solace. 'मातुः स्तनाविव शिशोः अमृताय मानौ' → The Lord's feet are compared to a mother's nourishing breasts, which provide nectar-like sustenance to an infant. Just as a baby instinctively seeks its mother for nourishment and comfort, devotees instinctively seek the Lord's feet for spiritual nourishment and liberation. 'प्राप्तौ परस्पर तुलाम अतुलान्तरौ' → The two feet appear equal in stature, yet they are incomparable in their spiritual significance, meaning that each of them holds infinite divine greatness beyond human understanding."
    ],
    essence: [
      "I take refuge at your lotus feet, O Lord Venkateswara!, that are primary refuge for those surrendered devotees; that appear like nectar to devotees for spiritual nourishment, as if mother's breast to an infant for nourishment; that appear equal to eyes, yet incomparable in their spiritual significance.",
    ],
    meanings: [
      "प्रायः = Generally, usually",
      "प्रपन्न = Surrendered",
      "जनता = People, devotees",
      "प्रथम = First, foremost",
      "आवगाह्यौ = To be entered into, plunged into",
      "मातुः = Of the mother",
      "स्तनौ = The two breasts",
      "इव = Like, similar to",
      "शिशोः = Of an infant",
      "अमृताय = As nectar, for immortality",
      "मानौ = Appearing, serving as",
      "प्राप्तौ = Having attained",
      "परस्पर = Each other, mutually",
      "तुलाम = Equality, balance",
      "अतुल = Incomparable",
      "अन्तरौ = Difference, distinction",
      "ते = Your",
      "श्रीवेङ्कटेश = Lord Venkatesha",
      "चरणौ = The two feet",
      "शरणं प्रपद्ये = I take refuge in"
    ],
    notes: [      
    ],
  },
  {
    chapter: 3,
    number: 15,
    sloka: [
      "सत्त्वोत्तरैस्सततसेव्यपदाम्बुजेन",
      "संसारतारकदयार्द्र दृगञ्चलेन ।",
      "सौम्योपयन्तृमुनिना मम दर्शितौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १५॥",
    ],
    vicheda: [
      "सत्त्वोत्तरैः सतत-सेव्य-पदाम्बुजेन",
      "संसार-तारक-दयार्द्र-दृग-अञ्चलेन ।",
      "सौम्य-उपयन्तृ-मुनिना मम दर्शितौ ते",
      "श्रीवेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ १५॥",
    ],
    anvaya: [
      "(अहं)",
      "- (सत्त्वोत्तरैः)",
      "- (सतत-सेव्य-पदाम्बुजेन) ",
      "- (संसार-तारक-दयार्द्र-दृग-अञ्चलेन)",
      "- (सौम्य-उपयन्तृ-मुनिना)",
      "- (यौ) मम दर्शितौ ते (चरणौ)",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "(I)",
      "- (by the virtuous beings),",
      "- (by those whose serve you constantly),",
      "- (by the divine glance that helps cross over the worldly existence),",
      "- (by the sage/spritual master),",
      "- at (your feet) that were revealed to me,",
      "- at the lotus feet of Lord Venkateswara,",
      "take refuge (completely surrender)",

      // "I take refuge in the lotus feet of Lord Venkatesvara, adored by the pious and virtuous, and which are a boat for crossing over this world of mundane existence: they were revealed to me by the gentle sage Manavalamamuni whose eyes were moist with compassion.",
      // "I take refuge in the divine feet of Lord Venkatesha, which are constantly worshipped by highly virtuous beings, which, with their compassionate glance, uplift devotees from the bondage of the material world, and which were revealed to me by the gentle and guiding sage.",
      // "'सत्त्वोत्तरैः सततसेव्यपदाम्बुजेन' → The Lord's lotus feet are constantly worshipped by the most virtuous and pure-hearted beings. This highlights the supreme sanctity of His feet. 'संसारतारकदयार्द्र दृगञ्चलेन' → The Lord's compassionate glance helps devotees cross the ocean of worldly existence (samsāra), meaning that He alone can liberate them from suffering. 'सौम्योपयन्तृमुनिना मम दर्शितौ' → The gentle sage (possibly referring to an acharya or spiritual teacher) revealed these divine feet to the devotee, indicating that spiritual guidance is necessary to perceive the Lord's grace.",
    ],
    essence: [
      "I take refuge at your lotus feet, O Lord Venkateswara!, that are revealed to me by the kind sage, who is virtuous, always worshipping you, and whose glance helps cross the worldly existence.",
    ],
    meanings: [
      "सत्त्वोत्तरैः = By those of superior purity (highly virtuous beings)",
      "सतत = Constantly",
      "सेव्य = To be served, worshipped",
      "पदाम्बुजेन = By the lotus feet",
      "संसार = The cycle of birth and death",
      "तारक = The one who helps in crossing over, the savior",
      "दयार्द्र = Filled with compassion",
      "दृग = Eyes, vision",
      "अञ्चलेन = By the glance",
      "सौम्य = Gentle, kind",
      "उपयन्तृ = Approaching, leading towards (guiding)",
      "मुनिना = By the sage",
      "मम = To me",
      "दर्शितौ = Shown, revealed",
      "ते = Your",
      "श्रीवेङ्कटेश = Lord Venkatesha",
      "चरणौ = The two feet",
      "शरणं प्रपद्ये = I take refuge in"
    ],
    notes: [      
    ],
  },
  {
    chapter: 3,
    number: 16,
    sloka: [
      "श्रीश श्रिया घटिकया त्वदुपायभावे",
      "प्राप्ये त्वयि स्वयमुपेयतया स्फुरन्त्या ।",
      "नित्याश्रिताय निरवद्यगुणाय तुभ्यं",
      "स्यां किङ्करो वृषगिरीश न जातु मह्यम् ॥ १६॥",
    ],
    vicheda: [
      "श्रीश श्रिया घटिकया त्वत्-उपाय-भावे",
      "प्राप्ये त्वयि स्वयम्-उपेयतया स्फुरन्त्या ।",
      "नित्याश्रिताय निरवद्य-गुणाय तुभ्यं",
      "स्याम् किङ्करः वृषगिरीश न जातु मह्यम् ॥ १६॥",
    ],
    anvaya: [
      "हे वृषगिरीश!",
      "हे श्रीश!",
      "त्वत्-उपाय-भावे (घटिकया) श्रिया प्राप्ये, त्वयि स्वयम्-उपेयतया स्फुरन्त्या,",
      "(नित्याश्रिताय) (निरवद्य-गुणाय) (तुभ्यं) किङ्करः स्याम्",
      "न जातु मह्यम्",
    ],
    transl: [
      "O Lord of Vṛṣagiri (Tirumala)!",
      "O Lord of Śrī (Vishnu, Venkatesha)!",
      "- TODO",
      "May I become humble servant to the you, O Lord!, the One who is eternally sought refuge and has flawless qualities, ",
      "Never let there be (any sense of independence) for me!",

      "Since Śrī (Lakṣmī) acts as a mediator (means) to attain You, and at the same time, She Herself manifests as the ultimate goal, O eternally sought refuge, O One with flawless qualities, May I always remain Your humble servant! Never let there be (any sense of independence) for me!",

      // "O Lord of Opulence, you yourself are the means to final beatitude, after reaching you, mother Lakshmi herself became the Mediatrix overflowing with compassion and solicitude, I have dedicated myself to your service for no reward whatsoever, but only to please you.",
      // "O Lord of Vṛṣagiri (Tirumala)! Since Śrī (Lakṣmī) acts as a mediator (means) to attain You, and at the same time, She Herself manifests as the ultimate goal, O eternally sought refuge, O One with flawless qualities, May I always remain Your humble servant! Never let there be (any sense of independence) for me!",
      // "'श्रिया घटिकया त्वदुपायभावे' → Śrī Lakṣmī acts as the means (upāya) to attain the Lord, meaning She intercedes for devotees and ensures their salvation. 'प्राप्ये त्वयि स्वयमुपेयतया स्फुरन्त्या' → The Lord is the ultimate goal (upeya), but Lakṣmī Herself is also the final attainment, meaning She represents divine bliss and eternal service to the Lord. 'नित्याश्रिताय निरवद्यगुणाय' → The Lord is eternally sought as refuge and possesses flawless divine qualities (compassion, justice, love). 'स्यां किङ्करो' → The devotee prays: 'May I always remain Your humble servant.' This is a declaration of complete surrender and servitude to the Lord. 'न जातु मह्यम्' → 'Never let there be any sense of independence for me.' The devotee rejects all notions of self-dependence and desires only servitude to God.",
      // "This verse beautifully encapsulates the essence of Śaraṇāgati (total surrender), acknowledging the grace of Lakṣmī as both a guide and the ultimate blissful attainment.",
    ],
    essence: [
      "O Lord of Tirupati, the consort of Śrī! May I become a servant for You—who are possessed of flawless qualities and eternally depended upon—and not for my own sake. This is because You are the ultimate goal (Upeya) who manifests spontaneously, while the Goddess Śrī serves as the intermediary (Ghaṭikā) and means (Upāya) by which one reaches You.",
    ],
    meanings: [
      "श्रीश = O Lord of Śrī (Vishnu, Venkatesha)",
      "श्रिया = By Śrī (Lakṣmī)",
      "घटिकया = By acting as a link (mediator, means)",
      "त्वत्-उपाय-भावे = In being the means to attain You",
      "प्राप्ये = As the attainable goal",
      "त्वयि = In You",
      "स्वयम्-उपेयतया = By being the ultimate end (goal) Herself",
      "स्फुरन्त्या = Manifesting, shining forth",
      "नित्याश्रिताय = To the eternally dependent one (ever sought refuge in)",
      "निरवद्य-गुणाय = To the One with flawless qualities",
      "तुभ्यं = To You",
      "स्याम् = May I become",
      "किङ्करः = A humble servant",
      "वृषगिरीश = O Lord of Vṛṣagiri (Tirumala)",
      "न = Never",
      "जातु = At any time",
      "मह्यम् = To me"
    ],
    notes: [      
      // It seems this is avyaya, not a verb, "प्राप्ये = प्रा - to be content - णिजन्ते - भावकर्मणोः लट्लकारः (आत्मनेपदम्) - उ.पु. एक.व.",
      "स्याम् = optative form of 'अस्मि' (to be), meaning 'may I become' - कर्तरि विधिलिङ्लकारः - अस् root - उ.पु. एक.व.",
    ],
  },
];

export default verses;
// "॥ इति वेङ्कटेशप्रपत्ति ॥",
