const verses = [
  {
    chapter: 2,
    number: 1,
    sloka: [
      "कमलाकुचचूचुककुङ्कुमतो",
      "नियतारुणितातुलनीलतनो ।",
      "कमलायतलोचन लोकपते",
      "विजयी भव वेङ्कटशैलपते ॥ १॥",
    ],
    sloka_tel: [
      "కమలాకుచచూచుకకుంకుమతో",
      "నియతారుణితాతులనీలతనో",
      "కమలాయతలోచన లోకపతే",
      "విజయీభవ వేంకటశైలపతే || ౧ ||"
    ],
    vicheda: [
      "कमला-कुच-चूचुक-कुङ्कुम-तः",
      "नियत-आरुणित-अतुल-नील-तनो ।",
      "कमला-आयत-लोचन लोक-पते",
      "विजयी भव वेङ्कट-शैल-पते ॥ १॥",
    ],
    anvaya: [
      "हे",
      "- कमला-कुच-चूचुक-कुङ्कुम-तः नियत-आरुणित-अतुल-नील-तनो !",
      "- कमला-आयत-लोचन !",
      "- लोक-पते !",
      "- वेङ्कट-शैल-पते !",
      "विजयी भव ।",
    ],
    prose: [
      "O Lord of Venkata Hill! O Lord of the worlds!",
      "O One with lotus-like eyes!",
      "Your incomparable dark-blue body is always reddened by the saffron (kumkuma) from the Vakshasthala of Mother Lakshmi.",
      "May You be ever victorious!",
    ],
    transl: [
      "O Lord of Venkatachala! O Lord! the one whose blue-complexioned body is reddended due to kumkuma from the vakshasthala of Mother Lakshmi, who has lotus-like eyes, who is the lord of the worlds. May you be ever victorious.",
    ],
    transl_tel: [
      "శ్రీ వేంకటాచలపతీ! ఓ ప్రభూ! నీలమేఘ శ్యామల వర్ణము కలిగిన నీ దివ్య మంగళ విగ్రహము, అలమేలుమంగ (లక్ష్మీదేవి) వక్షస్థలముపై ఉన్న కుంకుమ తాకడం వల్ల ఎర్రని కాంతితో ప్రకాశిస్తోంది. పద్మముల వంటి కన్నులు కలవాడా, లోకములకు అధిపతివైనవాడా! నీకు ఎల్లప్పుడూ జయము కలుగుగాక.",
    ],
    essence: [],
    meanings: [],
    grammar: [],
    notes: [
      "कमला = Mother Lakshmi",
      "चूचुक = स्तनाग्रः",
      "कुङ्कुमतः = कुङ्कुमम् - पञ्चमी.वि. - एक.व.",
      "नियत = controlled - ??",
      "अरुणित = Reddened",
      "नील = blue-colored (of Lord Venkateswara)",
      "तनो = तनुः (तनु - पुं - body) - सं.प्र - एक.व.",
      "कमला = Lotus",
      "आयत-लोचन = One, with large eyes (like Lotus)",
      "विजयी = विजयी (विजयिन् - पुं - victorious/triumphant)",
      "भव = भू(1P - भ्वादिः - to be/to exist) - कर्तरि लोट् - म.पु. - एक.व. = may you become",
    ],
  },
  {
    chapter: 2,
    number: 2,
    sloka: [
      "सचतुर्मुखषण्मुखपञ्चमुख-",
      "प्रमुखाखिलदैवतमौलिमणे ।",
      "शरणागतवत्सल सारनिधे",
      "परिपालय मां वृषशैलपते ॥ २॥",
    ],
    sloka_tel: [
      "సచతుర్ముఖషణ్ముఖపంచముఖ",
      "ప్రముఖాఖిలదైవతమౌళిమణే",
      "శరణాగతవత్సల సారనిధే",
      "పరిపాలయ మాం వృషశైలపతే || ౨ ||"
    ],
    vicheda: [
      "स-चतुर्मुख-षण्मुख-पञ्चमुख-",
      "प्रमुख-अखिल-दैवत-मौलि-मणे ।",
      "शरण-आगत-वत्सल सार-निधे",
      "परिपालय मां वृषशैलपते ॥",
    ],
    anvaya: [
      "हे",
      "- स-चतुर्मुख-षण्मुख-पञ्चमुख-प्रमुख-अखिल-दैवत-मौलि-मणे !",
      "- शरण-आगत-वत्सल !",
      "- सार-निधे !",
      "- वृष-शैल-पते !",
      "मां परिपालय ।",
    ],
    prose: [
      "O Lord!",
      "- who is crest jewel among the best of all devatas including Brahma, Subrahmanya, Lord Siva,",
      "- who is so compassionate to the refugees,",
      "- who is the treasure of all the essence",
      "O Lord of Vrisha shaila!",
      "Please protect me.",

      // "O Crest jewel of all deities, including Brahma, Kartikeya, and Siva; O lord who is full of solicitude for those who take refuge in you, Repository of all energy, O Lord of Vrisha mountain, please protect me.",
      // "Including the four-faced Brahma, six-faced Kumaraswamy (Subrahmanya swami), and five-faced Hanuman, you are the greatest crown jewel among all angels. You are the abode of kindness to those who submit themselves at your feet. O Lord of Vrisha hill, save me.",
      // "Please protect me oh., Lord of Vrusha mountain, Who is the crown jewel among all the gods, With four faces, six faces and five faces, And who is the ultimate treasure who loves, Those who come and surrender to him,",
    ],
    transl: [
      "O Lord of Vrusha shaila (Venkateswara), O Lord, one who is a crest jewel among the best of all devatas (including Brahma, Subrahmanya, Lord Siva), who is so compassionate to the refugees, who is a treasure of all the essence. Please protect me.",
    ],
    transl_tel: [
      "వృషాచలపతివైన ఓ వేంకటేశ్వరా! బ్రహ్మ, సుబ్రహ్మణ్యుడు మరియు పరమశివుడు వంటి గొప్ప దేవతలందరిలో మణికిరీటం వంటి శ్రేష్ఠుడవైనవాడా! నిన్ను శరణువేడిన వారిపై అపారమైన దయను కురిపించేవాడా, సకల సద్గుణ సారములకు నిలయమైనవాడా! నన్ను రక్షించుము.",
    ],
    essence: [],
    meanings: [],
    grammar: [],
    notes: [
      "स = सह",
      "चतुर्मुख = Brahma Deva",
      "षण्मुख = Subrahmanya Deva",
      "पञ्चमुख = Siva",
      "प्रमुख = श्रेष्ठम् (Best/Excellent)",
      "अखिल = समग्रम् = Whole, entire, complete",
      "दैवत = the whole class of gods",
      "मौलि = किरीटम् /head/foremost/best/crown of the head",
      "मणे = मणिः - gem/crest jewel",
      "वत्सल = Child-loving, affectionate towards children or offspring",
      "सार = Prowess, heroism, courage",
      "निधे = निधिः = reservoir, treasury",
    ],
  },
  {
    chapter: 2,
    number: 3,
    sloka: [
      "अतिवेलतया तव दुर्विषहैः",
      "अनुवेलकृतैरपराधशतैः ।",
      "भरितं त्वरितं वृषशैलपते",
      "परया कृपया परिपाहि हरे ॥ ३॥",
    ],
    sloka_tel: [
      "అతివేలతయా తవ దుర్విషహై-",
      "-రనువేలకృతైరపరాధశతైః |",
      "భరితం త్వరితం వృషశైలపతే",
      "పరయా కృపయా పరిపాహి హరే || ౩ ||"
    ],
    vicheda: [
      "अतिवेलतया तव दुर्विषहैः",
      "अनुवेलकृतैः-अपराधशतैः ।",
      "भरितं त्वरितं वृष-शैल-पते",
      "परया कृपया परि-पाहि हरे ॥",
    ],
    anvaya: [
      "हे (वृष-शैल-पते) हरे !",
      "- (अतिवेलतया) (दुर्विषहैः) (अनुवेलकृतैः) अपराधशतैः",
      "- भरितं (मां) ",
      "- (तव परया कृपया) त्वरितं परि-पाहि ।",
    ],
    prose: [
      "O Lord of Vrisha shaila! O Hari!",
      "- by the hundreds of unbearable offenses committed consistently again and again,",
      "- filled with (me)",
      "- with your utmost compassion, quickly please protect (me)",

      // "O Hari! Lord of Vrisha mountain, exceeding all limits, I have continuously committed hundreds of offenses, I am overcome by them! Seeking you shelter I implore you to have mercy on me and absolve me.",
      // "Extremely trembling on being committed various sins and hundreds of wrong deeds, I came running speedily to submit myself at your feet. O Lord of Vrisha hill, shower mercy on me.",
      // "Greatly trembling for having committed various sins, And also trembling for having done hundreds of wrongs, I have rushed speedily for surrendering to you, Lord of Vrusha, And so Oh, Hari, please shower on me your eternal mercy,",
    ],
    transl: [
      "O Lord Venkateswara! O Hari! With your utmost compassion, please quickly protect me, who is filled with hundreds of unbearable offenses committed consistently again and again.",
    ],
    transl_tel: [
      "ఓ వేంకటేశ్వరా! హరీ! పదే పదే, నిరంతరము నేను చేస్తున్న భరించలేని వందలాది అపరాధములతో నిండిన నన్ను, నీ అపారమైన దయతో దయచేసి త్వరగా రక్షించుము.",
    ],
    essence: [],
    meanings: [],
    grammar: [],
    notes: [
      "अति-वेलतया = वेल (time) - अति-वेल (excessive) - तस्य भावः(अतिवेलता) - तृतीया.वि. - एक.व. = due to constant/excessive occurence",
      "दुर्विषहैः = दुर् (difficult) - विषहैः (to bear/endure) = unbearable",
      "अनु-वेल-कृतैः = अनु-वेल (at every moment/repeatedly) = done/committed repeatedly",
      "अपराधशतैः = by hundreds of sins(offenses)",
      "भरितं = भरित = filled with/burdended",
      "त्वरितं = Quickly",
      "परया कृपया = with supreme/highest compassion",
      "परि = completely/all around",
      "पाहि = Protect",
      "परि-पाहि = protect completely/save entirely",
      "SHOULD तव be attached to परया कृपया ?? TO GET PROPER MEANING",
    ],
  },
  {
    chapter: 2,
    number: 4,
    sloka: [
      "अधिवेङ्कटशैलमुदारमते-",
      "र्जनताभिमताधिकदानरतात् ।",
      "परदेवतया गदितान्निगमैः",
      "कमलादयितान्न परं कलये ॥ ४॥",
    ],
    sloka_tel: [
      "అధివేంకటశైలముదారమతే-",
      "-ర్జనతాభిమతాధికదానరతాత్ |",
      "పరదేవతయా గదితాన్నిగమైః",
      "కమలాదయితాన్న పరం కలయే || ౪ ||"
    ],
    vicheda: [
      "अधि-वेङ्कट-शैलम्-उदार-मतेः-",
      "-जनता-अभिमत-अधिक-दान-रतात् ।",
      "पर-देवतया गदितात् निगमैः",
      "कमला-दयितात् न परं कलये ॥ ४॥",
    ],
    anvaya: [
      "(अहं)",
      "- अधि-वेङ्कट-शैलम्-उदार-मतेः",
      "- जनता-अभिमत-अधिक-दान-रतात्",
      "- पर-देवतया निगमैः गदितात्",
      "- कमला-दयितात्",
      "परं न कलये ।",
    ],
    prose: [
      "I do not consider anyone Supreme other than the one",
      "- who resides up on Venkatachala and has a noble/generous nature",
      "- who bestows to devotees more than what they asked for",
      "- who is proclaimed as Supreme by Vedas and other Devatas",
      "- who is the Husband of Mother Lakshmi",

      // "I know no other being, except the Lord of Lakshmi, who is described by the Vedas as the best of all gods, who can exceed you in broad-­‐mindedness and generosity? You give more than anyone can every ask for. ",
      // "O bounteous Lord of Venkata hill, who gives away always more than what your devotees desire, all the other angels (gods) are also saluting to you, and none is equal to you. ",
      // "There is none greater to you, Oh Lord of Lakshmi, Who is merciful by nature residing on Venkata mountain, Who blesses his devotees with much more than they desire, And who is saluted by other gods and books that show the way.",
    ],
    transl: [
      "I do not consider anyone Supreme other than Lord Venkateswara who resides on Venkatachala, who has a generous nature, who blesses devotees with more than what they wish for, who is proclaimed as the Supreme Lord by Vedas and by Devatas, and who is the husband of Mother Lakshmi.",
    ],
    transl_tel: [
      "వేంకటాచలంపై నివసించేవాడు, అత్యంత ఉదార స్వభావం కలవాడు, భక్తులు కోరుకున్న దానికంటే ఎక్కువే అనుగ్రహించేవాడు, వేదములలో మరియు దేవతలచే సర్వోన్నత దైవముగా కొనియాడబడేవాడు మరియు లక్ష్మీదేవి నాథుడైన వేంకటేశ్వరుడు తప్ప వేరే ఏ దైవమును నేను సర్వోన్నతుడిగా భావించను.",
    ],
    essence: [],
    meanings: [],
    grammar: [],
    notes: [
      "अधि-वेङ्कट-शैलम्-उदार-मतेः = पञ्चमी.वि. = from the one who resides on Venkata Chala and Generous",
      "?? शैलम्-उदार (or) शैल-मुदार",
      "जनत-अभिमत-अधिक-दान-रतात् = पञ्चमी.वि. = from the one who bestows more than what the devotees desire",
      "परदेवतया = पर+देवता (other gods) = by other gods(Devatas)",
      "निगमैः = निगम (Vedas) = by Vedas",
      "गदितात् = गदित (Spoken/Said - गद्-क्त) - (गद् - 1P - to tell) = पञ्चमी.वि.",
      "कलये = कल (10U - to go/count/enumerate) - कर्तरि लट् - आत्मने - उ.पु. - एक.व. = I consider",
    ],
  },
  {
    chapter: 2,
    number: 5,
    sloka: [
      "कलवेणुरवावशगोपवधू-",
      "शतकोटिवृतात्स्मरकोटिसमात् ।",
      "प्रतिवल्लविकाभिमतात्सुखदात्",
      "वसुदेवसुतान्न परं कलये ॥ ५॥",
    ],
    sloka_tel: [
      "కలవేణురవావశగోపవధూ-",
      "-శతకోటివృతాత్స్మరకోటిసమాత్ |",
      "ప్రతివల్లవికాభిమతాత్సుఖదాత్",
      "వసుదేవసుతాన్న పరం కలయే || ౫ ||",
    ],
    vicheda: [
      "कल-वेणु-रव-अवश-गोप-वधू-",
      "शत-कोटि-वृतात् स्मर-कोटि-समात् ।",
      "प्रतिवल्लविका-अभिमतात् सुखदात्",
      "वसुदेवसुतात् न परं कलये ॥ ५॥",
    ],
    anvaya: [
      "(अहं)",
      "- कल-वेणु-रव-अवश-गोप-वधू-शत-कोटि-वृतात्",
      "- स्मर-कोटि-समात्",
      "- प्रतिवल्लविका-अभिमतात्",
      "- सुखदात्",
      "- वसुदेवसुतात्",
      "परं न कलये ।",
    ],
    prose: [
      "I do not consider anyone Supreme other than the one",
      "- who is surrounded by hundres of crores of Gopikas who are enchanted by the music from his flute,",
      "- whose beauty is equal to that of crores of Cupids,",
      "- who is in the hearts of each and every Gopika",
      "- who is giver of happiness,",
      "- who is son of Vasudeva",

      // "I will consider no deity other than the Lord Krishna the son of Vasudeva, whose beauty is equal to that of a thousand cupids; surrounded by thousands of Gopis enchanted by the flute, the granter of joy to all beings.",
      // "With an enchanting music from your flute, you attracted the gopis and bestowed each one of them with their desired happiness that is equal to the happiness obtained from hundred crore penances or crores of prayers. O Son of VasudEva (Krishna), none is equal to you. ",
      // "There is no comparison to the son of Vasudeva, Who attracts the gopa maidens, by music from his flute, And fulfills the desire of each gopi and gives her pleasure, Much More than hundreds of crores of penances, And prayers addressed to crores of similar Gods..",
    ],
    transl: [
      "I do not consider anyone Supreme other than Lord Krishna (Venkateswara), who is surrounded by hundreds of crores of Gopikas who are enchanted by the music from his flute, whose beauty is equal to that of crores of Manmathas, who is in the hearts of each and every gopika, who is giver of happiness, and the son of Vasudeva.",
    ],
    transl_tel: [
      "వేలకోట్ల గోపికలతో చుట్టుముట్టబడి, తన మురళీ గానంతో వారిని మంత్రముగ్ధులను చేసేవాడు, కోట్లాది మన్మథుల సౌందర్యంతో సమానమైన రూపం కలవాడు, ప్రతి గోపిక హృదయంలో నివసించేవాడు, సకల సౌఖ్యములను ప్రసాదించేవాడు మరియు వసుదేవ నందనుడైన ఆ శ్రీకృష్ణుడు (వేంకటేశ్వరుడు) తప్ప వేరే ఎవరిని నేను సర్వోన్నతుడిగా భావించను.",
    ],
    essence: [],
    meanings: [],
    grammar: [],
    notes: [
      "कल = Melodious/sweet",
      "वेणु = Flute",
      "रव = शब्दः = Sound",
      "अवश = captivated/overwhelmed",
      "गोप-वधू = cowherd women (Gopis)",
      "शत-कोटि-वृतात् = Surrounded by hundreds of crores (millions)",
      "स्मर = कामदेवः = Cupid/Manmatha",
      "कोटि = crores (millions)",
      "समात् = equal to",
      "प्रतिवल्लविका = to each and every gopi - (वल्लव = गोपालः)",
      "अभिमतात् = dear/beloved",
      "सुखदात् = Giver of supreme bliss",
      "वसुदेव-सुतात् = from Son of Vasudeva (Lord Krishna)",
      "परम् = superior",
      "न = not",
      "कलये = I consider",
    ],
  },
  {
    chapter: 2,
    number: 6,
    sloka: [
      "अभिरामगुणाकर दाशरथे",
      "जगदेकधनुर्धर धीरमते ।",
      "रघुनायक राम रमेश विभो",
      "वरदो भव देव दयाजलधे ॥ ६॥",
    ],
    sloka_tel: [
      "అభిరామగుణాకర దాశరథే",
      "జగదేకధనుర్ధర ధీరమతే |",
      "రఘునాయక రామ రమేశ విభో",
      "వరదో భవ దేవ దయాజలధే || ౬ ||",
    ],
    vicheda: [
      "अभिराम गुणाकर दाशरथे",
      "जगदेक-धनुर्धर धीरमते ।",
      "रघुनायक राम रमेश विभो",
      "वरदः भव देव दयाजलधे ॥ ६॥",
    ],
    anvaya: [
      "हे",
      "- (अभिराम)",
      "- (गुणाकर)",
      "- (दाशरथे)",
      "- (जगदेक-धनुर्धर)",
      "- (धीरमते)",
      "- (रघुनायक)",
      "- (राम)", 
      "- (रमेश)", 
      "- (विभो)", 
      "- (दयाजलधे)",
      "वरदः भव ।",
    ],
    prose: [
      "O Lord! one",
      "- who gives extreme bliss,",
      "- who is a mine of noble qualities",
      "- who is a son of Dasaratha",
      "- who is one and only weilder of the bow,",
      "- who has a courageous mind",
      "- who is the leader of Raghu dynasty",
      "- who is all pleasing,",
      "- who is the Lord of Ramaa (Mother Lakshmi)",
      "- who is all pervading (omni-present)",
      "- who is an ocean of compassion,",
      "Please become a boon giver.",

      // "O repository of all pleasing qualities, O Son of Dasaratha, O Unique and Sole Creator, O Courageous One! O Lord of the Raghus, O Lord of Lakshmi, O Delightful One! O Omnipresent One, Ocean of compassion, O God, be my benefactor.",
      // "You have been the lovely and virtuous son of Dasharatha; you are the only courageous and great archer of the entire world, the chief of Raghukula, the pleasing and entertaining Lord. Please grant the boon to me, O Lord and Ocean of Mercy. ",
      // "Become the boon giver, Oh sea of mercy, Oh matchless doer of the good, Oh son of Dasaratha, Oh only archer of the world, oh god with a brave heart, Oh Rama the lord of Raghu clan, And Oh God who is the Lord of Lakshmi.",
    ],
    transl: [
      "O Lord Rama (Lord Venkateswara) ! O Lord! the one who gives extreme bliss, who is a repository of noble qualities, who is son of Dasaratha, who is an only wielder of the bow, who has a courageous mind, who is the leader of Raghu dynasty, who is all pleasing, who is the Lord of Ramaa (Lakshmi), who is all pervading one, and who is an ocean of compassion. Please become a boon giver.",
    ],
    transl_tel: [
      "శ్రీ వేంకటాచలపతీ! రామచంద్రా! పరమానంద స్వరూపుడా, సకల సద్గుణాలకు నిలయమైనవాడా, దశరథ నందనా! సాటిలేని కోదండధారివి, ధైర్యవంతుడైన మనసు కలవాడా, రఘువంశ తిలకమా! అందరినీ అలరించేవాడా, రమాదేవి (లక్ష్మి) నాథుడా, విభుడా (సర్వవ్యాపివైన వాసుదేవుడా), దయా సముద్రుడా! మాకు వరములను అనుగ్రహించుము.",
    ],
    essence: [],
    meanings: [],
    grammar: [],
    notes: [
      "अभिराम = extremely charming/delightful/pleasing",
      "गुणाकर = mine of virtues, one who possesses noble qualities",
      "दाशरथे = Son of dasaratha",
      "जगदेक-धनुर्धर = one and only wielder of the bow in the world",
      "धीरमते = one with steady/courageous mind",
      "रघुनायक = leader of Raghu clan/dynasty",
      "राम = The all-pleasing one, embodiment of bliss",
      "रमेश = Lord of Lakshmi",
      "विभो = All-pervading Lord, omnipresent",
      "दयाजलधे = Ocean of compassion",
      "देव = O Lord",
      "वरदः भव = Please become bestower of boons",
    ],
  },
  {
    chapter: 2,
    number: 7,
    sloka: [
      "अवनीतनयाकमनीयकरं",
      "रजनीकरचारुमुखाम्बुरुहम् ।",
      "रजनीचरराजतमोमिहिरं",
      "महनीयमहं रघुराममये ॥ ७॥",
    ],
    sloka_tel: [
      "అవనీతనయా కమనీయకరం",
      "రజనీకరచారుముఖాంబురుహమ్ |",
      "రజనీచరరాజతమోమిహిరం",
      "మహనీయమహం రఘురామమయే || ౭ ||",
    ],
    vicheda: [
      "अवनी-तनया-कमनीय-करम्",
      "रजनी-कर-चारु-मुख-अम्बुरुहम् ।",
      "रजनी-चर-राज-तमः-मिहिरम्",
      "महनीयम् अहं रघुरामम् अये ॥ ७॥",
    ],
    anvaya: [
      "अहं",
      "- अवनी-तनया-कमनीय-करम्",
      "- रजनी-कर-चारु-मुख-अम्बुरुहम्",
      "- रजनी-चर-राज-तमः-मिहिरम्",
      "- महनीयम्",
      "- रघु-रामम्",
      "अये ।",
    ],
    prose: [
      "I",
      "- the one who is pleasing to the daughter of earth (Mother Sita),",
      "- the one who lotus face (मुख-अम्बुरुहम्) is as beautiful as moon (रजनी-कर),",
      "- the one who removes darkness of Ravana (king of night wanderers - रजनी-चर) like the Sun,",
      "- the one who is great/worthy of worship,",
      "- the Sri Rama of Raghu dynasty,",
      "take refuge in",

      // "The one who is pleasing to Sita. The one whose face is as beautiful as the moon and resembles a lotus. The one who is like the sun that destroys the darkness of the king of night-wanderers (Ravana). I take refuge in the most worshipful Lord Rama of the Raghu dynasty.",
      // "I take refuge at the feet of scion of the race of Raghu; Lord Rama, who is the delight of Sita; with a lotus-­‐face like the full moon; who is like the sun in the destruction of the darkness of ignorance, most worthy of honour.",
      // "Your pretty hands are held by the daughter of Earth, Sita; and you are beautiful with your lotus-like face resembling the moon. You are the king dispelling all the darkness by walking in the nights. Grant me refuge O Rama of Raghu clan.",
      // "I seek refuge in the great Rama of Raghu clan, Whose pretty hands are held by the daughter of earth, Who has a pretty lotus-like face, similar to the moon, And who as a king walks at night and destroys darkness like the sun.",
    ],
    transl: [
      "I take refuge in Lord Sri Rama (Venkateswara), who is pleasing to Mother Sita, who has a lotus face as beautiful as the moon, who removes darkness of Ravana like the Sun, who is worthy of worship, and who belongs to Raghu dynasty.",
    ],
    transl_tel: [
      "సీతాదేవికి మనోల్లాసాన్ని కలిగించేవాడు, చంద్రుని వంటి అందమైన ముఖకమలము కలవాడు, సూర్యుడు చీకటిని పారద్రోలినట్లుగా రావణుడనే అంధకారాన్ని నశింపజేసినవాడు, సకల లోకములచే పూజింపదగినవాడు మరియు రఘువంశమున జన్మించినవాడైన ఆ శ్రీరామచంద్రుని (వేంకటేశ్వరుని) నేను శరణు వేడుతున్నాను.",
    ],
    essence: [],
    meanings: [],
    grammar: [],
    notes: [
      "अवनी = Earth",
      "तनया = Daughter",
      "कमनीय = Charming",
      "करम् = Doer",
      "रजनी-कर = Moon (One who makes night beautiful)",
      "चारु = Beautiful/Pleasing",
      "मुख-अम्बुरुहम् = One who has Lotus like Face",
      "रजनी-चर = One who moves at night (Demons, Ravana)",
      "राज = King",
      "तमः = Darkness/Ignorance",
      "मिहिरम् = Sun (One who removes Darkness)",
      "महनीयम् = One who is great/worthy of worship",
      "रघु-रामम् = Sri Rama of Raghu dynasty",
      "अये = अय् (1A - भ्वादिः - to go) - कर्तरि लट् - उ.पु. - एक.व. = I take refuge in",
    ],
  },
  {
    chapter: 2,
    number: 8,
    sloka: [
      "सुमुखं सुहृदं सुलभं सुखदं",
      "स्वनुजं च सुकायममोघशरम् ।",
      "अपहाय रघूद्वहमन्यमहं",
      "न कथञ्चन कञ्चन जातु भजे ॥ ८॥",
    ],
    sloka_tel: [
      "సుముఖం సుహృదం సులభం సుఖదం",
      "స్వనుజం చ సుకాయమమోఘశరమ్ |",
      "అపహాయ రఘూద్వహమన్యమహం",
      "న కథంచన కంచన జాతు భజే || ౮ ||",
    ],
    vicheda: [
      "सुमुखं सुहृदं सुलभं सुखदं",
      "सु-अनुजं च सुकायम् अमोघशरम् ।",
      "अपहाय रघु-उद्वहम् अन्यम् अहं",
      "न कथञ्चन कञ्चन जातु भजे ॥ ८॥",
    ],
    anvaya: [
      "अहं",
      "- जातु",
      "-- सुमुखं", 
      "-- सुहृदं", 
      "-- सुलभं", 
      "-- सुखदं", 
      "-- सु-अनुजं",
      "-- सुकायम्", 
      "-- अमोघशरम्", 
      "- च रघु-उद्वहम्",
      "अपहाय",
      "- अन्यम्",
      "कथञ्चन कञ्चन न भजे ।",
    ],
    prose: [
      "I",
      "- at any time",
      "-- one with beautiful face,", 
      "-- one with beautiful heart,",
      "-- one who is easily attainable,",
      "-- one who gives happiness,",
      "-- one with good brothers,",
      "-- one with good body,",
      "-- one having great arrows,",
      "- and the great one of Raghu dyansty,",
      "having left",
      "- anyone else",
      "do not worship any other devata in any way.",

      // "O Handsome One, O Friend easily accessible, Giver of Joy, having good brothers, O you of Beauteous Body, with the unfailing arrow, the Saviour, abandoning all others I take refuge in you alone. ",
      // "You are pleasant-faced, good-hearted, easily reachable, and you are the provider of happiness along with your brothers and with a never-ending flow of arrows. So, I never pray to anyone else even for a while except you, O Rama. ",
      // "You are with a pleasant face, good heart, Very easy to reach and giver of pleasures, Along with your brothers and with a never-ending stream of arrows, So leaving you, I would never at any time, even for a second, Pray anyone else, Oh Jewel of the Raghu clan.",
    ],
    transl: [
      "I do not worship any other devata at any time in any way, having left, Lord Sri Rama (Venkateswara) who is the best of Raghu dynasty, who has a beautiful face and a good heart, who has great brothers, who has a good body, who arrows never go in vain.",
    ],
    transl_tel: [
      "రఘువంశ శ్రేష్ఠుడైనవాడు, అందమైన ముఖము మరియు నిర్మలమైన హృదయము కలవాడు, గొప్పవారైన సోదరులు (లక్ష్మణ, భరత, శత్రుఘ్నులు) కలవాడు, సుందరమైన విగ్రహము కలవాడు మరియు ఎన్నడూ లక్ష్యం తప్పని అమోఘమైన బాణములు కలవాడైన ఆ శ్రీరామచంద్రుని (వేంకటేశ్వరుని) వదిలి—నేను మరి ఏ ఇతర దేవతను, ఎన్నడూ, ఏ విధంగానూ ఆరాధించను.",
    ],
    essence: [],
    meanings: [],
    grammar: [],
    notes: [
      "अहं = I",
      "जातु = कदाचित् = at any time/ever",
      "सुमुखं = one with beautiful face",
      "सुहृदं = one with good heart/a true friend/well wisher",
      "सुलभं = one who is easily attainable/approachable",
      "सुखदं = one who is giver of happiness",
      "स्वनुजं = सु-अनुजं = one with good younger brother (Lakshmana)",
      "सुकायम् = one with beautiful body",
      "अमोघशरम् = अमोघ-शरम् = one whose arrows never go in vain",
      "रघूद्वहम् = रघु-उद्वहम् = The great one of the Raghu dynasty, i.e., Lord Rama - (उद्-वह् - 1U - भ्वादिः - carrying or leading up/son/offspring/best)",
      "अपहाय = अप + हाय = having left = (हा - to abandon/leave - 3P -जुहोत्यादिः - ल्यप् (अव्ययम्))",
      "अन्यम् = anyone else",
      "कथञ्चन = in any way",
      "कञ्चन = anyone at all",
      "न = Not",
      "भजे = worship",
    ],
  },
  {
    chapter: 2,
    number: 9,
    sloka: [
      "विना वेङ्कटेशं न नाथो न नाथः",
      "सदा वेङ्कटेशं स्मरामि स्मरामि ।",
      "हरे वेङ्कटेश प्रसीद प्रसीद",
      "प्रियं वेङ्कटेश प्रयच्छ प्रयच्छ ॥ ९॥",
    ],
    sloka_tel: [
      "వినా వేంకటేశం న నాథో న నాథః",
      "సదా వేంకటేశం స్మరామి స్మరామి |",
      "హరే వేంకటేశ ప్రసీద ప్రసీద",
      "ప్రియం వేంకటేశ ప్రయచ్ఛ ప్రయచ్ఛ || ౯ ||",
    ],
    vicheda: [
      "विना वेङ्कटेशं न नाथः न नाथः",
      "सदा वेङ्कटेशं स्मरामि स्मरामि ।",
      "हरे वेङ्कटेश प्रसीद प्रसीद",
      "प्रियं वेङ्कटेश प्रयच्छ प्रयच्छ ॥ ९॥",
    ],
    anvaya: [
      "वेङ्कटेशं विना न नाथः न नाथः ।",
      "(अहं) सदा वेङ्कटेशं स्मरामि स्मरामि ।",
      "(हे) हरे! (हे) वेङ्कटेश! प्रसीद प्रसीद ।",
      "(हे) वेङ्कटेश! प्रियं प्रयच्छ प्रयच्छ ।",
    ],
    prose: [
      "I do not have any other master other than Lord Venkateswara.",
      "I always remember Lord Venkateswara.",
      "O Hari! O Venkatesa! Become pleased.",
      "O Venkatesa! please bestow (with your love and grace).",

      // "Apart from Lord Venkatesvara I have neither master nor place of rest. Again and again I remember Lord Venkatesvara. O Saviour, O Lord Venkatesvara! Be gracious towards me and bestow your compassion upon me. ",
      // "Without you, O Venkateshwara, I am an orphan. I always keep remembering your name. O Venkatesa, kindly be pleased with me and bestow me with your love and grace.",
      // "I do not have any Lord except Venkatesa, I remember and remember only Lord Venkatesa, So Hey Venkatesa, be pleased with me, I request you to give me only what you like.",
    ],
    transl: [
      "I do not have any other master other than Lord Venkateswara. I always remember Lord Venkateswara. O Lord Hari! O Lord Venkatesa! please become pleased by me. O Lord Venkatesa! please bestow your love and grace upon me.",
    ],
    transl_tel: [
      "శ్రీ వేంకటేశ్వరుడు తప్ప నాకు వేరే దిక్కు (యజమాని) లేరు. నేను ఎల్లప్పుడూ ఆ వేంకటేశ్వరునినే స్మరిస్తాను. ఓ హరీ! వేంకటేశా! నాపై ప్రసన్నుడవు కమ్ము. ఓ వేంకటేశా! నీ ప్రేమను మరియు అనుగ్రహాన్ని నాపై కురిపించుము.",
    ],
    essence: [],
    meanings: [],
    grammar: [],
    notes: [
      "प्रसीद = प्र + सद् (सुखी होना) - कर्तरि लोट् - (परस्मै) - म.पु. - एक.व. = Please become pleased - (सद् - 1P - भ्वादिः - to dry up/lose power - सीदन्ति मम गात्राणि - BG 1.28)",
      "प्रियं = Beloved, dear thing",
      "प्रयच्छ = प्र-यच्छ - कर्तरि लोट् - परस्मै = Please grant/bestow - (दा - 1P - भ्वादिः - to give - प्र+दा - देना) ",
    ],
  },
  {
    chapter: 2,
    number: 10,
    sloka: [
      "अहं दूरतस्ते पदाम्भोजयुग्म-",
      "प्रणामेच्छयाऽऽगत्य सेवां करोमि ।",
      "सकृत्सेवया नित्यसेवाफलं त्वं",
      "प्रयच्छ प्रयच्छ प्रभो वेङ्कटेश ॥ १०॥",
    ],
    sloka_tel: [
      "అహం దూరతస్తే పదాంభోజయుగ్మ-",
      "-ప్రణామేచ్ఛయాఽఽగత్య సేవాం కరోమి |",
      "సకృత్సేవయా నిత్యసేవాఫలం త్వం",
      "ప్రయచ్ఛ ప్రయచ్ఛ ప్రభో వేంకటేశ || ౧౦ ||",
    ],
    vicheda: [
      "अहं दूरतः ते पदाम्भोजयुग्म-",
      "प्रणामेच्छया आगत्य सेवां करोमि ।",
      "सकृत्सेवया नित्यसेवाफलं त्वं",
      "प्रयच्छ प्रयच्छ प्रभो वेङ्कटेश ॥ १०॥",
    ],
    anvaya: [
      "हे (वेङ्कटेश) प्रभो !",
      "(ते पद-अम्भोज-युग्म-प्रणाम-इच्छया) (दूरतः आगत्य) अहं सेवां करोमि ।",
      "सकृत्सेवया नित्यसेवाफलं त्वं प्रयच्छ प्रयच्छ ।",
    ],
    prose: [
      "O Venkatesa! O Lord!",
      "By the desire of worshipping your lotus feet, having come from distance, I am serving you.",
      "By this one-time service, You please bestow upon me the result of serving you eternally.",

      // "O Lord Venkatesvara! I have come from afar in order to salute you lotus feet, and I have come to perform some service, by this small service, grant me the fruit of daily service. ",
      // "I have been far away from your lotus-like feet and have now come with a wish to serve the feet. So, Lord Venkatesha, I request you, again and again, please allow me the benefit of performing a good service to you. ",
      // "I was far away from your two lotus-like feet, And have come with a wish to serve them, And so I request and request you, Lord Venkatesa, To please allow me to do good service to you. ",
    ],
    transl: [
      "O Lord Venkatesa! By the desire of worshipping your lotus feet, having come from distance, I am serving you. By this one-time service, you please bestow upon me the result of serving you eternally.",
    ],
    transl_tel: [
      "ఓ వేంకటేశా! నీ పాదపద్మములను సేవించాలనే కోరికతో, ఎంతో దూరం నుండి వచ్చి నేను నిన్ను కొలుస్తున్నాను. నేను చేసిన ఈ ఒక్కసారి సేవకే సంతసించి, నీకు నిరంతరం సేవ చేసే (నిత్య కైంకర్య) ఫలాన్ని నాకు ప్రసాదించుము.",
    ],
    essence: [],
    meanings: [],
    grammar: [],
    notes: [
      "अम्भोज = lotus = borm from water (अम्भः = जलं - water)",
      "युग्म = pair",
      "सकृत् = एकवारम् - (अव्ययम्) = once",
    ],
  },
  {
    chapter: 2,
    number: 11,
    sloka: [
      "अज्ञानिना मया दोषान् अशेषान्विहितान् हरे ।",
      "क्षमस्व त्वं क्षमस्व त्वं शेषशैलशिखामणे ॥ ११॥",
    ],
    sloka_tel: [
      "అజ్ఞానినా మయా దోషానశేషాన్విహితాన్ హరే |",
      "క్షమస్వ త్వం క్షమస్వ త్వం శేషశైలశిఖామణే || ౧౧ ||",
    ],
    vicheda: [
      "अज्ञानिना मया दोषान् अशेषान् विहितान् हरे ।",
      "क्षमस्व त्वं क्षमस्व त्वं शेष-शैल-शिखा-मणे ॥ ११॥",
    ],
    anvaya: [
      "हे (शेष-शैल-शिखा-मणे) हरे !",
      "(अज्ञानिना) मया विहितान् (अशेषान्) दोषान् ।",
      "त्वं क्षमस्व त्वं क्षमस्व ।",
    ],
    prose: [
      "O Lord Hari! O jewel of Shesha Shaila!",
      "innumerabale faults committed by (ignorant) me,",
      "You please forgive, please forgive.",

      // "O Gorgeous Gem of Shesha Mountain! O Saviour! Please grant me forgiveness for all these faults which I an ignorant person have committed. Please forgive me!",
      // "The sins committed by me are all simply due to the sheer ignorance of mine; so kindly please pardon me, pardon me, O jewel of Sesha Shaila Mountain.",
      // "Please pardon, please pardon, Oh crest jewel of the Sesha mountain, This ignorant sinner of the sins committed, Due to sheer helplessness, Oh Hari.",
    ],
    transl: [
      "O Lord Hari! O Lord Venkatesa! Please forgive all the faults committed by (ignorant) me.",
    ],
    transl_tel: [
      "ఓ హరీ! వేంకటేశ్వరా! అజ్ఞానినైన నా చేత తెలియక చేయబడిన సకల అపరాధములను దయతో క్షమించుము.",
    ],
    essence: [],
    meanings: [],
    grammar: [],
    notes: [],
  },
  // "॥ इति वेङ्कटेशस्तोत्रम् ॥"
  // ఇతి శ్రీవేంకటేశ స్తోత్రమ్ |
];

export default verses;
