// "॥ अथ वेङ्कटेशप्रपत्ति ॥",
const verses = [
  {
    chapter: "SVS_3",
    number: 1,
    sloka: [
      "ईशानां जगतोऽस्य वेङ्कटपतेर्विष्णोः परां प्रेयसीं",
      "तद्वक्षस्स्थलनित्यवासरसिकां तत्क्षान्तिसंवर्धिनीम् ।",
      "पद्मालङ्कृतपाणिपल्लवयुगां पद्मासनस्थां श्रियं",
      "वात्सल्यादिगुणोज्ज्वलां भगवतीं वन्दे जगन्मातरम् ॥ १॥",
    ],
    vicheda: [
      "ईशानां जगतः अस्य वेङ्कटपतेः विष्णोः परां प्रेयसीं",
      "तत्-वक्षःस्थल-नित्य-वास-रसिकाम् तत्-क्षान्ति-संवर्धिनीम् ।",
      "पद्म-अलङ्कृत-पाणि-पल्लव-युगाम् पद्म-आसन-स्थाम् श्रियं",
      "वात्सल्य-आदि-गुण-उज्ज्वलाम् भगवतीं वन्दे जगत्-मातरम् ॥ १॥",
    ],
    anvaya: [
      "अहं",
      "- (अस्य जगतः ईशानां) (वेङ्कटपतेः) विष्णोः परां प्रेयसीं ।",
      "- (तत्-वक्षःस्थल-नित्यवास-रसिकां) ।",
      "- तत्-क्षान्ति-संवर्धिनीम् ।",
      "- पद्म-आलङ्कृत-पाणि-पल्लव-युगां ।",
      "- पद्मासन-स्थाम् ।",
      "- वात्सल्य-आदि-गुण-उज्ज्वलाम् ।",
      "- जगन्मातरम् ।",
      "भगवतीं श्रियं वन्दे ।",
    ],
    transl: [
      "I pay my obeisance to Lakshmi the ruler of the universe, who is the most beloved of Lord Vishnu the Lord of Mount Venkata, who rests with supreme delight upon His chest, and increases His forbearance, whose hands tender as sprouts, are decorated with lotus blossoms, whose seat is the lotus (of the mind) who is radiant with perfection of qualities such as tender solicitude etc. and who is the Mother of the Universe.",
      "I bow down to the divine Goddess Lakshmi, the supreme beloved of Lord Vishnu, the Lord of Venkata hills and ruler of the universe. She eternally resides on His chest and nurtures His patience and forbearance. Her tender hands are adorned with lotuses, and she is seated on a lotus throne. She shines with qualities such as motherly affection and is the universal mother. O Bhagavati, I offer my reverence to you!",
    ],
    notes: [
      "अस्य जगतः = of this world",
      "ईशानां = To the Lord/master/ruler(feminine) - द्वितीया.वि. - एक.व.",
      "(वेङ्कटपतेः) विष्णोः = Of Lord Vishnu/Lord Venkateswara",
      "परां प्रेयसीं = To the Supreme Beloved (consort)",
      "तत्-वक्षःस्थल-नित्यवास-रसिकां = to The one who eternally delights in residing on His chest",
      "तत्-क्षान्ति-संवर्धिनीम् = to The one who nurtures His (Vishnu’s) patience and forbearance",
      "पद्म-आलङ्कृत-पाणि-पल्लव-युगाम् = to The one whose tender hands are adorned with lotuses",
      "पद्मासन-स्थाम् = to The one seated on a lotus (Goddess Lakshmi)",
      "श्रियम् = Goddess Lakshmi",
      "वात्सल्य-आदि-गुण-उज्ज्वलाम् = to The one resplendent with qualities like motherly affection",
      "भगवतीम् = to The divine goddess",
      "जगन्मातरम् = to The mother of the universe",
      "(अहं) वन्दे = I bow down to, I worship",
    ],
  },
  {
    chapter: "SVS_3",
    number: 2,
    sloka: [
      "श्रीमन् कृपाजलनिधे कृतसर्वलोक",
      "सर्वज्ञ शक्त नतवत्सल सर्वशेषिन् ।",
      "स्वामिन् सुशील सुलभाश्रितपारिजात",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ २॥",
    ],
    vicheda: [
      "श्रीमन् कृपा-जल-निधे कृत-सर्व-लोक",
      "सर्वज्ञ शक्त नत-वत्सल सर्व-शेषिन् ।",
      "स्वामिन् सुशील सुलभ-आश्रित-पारिजात",
      "श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ २॥",
    ],
    anvaya: [
      "हे",
      "- (श्रीमन्) (कृपा-जल-निधे) कृत-सर्व-लोक !",
      "- (सर्वज्ञ) (शक्त) (नत-वत्सल) (सर्व-शेषिन्) !",
      "- (स्वामिन्) (सुशील) (सुलभ-आश्रित-पारिजात) !",
      "(अहं) श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ।",
    ],
    transl: [
      "I take refuge in the lotus feet of Lord Venkateswara, who is opulent, and ocean of compassion, the Creator of the entire universe, omniscient, omnipotent, affectionate to the humble, the essence of the universe, the Master, amiable and receptive, fulfilling the desires of those who take refuge in him.",
      "O Lord of prosperity! O ocean of mercy! O creator of all worlds! You are omniscient, omnipotent, and the protector of those who bow before You. You are the ultimate refuge of all. O Master! You are virtuous, easily accessible, and like a wish-fulfilling tree for those who seek shelter in You. O Lord Venkatesha! I completely surrender at Your divine feet.",
    ],
    notes: [
      "श्रीमन् = O Lord of great fortune (possessor of Lakshmi)",
      "कृपा-जल-निधे = O the Lord, who is Ocean of compassion",
      "कृतसर्वलोक = Creator of all the worlds",
      "सर्वज्ञ = Omniscient (all-knowing)",
      "शक्त = Omnipotent (all-powerful)",
      "नत-वत्सल = Compassionate to those who bow before You - (नम् - to bow down - 1P - भ्वादिः - क्त)",
      "सर्वशेषिन् = The ultimate refuge and master of all (everything is dependent on You)",
      "स्वामिन् = O Lord!",
      "सुशील = Possessor of great virtues and noble character",
      "सुलभ = Easily accessible (merciful to devotees)",
      "आश्रितपारिजात = The wish-fulfilling tree for those who take refuge in You",
      "श्रीवेङ्कटेश-चरणौ = To the two feet of Lord Venkateswara - द्वितीया.वि. - एक.व.",
      "शरणं = Refuge/Surrender",
      "(अहं) प्रपद्ये = I surrender, I (offer) myself = (पद् - to go/attain - 4A - दिवादिः - कर्तरि लट् - उ.पु. - एक.व.)",
    ],
  },
  {
    chapter: "SVS_3",
    number: 3,
    sloka: [
      "आनूपुरार्पितसुजातसुगन्धिपुष्प-",
      "सौरभ्यसौरभकरौ समसन्निवेशौ ।",
      "सौम्यौ सदाऽनुभवनेऽपि नवानुभाव्यौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ३॥",
    ],
    vicheda: [
      "आनूपुर-अर्पित-सुजात-सुगन्धि-पुष्प-",
      "सौरभ्य-सौरभकरौ सम-सन्निवेशौ ।",
      "सौम्यौ सदा अनुभवने अपि नवानुभाव्यौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ३॥",
    ],
    anvaya: [
      "(अहं)",
      "- आनूपुर-अर्पित-सुजात-सुगन्धि-पुष्प-सौरभ्य-सौरभकरौ",
      "- सम-सन्निवेशौ",
      "- सौम्यौ",
      "- सदा अनुभवने अपि नवानुभाव्यौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, which impart their fragrance to the lovely garlands of scented flowers which hang below his anklets, resting gently, although experienced constantly, the enjoyment is ever fresh.",
      "I surrender to the divine feet of Lord Venkatesha, which are adorned with beautifully fragrant flowers placed near His anklets. These feet emanate a divine fragrance, are symmetrically positioned, and possess a gentle charm. Even when experienced continuously, they always appear fresh and ever new.",
    ],
    notes: [
      "आनूपुर = Near the anklets",
      "अर्पित = Offered, placed",
      "सुजात = Beautifully born, well-formed",
      "सुगन्धिपुष्प = Fragrant flowers",
      "सौरभ्य = Fragrance",
      "सौरभकरौ = Those that spread fragrance",
      "समसन्निवेशौ = Symmetrically placed (well-proportioned)",
      "सौम्यौ = Gentle, pleasant",
      "सदा = Always",
      "अनुभवने अपि = Even in experience",
      "नवानुभाव्यौ = Always fresh and ever new in experience",
    ],
  },
  {
    chapter: "SVS_3",
    number: 4,
    sloka: [
      "सद्योविकासिसमुदित्वरसान्द्रराग-",
      "सौरभ्यनिर्भरसरोरुहसाम्यवार्ताम् ।",
      "सम्यक्षु साहसपदेषु विलेखयन्तौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ४॥",
    ],
    vicheda: [
      "सद्यः-विकासि-समुदित-वर-सान्द्र-राग-",
      "सौरभ्य-निर्भर-सरोरुह-साम्य-वार्ताम् ।",
      "सम्यक्षु साहस-पदेषु विलेखयन्तौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ४॥",
    ],
    anvaya: [
      "(अहं)",
      "- सद्यः-विकासि-समुदित-वर-सान्द्र-राग-सौरभ्य-निर्भर-सरोरुह-साम्य-वार्ताम्",
      "- सम्यक्षु साहस-पदेषु विलेखयन्तौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, which resemble by their beauty newly blossomed exceedingly fragrant red lotuses. The testimony is self evident.",
      "I surrender to the divine feet of Lord Venkatesha, which bloom instantly like a freshly opened lotus, enriched with deep red color and overflowing with fragrance. Their beauty reminds one of a lotus. As He moves with bold and confident steps, His divine feet leave marks on the ground, radiating their celestial presence.",
    ],
    notes: [
      "सद्यः-विकासि = Instantly blooming",
      "समुदित = Fully manifesting",
      "वर = Supreme, excellent",
      "सान्द्र-राग = Deeply enriched with color (symbolizing divine grace and love)",
      "सौरभ्य-निर्भर = Overflowing with fragrance",
      "सरोरुह-साम्य-वार्ताम् = Reminding one of a lotus (in beauty and fragrance)",
      "सम्यक्-अषु = Very quickly, properly",
      "साहस-पदेषु = In bold or courageous steps",
      "विलेखयन्तौ = Marking or engraving (the ground as they move)",
    ],
  },
  {
    chapter: "SVS_3",
    number: 5,
    sloka: [
      "रेखामयध्वजसुधाकलशातपत्र",
      "वज्राङ्कुशाम्बुरुहकल्पकशङ्खचक्रैः ।",
      "भव्यैरलङ्कृततलौ परतत्त्वचिन्हैः",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ५॥",
    ],
    vicheda: [
      "रेखामय-ध्वज-सुधा-कलश-आतपत्र-",
      "वज्र-अङ्कुश-अम्बुरुह-कल्पक-शङ्ख-चक्रैः ।",
      "भव्यैः अलङ्कृत-तलौ परतत्त्व-चिन्हैः",
      "श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ ५॥",
    ],
    anvaya: [
      "(अहं)",
      "- (भव्यैः) (परतत्त्व-चिन्हैः)",
      "- रेखामय-ध्वज-सुधा-कलश-आतपत्र-वज्र-अङ्कुश-अम्बुरुह-कल्पक-शङ्ख-चक्रैः",
      "- (अलङ्कृत-तलौ) श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, which are most worthy, marked with the divine and auspicious symbols of a flag, pot of ambrosia, umbrella, thunderbolt, elephant goad, conch-shell, and discus.",
      "I surrender to the divine feet of Lord Venkatesha, whose soles are adorned with auspicious marks representing the Supreme Truth, such as lines, flag, nectar pot, umbrella, thunderbolt, goad, lotus, celestial wish-fulfilling tree, conch, and discus.",
      "This verse glorifies the sacred feet of Lord Venkatesha, highlighting the divine symbols that adorn them, which signify protection, prosperity, and supreme divinity.",
    ],
    notes: [
      "भव्यैः = auspicious",
      "परतत्त्व-चिन्हैः = with symbols representing the supreme truth",      
      "रेखामय-ध्वज-सुधा-कलश-आतपत्र-वज्र-अङ्कुश-अम्बुरुह-कल्पक-शङ्ख-चक्रैः = marked with divine symbols such as lines, flag, nectar pot, umbrella, thunderbolt, goad, lotus, celestial wish-fulfilling tree, conch, and discus",
      "अलङ्कृत-तलौ = decorated soles",
      "शरणं प्रपद्ये = I surrender",
      "अङ्कुश = The Sanskrit word अङ्कुश (aṅkuśa) means elephant goad or hook. It is a traditional tool used to control and guide elephants, typically made of metal with a pointed curved end. In a spiritual or symbolic context, अङ्कुश represents control, discipline, and guidance, often signifying the ability to steer one's mind and senses in the right direction. It is commonly associated with Lord Ganesha and other deities, symbolizing mastery over desires and obstacles.",
      "तलौ = The word तलौ (talau) is the dual form of तल (tala), which means sole (bottom part of feet.)"
    ],
  },
  {
    chapter: "SVS_3",
    number: 6,
    sloka: [
      "ताम्रोदरद्युतिपराजितपद्मरागौ",
      "बाह्यैर्महोभिरभिभूतमहेन्द्रनीलौ ।",
      "उद्यन्नखांशुभिरुदस्तशशाङ्कभासौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ६॥",
    ],
    vicheda: [
      "ताम्र-उदर-द्युति-पराजित-पद्मरागौ",
      "बाह्यैः महोभिः अभिभूत-महेन्द्रनीलौ ।",
      "उद्यत्-नख-अंशुभिः उदस्त-शशाङ्क-भासौ",
      "श्री-वेङ्कटेश-चरणौ शरणं प्रपद्ये ॥ ६॥",
    ],
    anvaya: [
      "(अहं)",
      "- ताम्र-उदर-द्युति-पराजित-पद्मरागौ",
      "- बाह्यैः महोभिः अभिभूत-महेन्द्रनीलौ",
      "- उद्यत्-नख-अंशुभिः उदस्त-शशाङ्क-भासौ",
      "- श्री-वेङ्कटेश-चरणौ",
      "शरणं प्रपद्ये ।",
    ],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, whose redness surpasses that of a ruby, and whose eternal resplendence exceeds that of the sapphire, the radiance of the nails excels that of the moon.",
      "I surrender to the divine feet of Lord Venkatesha, which shine with the brilliance of red lotus gems, surpassing even the radiance of glowing copper; whose outer luster eclipses the grandeur of the great blue sapphire (Indranīla); and whose toenails emit a rising brilliance, resembling the radiant glow of the full moon.",
      "This verse poetically describes the dazzling radiance of Lord Venkatesha's feet, comparing their colors and brilliance to precious gems, celestial lights, and natural elements, emphasizing their divine beauty and auspiciousness.",
    ],
    notes: [
      "ताम्र (tāmra) = Copper",
      "उदर (udara) = Belly, interior, or core",
      "द्युति (dyuti) = Radiance, brilliance, or luster",
      "ताम्र-उदर-द्युति-पराजित-पद्मरागौ = having the luster of a red lotus gem (Padmarāga), surpassing the radiance of copper interiors",
      "बाह्यैः महोभिः = by great external brilliance",
      "अभिभूत = eclipse",
      "अभिभूत-महेन्द्रनीलौ = surpassing the radiance of the great Indra Nīla (blue sapphire)",
      "उद्यत्-नख-अंशुभिः = with rising brilliance from the toenails",
      "उदस्त-शशाङ्क-भासौ = shining like the raised radiance of the full moon",
    ],
  },
  {
    chapter: "SVS_3",
    number: 7,
    sloka: [
      "सप्रेमभीति कमलाकरपल्लवाभ्यां",
      "संवाहनेऽपि सपदि क्लममादधानौ ।",
      "कान्ताववाङ्ग्मनसगोचरसौकुमार्यौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ७॥",
    ],
    vicheda: [
      "सप्रेमभीति कमलाकरपल्लवाभ्यां",
      "संवाहनेऽपि सपदि क्लममादधानौ ।",
      "कान्ताववाङ्ग्मनसगोचरसौकुमार्यौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ७॥",
    ],
    anvaya: [],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, so tender that they cannot bear even the gentle and careful massaging by the lotus-­‐like hands of Lakshmi. whose charm and delicacy are beyond comprehension and expression.",
    ],
    notes: [],
  },
  {
    chapter: "SVS_3",
    number: 8,
    sloka: [
      "लक्ष्मीमहीतदनुरूपनिजानुभाव-",
      "नीलादिदिव्यमहिषीकरपल्लवानाम् ।",
      "आरुण्यसङ्क्रमणतः किल सान्द्ररागौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ८॥",
    ],
    vicheda: [
      "लक्ष्मीमहीतदनुरूपनिजानुभाव-",
      "नीलादिदिव्यमहिषीकरपल्लवानाम् ।",
      "आरुण्यसङ्क्रमणतः किल सान्द्ररागौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ८॥",
    ],
    anvaya: [],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, whose red hue has been contracted from the reddish hands of Lakshmi, Bhudevi and Niladevi and the other consorts, all of equal dignity and radiance.",
    ],
    notes: [],
  },
  {
    chapter: "SVS_3",
    number: 9,
    sloka: [
      "नित्यानमद्विधिशिवादिकिरीटकोटि-",
      "प्रत्युप्तदीप्तनवरत्नमहःप्ररोहैः ।",
      "नीराजनाविधिमुदारमुपादधानौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ९॥",
    ],
    vicheda: [
      "नित्यानमद्विधिशिवादिकिरीटकोटि-",
      "प्रत्युप्तदीप्तनवरत्नमहःप्ररोहैः ।",
      "नीराजनाविधिमुदारमुपादधानौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ९॥",
    ],
    anvaya: [],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, who are constantly receiving the adoration of lights from the crowns of the deities like Brahma, Siva etc as they repeatedly bow down and pay their daily obeisance.",
    ],
    notes: [],
  },
  {
    chapter: "SVS_3",
    number: 10,
    sloka: [
      "विष्णोः पदे परम इत्युदितप्रशंसौ",
      "यौ मध्व उत्स इति भोग्यतयाऽप्युपात्तौ ।",
      "भूयस्तथेति तव पाणितलप्रदिष्टौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १०॥",
    ],
    vicheda: [
      "विष्णोः पदे परम इत्युदितप्रशंसौ",
      "यौ मध्व उत्स इति भोग्यतयाऽप्युपात्तौ ।",
      "भूयस्तथेति तव पाणितलप्रदिष्टौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १०॥",
    ],
    anvaya: [],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, whose feet are described in the Vedas as a fountain of ambrosia, an object of profound mystical experience expressed in manifold ways, and whose efficacy is demonstrated by the gesture of his hand pointing downwards.",
    ],
    notes: [],
  },
  {
    chapter: "SVS_3",
    number: 11,
    sloka: [
      "पार्थाय तत्सदृशसारथिना त्वयैव",
      "यौ दर्शितौ स्वचरणौ शरणं व्रजेति ।",
      "भूयोऽपि मह्यमिह तौ करदर्शितौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ११॥",
    ],
    vicheda: [
      "पार्थाय तत्सदृशसारथिना त्वयैव",
      "यौ दर्शितौ स्वचरणौ शरणं व्रजेति ।",
      "भूयोऽपि मह्यमिह तौ करदर्शितौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ ११॥",
    ],
    anvaya: [],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara — those feet which were resorted to by Arjuna, when you acted as his charioteer. You pointed to them with your hand as you gave the injunction — 'take refuge in me alone'.",
    ],
    notes: [],
  },
  {
    chapter: "SVS_3",
    number: 12,
    sloka: [
      "मन्मूर्ध्नि कालियफणे विकटाटवीषु",
      "श्रीवेङ्कटाद्रिशिखरे शिरसि श्रुतीनाम् ।",
      "चित्तेऽप्यनन्यमनसां सममाहितौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १२॥",
    ],
    vicheda: [
      "मन्मूर्ध्नि कालियफणे विकटाटवीषु",
      "श्रीवेङ्कटाद्रिशिखरे शिरसि श्रुतीनाम् ।",
      "चित्तेऽप्यनन्यमनसां सममाहितौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १२॥",
    ],
    anvaya: [],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, which are equally placed on my head as on the head of the dragon Kaliya, on the crest of Mount Venkata, on the head of the Secret Doctrine of the Upanishads and in the unwavering mind of the yogis.",
    ],
    notes: [],
  },
  {
    chapter: "SVS_3",
    number: 13,
    sloka: [
      "अम्लानहृष्यदवनीतलकीर्णपुष्पौ",
      "श्रीवेङ्कटाद्रिशिखराभरणायमानौ ।",
      "आनन्दिताखिलमनोनयनौ तवैतौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १३॥",
    ],
    vicheda: [
      "अम्लानहृष्यदवनीतलकीर्णपुष्पौ",
      "श्रीवेङ्कटाद्रिशिखराभरणायमानौ ।",
      "आनन्दिताखिलमनोनयनौ तवैतौ",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १३॥",
    ],
    anvaya: [],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, which appear as unfading flowers, spread over the earth and the crest of Mount Venkata, an ornament of great beauty in the mind and vision of everyone.",
    ],
    notes: [],
  },
  {
    chapter: "SVS_3",
    number: 14,
    sloka: [
      "प्रायः प्रपन्नजनताप्रथमावगाह्यौ",
      "मातुस्स्तनाविव शिशोरमृतायमानौ ।",
      "प्राप्तौ परस्परतुलामतुलान्तरौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १४॥",
    ],
    vicheda: [
      "प्रायः प्रपन्नजनताप्रथमावगाह्यौ",
      "मातुस्स्तनाविव शिशोरमृतायमानौ ।",
      "प्राप्तौ परस्परतुलामतुलान्तरौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १४॥",
    ],
    anvaya: [],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, whose attraction to those who surrender (prapannas) is like the breast of a mother for a suckling infant, spouting the incomparable spiritual ambrosia whereby they are nourished.",
    ],
    notes: [],
  },
  {
    chapter: "SVS_3",
    number: 15,
    sloka: [
      "सत्त्वोत्तरैस्सततसेव्यपदाम्बुजेन",
      "संसारतारकदयार्द्र दृगञ्चलेन ।",
      "सौम्योपयन्तृमुनिना मम दर्शितौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १५॥",
    ],
    vicheda: [
      "सत्त्वोत्तरैस्सततसेव्यपदाम्बुजेन",
      "संसारतारकदयार्द्र दृगञ्चलेन ।",
      "सौम्योपयन्तृमुनिना मम दर्शितौ ते",
      "श्रीवेङ्कटेशचरणौ शरणं प्रपद्ये ॥ १५॥",
    ],
    anvaya: [],
    transl: [
      "I take refuge in the lotus feet of Lord Venkatesvara, adored by the pious and virtuous, and which are a boat for crossing over this world of mundane existence: they were revealed to me by the gentle sage Manavalamamuni whose eyes were moist with compassion.",
    ],
    notes: [],
  },
  {
    chapter: "SVS_3",
    number: 16,
    sloka: [
      "श्रीश श्रिया घटिकया त्वदुपायभावे",
      "प्राप्ये त्वयि स्वयमुपेयतया स्फुरन्त्या ।",
      "नित्याश्रिताय निरवद्यगुणाय तुभ्यं",
      "स्यां किङ्करो वृषगिरीश न जातु मह्यम् ॥ १६॥",
    ],
    vicheda: [
      "श्रीश श्रिया घटिकया त्वदुपायभावे",
      "प्राप्ये त्वयि स्वयमुपेयतया स्फुरन्त्या ।",
      "नित्याश्रिताय निरवद्यगुणाय तुभ्यं",
      "स्यां किङ्करो वृषगिरीश न जातु मह्यम् ॥ १६॥",
    ],
    anvaya: [],
    transl: [
      "O Lord of Opulence, you yourself are the means to final beatitude, after reaching you, mother Lakshmi herself became the Mediatrix overflowing with compassion and solicitude, I have dedicated myself to your service for no reward whatsoever, but only to please you.",
    ],
    notes: [],
  },
];

export default verses;
// "॥ इति वेङ्कटेशप्रपत्ति ॥",
