const verses = [
  {
    chapter : 13,
    number  : 1,
    sloka   : [
      'अर्जुन उवाच |',
      'प्रकृतिं पुरुषं चैव क्षेत्रं क्षेत्रज्ञमेव च |',
      'एतद्वेदितुमिच्छामि ज्ञानं ज्ञेयं च केशव || '
    ],
    vicheda : [
      'तस्मात् असक्तः सततं कार्यं कर्म समाचर |',
      'असक्तः हि आचरन् कर्म परम् आप्नोति पूरुष: ||'
    ],
    anvaya  : [
      'तस्मात्, सततं असक्तः कार्यं कर्म समाचर |',
      'पूरुष: असक्तः कर्म आचरन् हि परम् आप्नोति |'
    ],
    transl  : [
      "Therefore, always perform your prescribed duty without attachment. For by performing work without attachment, a person attains the supreme goal (liberation)." 
    ],
    notes   : [
      "तस्मात् = Therefore",
      "सक्तः = (सञ्ज् - 1P - to cling/to stick to/to attach) - क्त प्रत्यय (past) = one who is attached)",
      "असक्तः = one who is not attached (masculine)",
      "असक्तः = Without attachment",
      "सततम् = Always",
      "कार्यम् = That which is to be done (duty)",
      "कर्म = Action / work",
      "कार्यं कर्म = Prescribed duty",
      "समाचर = Perform diligently - लोट्",
      "हि = Indeed",
      "असक्तः = Being unattached",
      "आचरन् = Performing",
      "कर्म = Action",
      "परम् = The supreme",
      "आप्नोति = Attains",
      "पूरुषः = A person"
    ],
  },
  {
    chapter : 13,
    number  : 8,
    sloka   : [
      'अमानित्वमदम्भित्वमहिंसा क्षान्तिरार्जवम् |',
      'आचार्योपासनं शौचं स्थैर्यमात्मविनिग्रह: || 8 ||',
      'इन्द्रियार्थेषु वैराग्यमनहङ्कार एव च |',
      'जन्ममृत्युजराव्याधिदु:खदोषानुदर्शनम् || 9 ||',
      'असक्तिरनभिष्वङ्ग: पुत्रदारगृहादिषु |',
      'नित्यं च समचित्तत्वमिष्टानिष्टोपपत्तिषु || 10 ||',
      'मयि चानन्ययोगेन भक्तिरव्यभिचारिणी |',
      'विविक्तदेशसेवित्वमरतिर्जनसंसदि || 11 ||',
      'अध्यात्मज्ञाननित्यत्वं तत्वज्ञानार्थदर्शनम् |',
      'एतज्ज्ञानमिति प्रोक्तमज्ञानं यदतोऽन्यथा || 12 ||',
    ],
    vicheda : [
      'अमानित्वम् अदम्भित्वम् अहिंसा क्षान्तिः आर्जवम् |',
      'आचार्योपासनं शौचं स्थैर्यम् आत्मविनिग्रहः || 8 ||',
      'इन्द्रियार्थेषु वैराग्यम् अनहङ्कारः एव च |',
      'जन्म-मृत्यु-जरा-व्याधि-दुःख-दोष-अनुदर्शनम् || 9 ||',
      'असक्तिः अनभिष्वङ्गः पुत्र-दार-गृहादिषु |',
      'नित्यं च समचित्तत्वम् इष्ट-अनिष्ट-उपपत्तिषु || 10 ||',
      'मयि च अनन्ययोगेन भक्तिः अव्यभिचारिणी |',
      'विविक्तदेशसेवित्वम् अरतिः जनसंसदि || 11 ||',
      'अध्यात्म-ज्ञान-नित्यत्वं तत्व-ज्ञानार्थ-दर्शनम् |',
      'एतत् ज्ञानम् इति प्रोक्तम् अज्ञानम् यत् अतः अन्यथा || 12 ||',
    ],
    anvaya  : [
      '- अमानित्वम्, अदम्भित्वम्, अहिंसा, क्षान्तिः, आर्जवम् ',
      '- आचार्योपासनं, शौचं, स्थैर्यम्, आत्मविनिग्रहः ',
      '- इन्द्रियार्थेषु वैराग्यम्, अनहङ्कारः',
      '- जन्म-मृत्यु-जरा-व्याधि-दुःख-दोष-अनुदर्शनम् ',
      '- असक्तिः, पुत्र-दार-गृहादिषु अनभिष्वङ्गः ',
      '- इष्ट-अनिष्ट-उपपत्तिषु (नित्यं) समचित्तत्वम् ',
      '- मयि अनन्य-योगेन (अव्यभिचारिणी) भक्तिः ',
      '- विविक्तदेशसेवित्वम्, जनसंसदि अरतिः ',
      '- अध्यात्म-ज्ञान-नित्यत्वं, तत्व-ज्ञानार्थ-दर्शनम् ',
      'एतत् ज्ञानम् इति प्रोक्तम्',
      'अतः यत् अन्यथा अज्ञानम् (प्रोक्तम्)',
    ],
    transl  : [
      "Humility, absence of hypocrisy, non-violence, forgiveness, uprightness, service to the teacher, purity, steadfastness, self-control; dispassion toward sense objects, absence of ego; constant reflection on the evils of birth, death, old age, and disease; detachment, absence of clinging to son, wife, and home; equanimity of mind in favorable and unfavorable circumstances; unwavering devotion to Me with undivided focus; love for solitude, disinterest in crowds; constancy in self-knowledge and perception of the goal of true knowledge—this is declared as knowledge, and what is contrary to this is ignorance." 
    ],
    notes   : [
      'अमानित्वम् = humility',
      'अदम्भित्वम् = absence of hypocrisy',
      'अहिंसा = non-violence',
      'क्षान्तिः = forgiveness',
      'आर्जवम् = straightforwardness',
      'आचार्योपासनम् = service to the teacher',
      'शौचम् = purity',
      'स्थैर्यम् = steadiness',
      'आत्मविनिग्रहः = self-control',
      '',
      'इन्द्रियार्थेषु = in objects of senses',
      'वैराग्यम् = dispassion',
      'अनहङ्कारः = absence of ego',
      'एव च = and also',
      'जन्म-मृत्यु-जरा-व्याधि-दुःख-दोष-अनुदर्शनम् = constant reflection on the evils of birth, death, old age, and disease',
      '',
      'असक्तिः = detachment',
      'अनभिष्वङ्गः = absence of attachment',
      'पुत्र-दार-गृहादिषु = towards son, wife, house, etc.',
      'नित्यं = always',
      'समचित्तत्वम् = equanimity of mind',
      'इष्ट-अनिष्ट-उपपत्तिषु = in favorable and unfavorable conditions',
      '',
      'मयि = towards Me',
      'च = and',
      'अनन्ययोगेन = through undivided devotion',
      'भक्तिः = devotion',
      'अव्यभिचारिणी = unflinching',
      'विविक्तदेशसेवित्वम् = preference for solitude',
      'अरतिः = disinterest',
      'जनसंसदि = in crowds of people',
      '',
      'अध्यात्मज्ञाननित्यत्वम् = constancy in spiritual knowledge',
      'तत्त्वज्ञानार्थदर्शनम् = perception of the goal of true knowledge',
      'एतत् = this',
      'ज्ञानम् = knowledge',
      'इति = thus',
      'प्रोक्तम् = is said',
      'अज्ञानम् = ignorance',
      'यत् = that which',
      'अतः अन्यथा = opposite to this'
    ],
  },
];

export default verses;