const verses = [
  {
    chapter : 1,
    number  : 1,
    sloka   : [
      "नमामीश्वरं सच्चिदानन्दरूपं",
      "लसत्कुण्डलं गोकुले भ्राजमानम् ।",
      "यशोदाभियोलूखलाद्धावमानं",
      "परामृष्टमत्यन्ततो द्रुत्य गोप्या ॥ १ ॥",
    ],
    sloka_tel : [
      "నమామీశ్వరం సచ్చిదానందరూపం",
      "లసత్కుండలం గోకులే భ్రాజమానమ్",
      "యశోదాభియోలూఖలాద్ ధావమానం",
      "పరామృష్టమత్యంతతో దృత్య గోప్యా ॥ 1 ॥"
    ],
    vicheda : [
      "नमामि ईश्वरम् सत्-चित्-आनन्द-रूपम्",
      "लसत्-कुण्डलम् गोकुले भ्राजमानम्",
      "यशोदा-भिया उलूखलात् धावमानम्",
      "परामृष्टम् अत्यन्ततः द्रुत्य गोप्या"
    ],
    anvaya  : [
      "(अहं)",
      "- ईश्वरम्",
      "- सत्-चित्-आनन्द-रूपम्", 
      "- लसत्-कुण्डलम्", 
      "- गोकुले भ्राजमानम्", 
      "- यशोदा-भिया उलूखलात् धावमानम्", 
      "- गोप्या अत्यन्ततः द्रुत्य परामृष्टम्",
      "नमामि",
    ],
    transl  : [
      "(I)", 
      "- to the Supreme Lord",
      "- whose form is the embodiment of eternal existence, knowledge, and bliss",
      "- whose earrings are swinging",
      "- who is shining in Gokula",
      "- who is running away from the wooden mortar, due to the fear of Mother Yashoda,",
      "- (but) who has been caught from behind by Mother Yashoda (Gopi) after running with great effort after him.",
      "bow down (offer my obeisances).",
    ],
    essence : [
      "To the Supreme Lord, whose form is the embodiment of eternal existence, knowledge, and bliss, whose earrings are swinging, who is beautifully shining in the divine realm of Gokula, who (due to the offense of breaking the pot of yogurt that His mother was churning into butter and then stealing the butter that was kept hanging from a swing) is quickly running from the wooden grinding mortar in fear of mother Yasoda, but who has been caught from behind by her who ran after Him with greater speed--to that Supreme Lord, Sri Damodara, I offer my humble obeisances."
    ],
    essence_tel: [
      "సచ్చిదానంద స్వరూపుడు, ప్రకాశించే కుండలములు కలవాడు, గోకులంలో విరాజిల్లేవాడు, యశోదమ్మకు భయపడి రోలు నుండి దూకి పరుగెడుతూ, ఆమె చేత పట్టుబడినవాడైన ఆ పరమేశ్వరునికి (శ్రీ దామోదరునికి) నా నమస్కారములు."
    ],
    meanings: [
      "namāmi: I offer my obeisances",
      "īśvaram: to the Supreme Lord",
      "sac-cid-ānanda-rūpam: whose form is eternal, full of knowledge and bliss",
      "lasat-kuṇḍalam: whose earrings are swinging/glistening",
      "gokule: in the land of Gokula",
      "bhrājamānam: shining brilliantly",
      "yaśodā-bhiyā: due to fear of Yashoda",
      "ulūkhalāt: from the wooden grinding mortar",
      "dhāvamānam: running away",
      "parāmṛṣṭam: caught/grasped from behind",
      "atyantataḥ: greatly/completely (adverb)",
      "drutyā: running quickly",
      "gopyā: by the Gopi (Mother Yashoda)"
    ],
    notes   : [
      "Krishna had broken a pot of yogurt and was feeding butter to the monkeys while sitting on a wooden grinding mortar (ulūkhala). When he saw Mother Yashoda approaching with a whipping stick, he jumped off the mortar in a state of 'staged' panic.",
      "The phrase is philosophically profound because it describes the Fear of Fear personified. The Upanishads state that fear itself is afraid of the Supreme Lord, yet here, out of love for His devotee, the Lord is yaśodā-bhiyā (fearing Yashoda).",
      "The word 'atyantataḥ' emphasizes that Yashoda had to run very fast to catch the Lord, who is usually unreachable by mind or speech.",
      "This lila takes place on the day of Deepavali.",
      "यशोदा-भिया = Instrumental Case - भीः (भयम्) - तृतीया विभक्ति - एकवचनम् - 'due to the fear of Mother Yashoda'",
      "उलूखलात् - Ablative Case - उलूखलम् (उलूखल) (wooden grinding mortar) - पञ्चमी विभक्ति - एकवचनम् - 'from the wooden grinding mortar'",
      "धावमानम् - Present Participle - धावमानः - धाव् (to run) - शानच् परत्ययः - 'running away'",
      "द्रुत्य (drutya): This is a Lyap-pratyaya (similar to ktvā, meaning 'having done'). It comes from the root dru (to run/flow). It signifies that Yashoda had to run with great speed before the moment of catching occurred.",
      "परामृष्टम् - परा (parā) + मृश् (mṛś) + क्त (kta) ",
      "परा (parā) = A prefix (upasarga) that can mean 'back,' 'away,' or 'opposite.' In this specific context, it signifies 'from behind' or reaching back.",
      " मृश् (mṛś) = A root verb meaning 'to touch,' 'to grasp,' or 'to catch.'",
      "क्त (kta) = A suffix (pratyaya) that indicates the past participle form, meaning 'having been done.'",
      "अत्यन्ततः (atyantataḥ): The suffix -tasi (tah) is used here in the sense of the ablative or adverbial. It emphasizes the intensity. It implies that she didn't just catch Him casually; she had to exert herself 'to the extreme' to catch the Lord who is usually faster than the mind.",
    ]
  },
  {
    chapter : 1,
    number  : 2,
    sloka   : [
      "रुदन्तं मुहुर्नेत्रयुग्मं मृजन्तं",
      "कराम्भोजयुग्मेन सातङ्कनेत्रम् ।",
      "मुहुः श्वासकम्पत्रिरेखाङ्ककण्ठ-",
      "स्थितग्रैव-दामोदरं भक्तिबद्धम् ॥ २ ॥",
    ],
    sloka_tel : [
      "రుదంతం ముహుర్ నేత్ర-యుగ్మం మృజంతమ్",
      "కరాంభోజ-యుగ్మేన సాతఙ్క-నేత్రమ్",
      "ముహుః శ్వాస-కంప-త్రిరేఖాంక-కంఠ",
      "స్థిత-గ్రైవం దామోదరం భక్తి-బద్ధమ్ ॥ 2 ॥",
    ],
    vicheda : [
      "रुदन्तम् मुहुः नेत्र-युग्मम् मृजन्तम्",
      "कर-अम्भोज-युग्मेन स-आतङ्क-नेत्रम्",
      "मुहुः श्वास-कम्प-त्रि-रेखा-अङ्क-कण्ठ",
      "स्थित-ग्रैवं दाम-उदरम् भक्ति-बद्धम्",
    ],
    anvaya  : [
      "(अहं)",
      "- मुहुः रुदन्तम्",
      "- कर-अम्भोज-युग्मेन नेत्र-युग्मम् मृजन्तम्",
      "- स-आतङ्क-नेत्रम्",
      "- मुहुः श्वास-कम्प-त्रि-रेखा-अङ्क-कण्ठ-स्थित-ग्रैवम्",
      "- भक्ति-बद्धम्",
      "- दाम-उदरम्",
      "(नमामि)",
    ],
    transl  : [
      "(I)", 
      "- who is crying again and again,",
      "- who, with His two lotus-like hands rubbing His pair of eyes,",
      "- whose eyes are full of fear,",
      "- whose pearl necklace situated on His neck, marked with three lines like a conch shell, is trembling due to His agitated breathing,",
      "- who is bound by love of his devotee,",
      "- to Lord Damodara (one whose belly is bound with a rope)",
      "bow down (offer my obeisances).",
    ],
    essence : [
      "(Seeing the whipping stick in His mother's hand) He is crying and rubbing His eyes again and again with His two lotus hands. His eyes are filled with fear, and the necklace of pearls around His neck, which is marked with three lines like a conch shell, is shaking because of His quick breathing due to crying. To this Supreme Lord, Sri Damodara, whose belly is bound not with ropes but with His mother's pure love, I offer my humble obeisances.",
    ],
    essence_tel: [
      "తల్లి చేతిలోని కర్రను చూసి భయంతో ఏడుస్తూ, తన పద్మముల వంటి రెండు చేతులతో కళ్లను పదే పదే తుడుచుకుంటున్నవాడు, భయంతో నిండిన కన్నులు కలవాడు, ఏడుపు వల్ల కలిగే నిట్టూర్పుల చేత కంఠంలోని ముత్యాల హారము కదులుతున్నవాడు, త్రికంఠరేఖలు కలవాడు మరియు కేవలం భక్తి చేతనే కట్టబడినవాడైన ఆ శ్రీ దామోదరునికి నా నమస్కారములు.",
    ],
    meanings: [
      "rudantam: crying",
      "muhuḥ: again and again",
      "netra-yugmam: the pair of eyes",
      "mṛjantam: rubbing",
      "karāmbhoja-yugmena: with His two lotus-like hands",
      "sātaṅka-netram: whose eyes are full of fear",
      "śvāsa-kampa: trembling due to breathing",
      "tri-rekhāṅka-kaṇṭha: whose neck is marked with three lines (like a conch)",
      "sthita-graivam: the pearl necklace situated on His neck",
      "dāma-udaram: whose belly (udara) is bound by a rope (dāma)",
      "bhakti-baddham: who is bound by devotion",
    ],
    notes   : [
      "The term 'tri-rekhā' refers to the three lines on the neck, considered a sign of supreme beauty and divinity, often compared to the spirals of a conch shell.",
      "The phrase 'bhakti-baddham' is the theological heart of this verse, showing that the Infinite can only be captured by pure love.",
      "रुदन्तम् = रुद् (rud) + शतृ (śatṛ) = रुदन् - द्वितीया विभक्ति - present participle",
      "युग्मम् = युज् (yuj) + म (ma) - Kṛt-pratyaya = pair",
      "ग्रैवम् = ग्रीवा (grīvā) - 'neck.' = refers to necklace here",

    ],
  },
  {
    chapter : 1,
    number  : 3,
    sloka   : [
      "इतीदृक् स्वलीलाभिरानन्दकुण्डे",
      "स्वघोषं निमज्जन्तमाख्यापयन्तम् ।",
      "तदीयेषिताज्ञेषु भक्तैर्जितत्वं",
      "पुनः प्रेमतस्तं शतावृत्ति वन्दे ॥ ३ ॥",
    ],
    sloka_tel : [
      "ఇతీదృక్ స్వ-లీలాభిర్ ఆనంద-కుండే",
      "స్వ-ఘోషం నిమజ్జంతమ్ ఆఖ్యాపయంతమ్",
      "తదీయేషిత-జ్ఞేషు భక్తైర్ జితత్వం",
      "పునః ప్రేమతస్ తం శతావృత్తి వందే ॥ 3 ॥",
    ],
    vicheda : [
      "इति ईदृक् स्व-लीलाभिः आनन्द-कुण्डे",
      "स्व-घोषम् निमज्जन्तम् आख्यापयन्तम्",
      "तदीय-ईषित-ज्ञेषु भक्तैः जितत्वम्",
      "पुनः प्रेमतः तम् शत-आवृत्ति वन्दे",
    ],
    anvaya  : [
      "(अहं)",
      "- इति ईदृक् स्व-लीलाभिः स्व-घोषम् आनन्द-कुण्डे निमज्जन्तम्,",
      "- (तदीय-ईषित-ज्ञेषु भक्तैः जितत्वम्) आख्यापयन्तम्,",
      "- (दाम-उदरम्) तम्",
      "पुनः प्रेमतः शत-आवृत्ति वन्दे",
    ],
    transl  : [
      "(I)", 
      "- who drowns the inhabitants of Gokula in pools of ecstasy, with such childhood pastimes",
      "- who declares that He is conquered only by His intimate devotees to those who are absorbed in His majestic aspect (aisvarya),",
      "- to that Lord Damodara,", 
      "again offer my obeisances hundreds of times with great love.",
    ],
    essence : [
      "By such childhood pastimes as this He is drowning the inhabitants of Gokula in pools of ecstasy, and is revealing to those devotees who are absorbed in knowledge of His supreme majesty and opulence that He is only conquered by devotees whose pure love is imbues with intimacy and is free from all conceptions of awe and reverence. With great love I again offer my obeisances to Lord Damodara hundreds and hundreds of times.",
    ],
    essence_tel: [
      "ఇటువంటి తన బాల్య లీలల ద్వారా గోకులవాసులందరినీ ఆనందమనే కొలనులో ముంచెత్తుతున్నవాడు, తన ఐశ్వర్య జ్ఞానము కలిగిన వారికి తాను కేవలం భక్తుల ప్రేమకు మాత్రమే లొంగుతానని చాటి చెప్పేవాడు అయిన ఆ దామోదరునికి ప్రేమతో వందల పర్యాయాలు నమస్కరిస్తున్నాను.",
    ],
    meanings: [
      "iti: in this way",
      "īdṛk: such (pastimes)",
      "sva-līlābhiḥ: by His own pastimes",
      "ānanda-kuṇḍe: in a pool of bliss",
      "sva-ghoṣam: His own village (Gokula)",
      "nimajjantam: immersion/drowning",
      "ākhyāpayantam: to the one who is proclaiming/revealing",
      "tadīya-īṣita-jñeṣu: to those who know His majesty",
      "bhaktaiḥ: by His devotees",
      "jitatvam: the state of being conquered",
      "punaḥ: again",
      "premataḥ: with love",
      "tam: to Him",
      "śata-āvṛtti: hundreds of times",
      "vande: I praise/bow",
    ],
    notes   : [
      "The contrast between 'Aisvarya-jnana' (knowledge of majesty) and 'Madhurya' (sweetness) is highlighted here; the Lord prefers the latter.",
      "The phrase 'Sva-ghosam' refers to the cowherd settlement of Vraja, which vibrates with the sound of Krishna's glories.",
      "तदीय = His / Relating to Him",
      "ईषित = Majesty / Godhood / Opulence / Sovereignty",
      "ज्ञेषु = To the knowers / Among those who know",
      "जितत्वम् = The state of being conquered",
      "जितत्वम् = जि (root - to win/conquer) + kta (Past Passive Participle - winner) + त्व (Taddhita-pratyaya - abstract noun = -ness/-ship/-hood)",
      "आख्यापयन्तम् = Present Participle (Śatṛ Pratyaya) - dwitiya vibhakti",
      "आख्यापयन्तम् = आ (upasarga - fully) + ख्या (root - to know) + णिच् (make someone know) + शतृ (ongoing action)",
      "आवृत्ति = आ (fully) + वृत् (to turn/rotate) + क्तिन् (suffix used to form feminine abstract nouns from verbal roots) = times/repetitions",
    ],
  },
  {
    chapter : 1,
    number  : 4,
    sloka   : [
      "वरं देव मोक्षं न मोक्षावधिं वा",
      "न चान्यं वृणेऽहं वरेषादपीह ।",
      "इदं ते वपुर्नाथ गोपालबालं",
      "सदा मे मनस्याविरास्तां किमन्यैः ॥ ४ ॥",
    ],
    sloka_tel : [
      "వరం దేవ మోక్షం న మోక్షావధిం వా",
      "న చాన్యం వృణేऽహం వరేషాద్ అపీహ",
      "ఇదం తే వపుర్ నాథ గోపాల-బాలం",
      "సదా మే మనస్య్ ఆవిరాస్తాం కిమ్ అన్యైః ॥ 4 ॥",
    ],
    vicheda : [
      "वरम् देव मोक्षम् न मोक्ष-अवधिम् वा",
      "न च अन्यम् वृणे अहम् वरेषात् अपि इह",
      "इदम् ते वपुः नाथ गोपाल-बालम्",
      "सदा मे मनसि आविरास्ताम् किम् अन्यैः",
    ],
    anvaya  : [
      "(हे) देव! इह",
      "अहम्",
      "- वरम्",  
      "- मोक्षम्", 
      "- मोक्ष-अवधिम् वा",
      "- वर-ईशात् अन्यम् अपि",
      "न वृणे",
      "(हे) नाथ!",
      "ते इदम् गोपाल-बालम् वपुः सदा मे मनसि आविरास्ताम्",
      "अन्यैः किम्?",
    ],
    transl  : [
      "O Lord! In this world,",
      "I",
      "- any boon,",
      "- liberation,",
      "- the highest limit of liberation (Vaikuntha),",
      "- any other boon even if it is the best",
      "do not ask for",
      "O Lord!",
      "This form of Yours as a cowherd child (Bala Gopala) may always remain manifest in my heart,",
      "What is the use of any other boon to me?",
    ],
    essence : [
      "O Lord, although You are able to give all kinds of benedictions, I do not pray to You for the boon of impersonal liberation, nor the highest liberation of eternal life in Vaikuntha, nor any other boon (which may be obtained by executing the nine processes of bhakti). O Lord, I simply wish that this form of Yours as Bala Gopala in Vrndavana may ever be manifest in my heart, for what is the use to me of any other boon besides this?",
    ],
    essence_tel: [
      "ఓ దేవా! నీవు సమస్త వరములను ప్రసాదించగలవాడవు అయినప్పటికీ, నాకు మోక్షం వద్దు, మోక్షమునకు పరాకాష్ట అయిన వైకుంఠ ప్రాప్తి వద్దు, మరితర వరములు కూడా వద్దు. ఓ నాథా! నీ ఈ బాల గోపాల రూపం నా మనస్సులో ఎల్లప్పుడూ నిలిచి ఉంటే చాలు. అది లేని నాడు ఇతర వరములతో నాకేమి పని?",
    ],
    meanings: [
      "varam: boon",
      "deva: O Lord",
      "mokṣam: liberation",
      "na: not",
      "mokṣa-avadhim: the highest limit of liberation",
      "vā: or",
      "na ca anyam: nor anything else",
      "vṛṇe 'ham: I choose/ask for",
      "vareṣāt api: even from the best of boons",
      "iha: here/in this world",
      "idam te vapuḥ: this form of Yours",
      "nātha: O Master",
      "gopāla-bālam: a cowherd child",
      "sadā: always",
      "me manasi: in my heart/mind",
      "āvirāstām: may it be manifest",
      "kim anyaiḥ: what is the use of others?",
    ],
    notes   : [
      "The phrase 'mokṣa-avadhim' typically refers to the state of Sayujya-mukti (merging into the Brahman) or the opulences of Vaikuntha, both of which a pure devotee sets aside in favor of seeing the Lord.",
      "The use of 'Gopala-balam' emphasizes the specific beauty of Krishna's childhood form over His more majestic (Aisvarya) forms.",
    ],
  },
  {
    chapter : 1,
    number  : 5,
    sloka   : [
      "इदं ते मुखाम्भोजमत्यन्तनीलैर्-",
      "वृतं कुन्तलैः स्निग्ध-रक्तैश्च गोप्या ।",
      "मुहुश्चुम्बितं बिम्बरक्तधरं मे",
      "मनस्याविरास्तां अलं लक्षलाभैः ॥ ५ ॥",
    ],
    sloka_tel : [
      "ఇదం తే ముఖాంభోజమ్ అత్యంత-నీలైర్",
      "వృతం కుంతలైః స్నిగ్ధ-రక్తైశ్ చ గోప్యా",
      "ముహుశ్ చుంబితం బింబ-రక్తాధరం మే",
      "మనస్య్ ఆవిరాస్తామ్ అలం లక్ష-లాభైః ॥ 5 ॥",
    ],
    vicheda : [
      "इदम् ते मुख-अम्भोजम् अत्यन्त-नीलैः",
      "वृतम् कुन्तलैः स्निग्ध-रक्तैः च गोप्या",
      "मुहुः चुम्बितम् बिम्ब-रक्त-अधरम् मे",
      "मनसि आविरास्ताम् अलम् लक्ष-लाभैः",
    ],
    anvaya  : [
      "ते इदम् मुख-अम्भोजम्",
      "- अत्यन्त-नीलैः स्निग्ध-रक्तैः च कुन्तलैः वृतम्,", 
      "- गोप्या मुहुः चुम्बितम्,", 
      "बिम्ब-रक्त-अधरम्",  
      "मे मनसि आविरास्ताम्,",
      "लक्ष-लाभैः अलम् ।",
    ],
    transl  : [
      "This lotus face of yours",
      "- is encircled by locks of soft black hair tinged with red,",
      "- is kissed again and again by mother Yasoda,",
      "Your lips are as red as the bimba fruit.",
      "May this form of yours always manifest in my heart",
      "What is the use of thousands of other gains to me?",
    ],
    essence : [
      "O Lord, Your lotus face, which is encircled by locks of soft black hair tinged with red, is kissed again and again by mother Yasoda, and Your lips are reddish like the bimba fruit. May this beautiful vision of Your lotus face be ever manifest in my heart. Thousands and thousands of other benedictions are of no use to me.",
    ],
    essence_tel: [
      "ఓ దేవా! చిక్కని నలుపు మరియు ఎరుపు రంగులు కలిసిన మృదువైన ముంగురులతో నిండిన నీ ముఖపద్మమును యశోదమ్మ పదే పదే ముద్దాడుతోంది. దొండపండు వలె ఎర్రని నీ అధరములతో కూడిన ఆ అందమైన ముఖము నా మనస్సులో ఎల్లప్పుడూ నిలిచి ఉండుగాక. వేలకొద్దీ ఇతర లాభములతో నాకు పనిలేదు.",
    ],
    meanings: [
      "idam: this",
      "te: Your",
      "mukha-ambhojam: lotus face",
      "atyanta-nīlaiḥ: very dark blue/black",
      "vṛtam: surrounded/encircled",
      "kuntalaiḥ: by locks of hair",
      "snigdha-raktaiḥ: soft and reddish",
      "ca: and",
      "gopyā: by the Gopi (Yashoda)",
      "muhuḥ: repeatedly",
      "cumbitam: kissed",
      "bimba-rakta-adharam: lips as red as the bimba fruit",
      "me manasi: in my heart",
      "āvirāstām: may it be manifest",
      "alam: enough/useless",
      "lakṣa-lābhaiḥ: with hundreds of thousands of gains",
    ],
    notes   : [
      "The 'bimba' fruit is a traditional poetic comparison in Sanskrit for deep red, luscious lips.",
      "The term 'snigdha-raktaiḥ' describes hair that is naturally glossy (soft) with a reddish-gold hue, often seen in the hair of young children or divine personalities.",
    ],
  },
  {
    chapter : 1,
    number  : 6,
    sloka   : [
      "नमो देव दामोदरानन्त विष्णो",
      "प्रसीद प्रभो दुःखजालाब्धिमग्नम् ।",
      "कृपादृष्टिवृष्ट्यातिदीनं बतानु",
      "गृहाणेश मां अज्ञमेध्यक्षिदृश्यः ॥ ६ ॥",
    ],
    sloka_tel : [
      "నమో దేవ దామోదరానంత విష్ణో",
      "ప్రసీద ప్రభో దుఃఖ-జాలాబ్ధి-మగ్నమ్",
      "కృపా-దృష్టి-వృష్ట్యాతి-దీనం బతాను",
      "గృహాణేష మామ్ అజ్ఞమ్ ఏధ్య్ అక్షి-దృశ్యః ॥ 6 ॥",
    ],
    vicheda : [
      "नमः देव दामोदर अनन्त विष्णो",
      "प्रसीद प्रभो दुःख-जाल-अब्धि-मग्नम्",
      "कृपा-दृष्टि-वृष्ट्या अति-दीनम् बत अनु-",
      "गृहाण ईश माम् अज्ञम् एधि अक्षि-दृश्यः",
    ],
    anvaya  : [
      "हे देव! दामोदर! अनन्त! विष्णो! (ते) नमः।", 
      "हे प्रभो! प्रसीद।", 
      "बत! (दुःख-जाल-अब्धि-मग्नम्) (अति-दीनम्) (अज्ञम्) माम् कृपा-दृष्टि-वृष्ट्या अनुगृहाण।", 
      "हे ईश! मम अक्षि-दृश्यः एधि ।",
    ],
    transl  : [
      "O Divine Lord! O Damodara! O Ananta! O Vishnu! My obeisances unto You.", 
      "O Master! Please become pleased with me!", 
      "Alas! Please uplift me who is sunken in an ocean of worldly sorrows, greatly distressed, an ignorant with Your glance of mercy,", 
      "O Lord! Please become visible to my eyes.",
    ],
    essence : [
      "O Supreme Godhead, I offer my obeisances unto You. O Damodara! O Ananta! O Vishnu! O master! O my Lord, be pleased upon me. By showering Your glance of mercy upon me, deliver this poor ignorant fool who is immersed in an ocean of worldly sorrows, and become visible to my eyes.",
    ],
    essence_tel: [
      "ఓ దేవా! దామోదరా! అనంతా! విష్ణుమూర్తి! నీకు నమస్కారము. ఓ ప్రభూ! నాపై ప్రసన్నుడవు కావాలి. సంసార దుఃఖాలనే సముద్రంలో మునిగిపోయి, దిక్కులేనివాడినై అజ్ఞానంలో ఉన్న నన్ను నీ కరుణా కటాక్ష వీక్షణములతో ఉద్ధరించు. ఓ ఈశ్వరా! నా కనులకు ప్రత్యక్షము కావాలి.",
    ],
    meanings: [
      "namaḥ: obeisances",
      "deva: O Divine Lord",
      "dāmodara: O Damodara (bound at the waist)",
      "ananta: O Limitless One",
      "viṣṇo: O All-pervading One",
      "prasīda: be pleased",
      "prabho: O Master",
      "duḥkha-jāla-abdhi-magnam: immersed in the ocean of a network of sorrows",
      "kṛpā-dṛṣṭi-vṛṣṭyā: with the rain of Your merciful glance",
      "ati-dīnam: very miserable/wretched",
      "bata: alas",
      "anugṛhāṇa: kindly uplift/favor",
      "īṣa: O Supreme Controller",
      "mām: me",
      "ajñam: ignorant one",
      "edhi: please come/be",
      "akṣi-dṛśyaḥ: visible to the eyes",
    ],
    notes   : [
      "This verse shifts from praising the Lord's form to a direct, humble prayer for deliverance from 'Samsara' (the material cycle of birth and death).",
      "The term 'Ananta' highlights that while He is bound as Damodara, He remains the Infinite and Limitless Lord.",
      "बत = Alas! (expressing sorrow)",
      "अनुगृहाण = अनु + ग्रह् (root) = कृपा करना, अनुग्रह करना - कर्तरि लोट् - madhyama पुरुष - एकवचन = please uplift/favor",
      "एधि = अस् (root) - अस्ति - कर्तरि लोट् - madhyama पुरुष - एकवचन = please come/be",
    ],
  },
  {
    chapter : 1,
    number  : 7,
    sloka   : [
      "कुवेरात्मजौ बद्धमूर्त्यैव यद्वत्",
      "त्वया मोचितौ भक्तिभाजौ कृतौ च ।",
      "तथा प्रेमभक्तिं स्वकं मे प्रयच्छ",
      "न मोक्षे ग्रहो मेऽस्ति दामोदरेह ॥ ७ ॥",
    ],
    sloka_tel : [
      "కువేరాత్మజౌ బద్ధ-మూర్త్యైవ యద్వత్",
      "త్వయా మోచితౌ భక్తి-భాజౌ కృతౌ చ",
      "తథా ప్రేమ-భక్తిం స్వకాం మే ప్రయచ్ఛ",
      "న మోక్షే గ్రహో మే ऽస్తి దామోదరేహ ॥ 7 ॥",
    ],
    vicheda : [
      "कुवेर-आत्मजौ बद्ध-मूर्त्या एव यद्वत्",
      "त्वया मोचितौ भक्ति-भाजौ कृतौ च",
      "तथा प्रेम-भक्तिम् स्वकाम् मे प्रयच्छ",
      "न मोक्षे ग्रहः मे अस्ति दामोदर इह",
    ],
    anvaya  : [
      "यद्वत् (बद्ध-मूर्त्या) त्वया कुवेर-आत्मजौ मोचितौ भक्ति-भाजौ कृतौ च", 
      "तथा मे स्वकाम् प्रेम-भक्तिम् प्रयच्छ।", 
      "हे दामोदर! इह मोक्षे मे ग्रहः न अस्ति ।",
    ],
    transl  : [
      "Just as the two sons of Kuvera (Nalakuvara and Manigriva) were delivered and turned into great devotees by You in Your form bound to the mortar,", 
      "Similarly, please grant me Your own pure loving devotion (prema-bhakti).", 
      "O Lord Damodara, I have no desire for liberation in this world.",
    ],
    essence : [
      "O Lord Damodara, just as the two sons of Kuvera--Manigriva and Nalakuvara--were delivered from the curse of Narada and made into great devotees by You in Your form as a baby tied with rope to a wooden grinding mortar, in the same way, please give to me Your own prema-bhakti. I only long for this and have no desire for any kind of liberation.",
    ],
    essence_tel: [
      "ఓ దామోదరా! రోలుకు కట్టబడిన రూపంలో ఉన్న నీవు కుబేరుని పుత్రులైన నలకూబర మణిగ్రీవులను శాపం నుండి విముక్తులను చేసి, వారిని గొప్ప భక్తులుగా ఎలా మార్చావో, అలాగే నాకు నీపై అనన్యమైన ప్రేమ భక్తిని ప్రసాదించు. నాకు మోక్షంపై ఎటువంటి ఆసక్తి లేదు.",
    ],
    meanings: [
      "kuvera-ātmajau: the two sons of Kuvera",
      "baddha-mūrtyā: by the form bound (to the mortar)",
      "eva: indeed",
      "yadvat: just as",
      "tvayā: by You",
      "mocitau: were liberated",
      "bhakti-bhājau: recipients of devotion",
      "kṛtau: were made",
      "ca: and",
      "tathā: in that same way",
      "prema-bhaktim: loving devotion",
      "svakām: Your own",
      "me: to me",
      "prayaccha: please grant",
      "na: not",
      "mokṣe: in liberation",
      "grahaḥ: obsession/desire",
      "me asti: I have",
      "dāmodara: O Lord Damodara",
      "iha: here/in this matter",
    ],
    notes   : [
      "The sons of Kuvera were cursed by Narada Muni to stand as Yamala-Arjuna trees until Krishna uprooted them with the grinding mortar.",
      "The phrase 'na mokṣe graho' emphasizes that the devotee considers 'Prema-bhakti' to be the 'fifth goal of life' (pañcama-puruṣārtha), superior even to salvation.",
    ],
  },
  {
    chapter : 1,
    number  : 8,
    sloka   : [
      "नमस्तेऽस्तु दाम्ने स्फुरद्दीप्तिधाम्ने",
      "त्वदीयोदरायाथ विश्वस्य धाम्ने ।",
      "नमो राधिकायै त्वदीयप्रियायै",
      "नमोऽनन्तलीलाय देवाय तुभ्यम् ॥ ८ ॥",
    ],
    sloka_tel : [
      "నమస్ తే ऽస్తు దామ్నే స్ఫురద్-దీప్తి-ధామ్నే",
      "త్వదీయోదరాయాథ విశ్వస్య ధామ్నే",
      "నమో రాధికాయై త్వదీయ-ప్రియాయై",
      "నమో ऽనంత-లీలాయ దేవాయ తుభ్యమ్ ॥ 8 ॥",
    ],
    vicheda : [
      "नमः ते अस्तु दाम्ने स्फुरत्-दीप्ति-धाम्ने",
      "त्वदीय-उदराय अथ विश्वस्य धाम्ने",
      "नमः राधिकायै त्वदीय-प्रियायै",
      "नमः अनन्त-लीलाय देवाय तुभ्यम्",
    ],
    anvaya  : [
      "स्फुरत्-दीप्ति-धाम्ने ते दाम्ने नमः अस्तु ।", 
      "अथ विश्वस्य धाम्ने त्वदीय-उदराय नमः ।", 
      "त्वदीय-प्रियायै राधिकायै नमः ।", 
      "अनन्त-लीलाय देवाय तुभ्यम् नमः ।",
    ],
    transl  : [
      "O Lord, I offer my obeisances to the rope that binds You, which is a reservoir of brilliant effulgence.", 
      "I then offer my obeisances to Your belly, which is the support of the entire universe.", 
      "I offer my obeisances to Your beloved Srimati Radharani,", 
      "and I offer my obeisances to You, the Supreme Lord of unlimited pastimes.",
    ],
    essence : [
      "O Lord Damodara, I first of all offer my obeisances to the brilliantly effulgent rope which binds Your belly. I then offer my obeisances to Your belly, which is the abode of the entire universe. I humbly bow down to Your most beloved Srimati Radharani, and I offer all obeisances to You, the Supreme Lord, who displays unlimited pastimes.",
    ],
    essence_tel: [
      "ఓ దామోదరా! నీ ఉదరమును చుట్టి ఉన్న ప్రకాశవంతమైన ఆ తాడుకు నా నమస్కారము. సమస్త బ్రహ్మాండములకు నిలయమైన నీ ఉదరమునకు నా నమస్కారము. నీకు అత్యంత ప్రియమైన శ్రీమతి రాధారాణికి నా నమస్కారము. అనంతమైన లీలలను ప్రదర్శించే ఓ దైవమా! నీకు నా వందనములు.",
    ],
    meanings: [
      "namaḥ: obeisances",
      "te: to You",
      "astu: let there be",
      "dāmne: to the rope",
      "sphurat-dīpti-dhāmne: which is the abode of brilliant effulgence",
      "tvadīya-udarāya: to Your belly",
      "atha: and then",
      "viśvasya dhāmne: the abode of the universe",
      "namaḥ rādhikāyai: obeisances to Radharani",
      "tvadīya-priyāyai: Your beloved",
      "ananta-līlāya: of unlimited pastimes",
      "devāya: to the Lord",
      "tubhyam: to You",
    ],
    notes   : [
      "The 'dāma' (rope) is not material; it represents the 'Dāma-śakti' or the binding power of the devotee's love.",
      "The mention of Radharani at the end of the prayer is significant as she is the personification of the highest devotion (Mahabhava) that binds Krishna.",
    ],
  },
];

// इति श्रीमद्पद्मपुराणे श्री दामोदराष्टाकं सम्पूर्णम् ॥

export default verses;