const verses = [
  {
    chapter : 1,
    number  : 1,
    sloka   : [
      "देव्युवाच",
      "देवदेव! महादेव! त्रिकालज्ञ! महेश्वर!",
      "करुणाकर देवेश! भक्तानुग्रहकारक! ॥",
      "अष्टोत्तर शतं लक्ष्म्याः श्रोतुमिच्छामि तत्त्वतः ॥",
    ],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 2,
    sloka   : [],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 3,
    sloka   : [],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 4,
    sloka   : [],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 5,
    sloka   : [],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 7,
    sloka   : [],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
  {
    chapter : 1,
    number  : 8,
    sloka   : [],
    sloka_tel : [],
    vicheda : [],
    anvaya  : [],
    transl  : [],
    essence : [],
    essence_tel: [],
    meanings: [],
    notes   : [],
  },
];

export default verses;